const NAV=[
['dashboard','⌂','Dashboard'],['portfolio','◫','Portfolio'],['transactions','↕','Transaktionen'],['analysis','◎','HPOS Analyse'],['radar','⌁','HPOS Radar'],['news','◉','News & Thesis'],['watchlist','☆','Watchlist'],['halal','✓','Halal Register'],['income','€','Income'],['rules','§','Regeln & Governance'],['settings','⚙','Daten & Einstellungen']
];
const RULES={healthcareCap:30,sukukTarget:15,cashMin:2,watchlistMax:15,minPosition:300,dividendGoalMonthly:100,goalDate:'2029-10-31'};
const DEFAULT={cash:0,positions:[],transactions:[],watchlist:[],halal:[],news:[],rules:RULES,createdAt:new Date().toISOString()};
let state=load();let page='dashboard';
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n||0));
function load(){try{return Object.assign(structuredClone(DEFAULT),JSON.parse(localStorage.getItem('hposState')||'{}'))}catch{return structuredClone(DEFAULT)}}
function save(){localStorage.setItem('hposState',JSON.stringify(state));}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function nav(){const n=$('#nav');n.innerHTML=NAV.map(([id,ic,label])=>`<button class="nav-btn ${page===id?'active':''}" data-page="${id}"><span class="nav-icon">${ic}</span><span>${label}</span></button>`).join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>{page=b.dataset.page;closeMenu();render()})}
function openMenu(){$('#sidebar').classList.add('open');$('#scrim').classList.add('show');$('#sidebar').setAttribute('aria-hidden','false');$('#menuBtn').setAttribute('aria-expanded','true')}
function closeMenu(){$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show');$('#sidebar').setAttribute('aria-hidden','true');$('#menuBtn').setAttribute('aria-expanded','false')}
function totalValue(){return state.cash+state.positions.reduce((s,p)=>s+Number(p.qty||0)*Number(p.price||p.avg||0),0)}
function positionValue(p){return Number(p.qty||0)*Number(p.price||p.avg||0)}
function metric(title,value,sub=''){return `<div class="card metric"><small>${title}</small><strong>${value}</strong>${sub?`<small>${sub}</small>`:''}</div>`}
function heading(kicker,title,sub=''){return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1>${sub?`<div class="muted">${sub}</div>`:''}</div></div>`}
function risk(){const total=Math.max(totalValue(),1);const sukuk=state.positions.filter(p=>/sukuk/i.test(p.assetClass||'')).reduce((s,p)=>s+positionValue(p),0)/total*100;const health=state.positions.filter(p=>/health/i.test(p.sector||'')).reduce((s,p)=>s+positionValue(p),0)/total*100;const cash=state.cash/total*100;const alerts=[];if(sukuk<RULES.sukukTarget)alerts.push(['warn',`Sukuk ${sukuk.toFixed(1)} % – Ziel ${RULES.sukukTarget} %`]);if(health>RULES.healthcareCap)alerts.push(['bad',`Healthcare ${health.toFixed(1)} % – Cap ${RULES.healthcareCap} % überschritten`]);if(cash<RULES.cashMin)alerts.push(['warn',`Cash ${cash.toFixed(1)} % – Minimum ${RULES.cashMin} %`]);state.positions.filter(p=>positionValue(p)>0&&positionValue(p)<RULES.minPosition).forEach(p=>alerts.push(['warn',`${p.symbol||p.name}: unter ${money(RULES.minPosition)} – T90/Review`]));state.halal.filter(h=>h.status==='H0').forEach(h=>alerts.push(['bad',`${h.symbol}: H0 – Exit/Veto`]));state.halal.filter(h=>h.status==='H2').forEach(h=>alerts.push(['warn',`${h.symbol}: H2 – Freeze/Review`]));if(state.watchlist.length>RULES.watchlistMax)alerts.push(['bad',`Watchlist ${state.watchlist.length}/${RULES.watchlistMax} – Limit überschritten`]);return {sukuk,health,cash,alerts}}
function dashboard(){const r=risk();return heading('HPOS','Dashboard','Lokales Portfolio-Cockpit')+`<div class="grid metrics">${metric('Portfoliowert',money(totalValue()))}${metric('Cash',money(state.cash),`${r.cash.toFixed(1)} %`)}${metric('Sukuk',`${r.sukuk.toFixed(1)} %`,`Ziel ${RULES.sukukTarget} %`)}${metric('Radar',String(r.alerts.length),'aktive Hinweise')}</div><h2 class="section-title">HPOS Radar</h2><div class="grid">${r.alerts.length?r.alerts.slice(0,6).map(a=>`<div class="alert ${a[0]}">${a[1]}</div>`).join(''):'<div class="alert ok">Keine Regelverletzung aus den aktuell erfassten lokalen Daten.</div>'}</div><h2 class="section-title">Schnellzugriff</h2><div class="two-col"><button class="btn primary" onclick="openTx()">＋ Kauf / Verkauf erfassen</button><button class="btn" onclick="go('settings')">Backup & Import</button></div>`}
function portfolio(){return heading('Depot','Portfolio',`${state.positions.length} Positionen`)+`<div class="card table-wrap"><table class="table"><thead><tr><th>Titel</th><th>Stück</th><th>Ø Einstand</th><th>Referenzkurs</th><th>Wert</th><th>Sektor</th></tr></thead><tbody>${state.positions.length?state.positions.map(p=>`<tr><td><strong>${p.symbol||''}</strong><br><span class="muted">${p.name||''}</span></td><td>${Number(p.qty||0).toLocaleString('de-DE')}</td><td>${money(p.avg)}</td><td>${money(p.price||p.avg)}</td><td>${money(positionValue(p))}</td><td>${p.sector||'–'}</td></tr>`).join(''):`<tr><td colspan="6" class="empty">Noch keine Positionen. Erfasse den ersten Kauf über ＋.</td></tr>`}</tbody></table></div>`}
function transactions(){return heading('Journal','Transaktionen','Käufe, Verkäufe, Dividenden und Cash-Bewegungen')+`<button class="btn primary" onclick="openTx()">＋ Neuer Eintrag</button><div class="card table-wrap" style="margin-top:14px"><table class="table"><thead><tr><th>Datum</th><th>Typ</th><th>Titel</th><th>Stück</th><th>Preis/Betrag</th><th></th></tr></thead><tbody>${state.transactions.length?state.transactions.slice().reverse().map(t=>`<tr><td>${t.date}</td><td>${t.type}</td><td>${t.symbol||'–'}</td><td>${t.qty||'–'}</td><td>${t.type==='Dividende'||t.type==='Einzahlung'||t.type==='Auszahlung'?money(t.amount):money(t.price)}</td><td><button class="btn danger" onclick="delTx('${t.id}')">Löschen</button></td></tr>`).join(''):`<tr><td colspan="6" class="empty">Noch keine Transaktionen.</td></tr>`}</tbody></table></div>`}
function analysis(){const r=risk();return heading('Engine','HPOS Analyse','Regelbasiertes Allocation- und Struktur-Review')+`<div class="grid metrics">${metric('Healthcare',`${r.health.toFixed(1)} %`,`Cap ${RULES.healthcareCap} %`)}${metric('Sukuk',`${r.sukuk.toFixed(1)} %`,`Ziel ${RULES.sukukTarget} %`)}${metric('Cash',`${r.cash.toFixed(1)} %`,`Min. ${RULES.cashMin} %`)}${metric('Watchlist',`${state.watchlist.length}/${RULES.watchlistMax}`)}</div><h2 class="section-title">Kapitalallokator</h2><div class="card"><div class="row"><div class="row-main"><strong>Priorität 1</strong><small>Halal-Gate vor Rendite. H0 ist Veto.</small></div><span class="pill ok">hart</span></div><div class="row"><div class="row-main"><strong>Priorität 2</strong><small>Sukuk-Zielquote Richtung ${RULES.sukukTarget} % aufbauen.</small></div></div><div class="row"><div class="row-main"><strong>Priorität 3</strong><small>Positionen unter ${money(RULES.minPosition)} aktiv prüfen: aufstocken oder Exit.</small></div></div></div>`}
function radar(){const r=risk();return heading('Kontrolle','HPOS Radar','Abweichungen, Freeze-Status und Review-Punkte')+`<div class="grid">${r.alerts.length?r.alerts.map(a=>`<div class="alert ${a[0]}">${a[1]}</div>`).join(''):'<div class="alert ok">Radar aktuell grün.</div>'}</div>`}
function news(){return heading('Thesen','News & Thesis','V1: manuell dokumentiert; Live-Feeds folgen über sicheren Adapter')+`<div class="card"><div class="empty">Noch keine News-Einträge. In V2 kann dieser Bereich automatisch mit Quellen befüllt werden.</div></div>`}
function watch(){return heading('Pipeline','Watchlist',`Maximal ${RULES.watchlistMax} kuratierte Titel`)+`<button class="btn primary" onclick="openWatch()">＋ Titel hinzufügen</button><div class="card" style="margin-top:14px">${state.watchlist.length?state.watchlist.map((w,i)=>`<div class="row"><div class="row-main"><strong>${w.symbol}</strong><small>${w.bucket} · ${w.note||''}</small></div><button class="btn danger" onclick="state.watchlist.splice(${i},1);save();render()">Entfernen</button></div>`).join(''):'<div class="empty">Watchlist leer.</div>'}</div>`}
function halal(){return heading('Compliance','Halal Register','H1 erlaubt · H2 Freeze/Review · H0 Exit/Veto')+`<button class="btn primary" onclick="openHalal()">＋ Prüfung erfassen</button><div class="card" style="margin-top:14px">${state.halal.length?state.halal.map((h,i)=>`<div class="row"><div class="row-main"><strong>${h.symbol} · ${h.status}</strong><small>${h.source||'Quelle offen'} · ${h.date||''}</small></div><button class="btn danger" onclick="state.halal.splice(${i},1);save();render()">Entfernen</button></div>`).join(''):'<div class="empty">Noch keine Prüfungen dokumentiert.</div>'}</div>`}
function income(){const divs=state.transactions.filter(t=>t.type==='Dividende');const year=new Date().getFullYear();const y=divs.filter(t=>String(t.date).startsWith(String(year))).reduce((s,t)=>s+Number(t.amount||0),0);const avg=y/12;const pct=Math.min(100,avg/RULES.dividendGoalMonthly*100);return heading('Cashflow','Income',`Ziel ${money(RULES.dividendGoalMonthly)} netto/Monat bis Oktober 2029`)+`<div class="grid metrics">${metric(`Dividenden ${year}`,money(y))}${metric('Monatsschnitt',money(avg))}${metric('Zielgrad',`${pct.toFixed(0)} %`)}${metric('Ziel',money(RULES.dividendGoalMonthly)+'/Monat')}</div><div class="card" style="margin-top:14px"><div class="progress"><span style="width:${pct}%"></span></div></div>`}
function rules(){return heading('Governance','Regeln & Governance','Verbindliche Startregeln dieser lokalen V1')+`<div class="card"><div class="row"><div class="row-main"><strong>Halal Gate</strong><small>H0 = Exit/Veto; H2 = Freeze/Review.</small></div></div><div class="row"><div class="row-main"><strong>Healthcare Cap</strong><small>${RULES.healthcareCap} %</small></div></div><div class="row"><div class="row-main"><strong>Sukuk Ziel</strong><small>${RULES.sukukTarget} %</small></div></div><div class="row"><div class="row-main"><strong>Cash Minimum</strong><small>${RULES.cashMin} %</small></div></div><div class="row"><div class="row-main"><strong>Mindestpositions-Review</strong><small>unter ${money(RULES.minPosition)} → T90/Review.</small></div></div><div class="row"><div class="row-main"><strong>Watchlist</strong><small>maximal ${RULES.watchlistMax} Titel.</small></div></div><div class="row"><div class="row-main"><strong>Dividendenziel</strong><small>${money(RULES.dividendGoalMonthly)} netto/Monat bis Oktober 2029.</small></div></div></div>`}
function settings(){return heading('Lokale Daten','Daten & Einstellungen','Backup, Gerätewechsel und Reset')+`<div class="two-col"><div class="card"><h3>JSON Backup</h3><p class="muted">Exportiert Portfolio, Transaktionen, Watchlist und Register aus diesem Browser.</p><button class="btn primary" onclick="exportData()">Export herunterladen</button></div><div class="card"><h3>JSON Import</h3><p class="muted">Import überschreibt den lokalen Stand auf diesem Gerät.</p><input id="importFile" type="file" accept="application/json" class="btn"><button class="btn" style="margin-top:10px" onclick="importData()">Importieren</button></div></div><div class="card" style="margin-top:14px"><h3>Lokalen Stand löschen</h3><p class="muted">Nur dieses Gerät. Das GitHub-Projekt bleibt unverändert.</p><button class="btn danger" onclick="resetAll()">Lokale Daten zurücksetzen</button></div>`}
const views={dashboard,portfolio,transactions,analysis,radar,news,watchlist:watch,halal,income,rules,settings};
function render(){nav();$('#content').innerHTML=views[page]();$('#content').focus({preventScroll:true})}
function go(p){page=p;render();window.scrollTo({top:0,behavior:'smooth'})}window.go=go;
function txDialog(){return `<div class="dialog-body"><div class="dialog-head"><h2>Neuer Eintrag</h2><button class="close" onclick="$('#txDialog').close()">×</button></div><div class="form-grid"><div class="field"><label>Typ</label><select id="txType"><option>Kauf</option><option>Verkauf</option><option>Dividende</option><option>Einzahlung</option><option>Auszahlung</option></select></div><div class="field"><label>Datum</label><input id="txDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Ticker / Name</label><input id="txSymbol" placeholder="z. B. ISWD"></div><div class="field"><label>Bezeichnung</label><input id="txName" placeholder="optional"></div><div class="two-col"><div class="field"><label>Stück</label><input id="txQty" type="number" min="0" step="any"></div><div class="field"><label>Preis je Stück</label><input id="txPrice" type="number" min="0" step="any"></div></div><div class="field"><label>Betrag bei Dividende/Ein-/Auszahlung</label><input id="txAmount" type="number" min="0" step="any"></div><div class="two-col"><div class="field"><label>Sektor</label><input id="txSector" placeholder="z. B. Healthcare"></div><div class="field"><label>Assetklasse</label><input id="txClass" placeholder="z. B. Sukuk"></div></div></div><div class="actions"><button class="btn" onclick="$('#txDialog').close()">Abbrechen</button><button class="btn primary" onclick="addTx()">Speichern</button></div></div>`}
function openTx(){$('#txDialog').innerHTML=txDialog();$('#txDialog').showModal()}window.openTx=openTx;
function addTx(){const type=$('#txType').value,date=$('#txDate').value,symbol=$('#txSymbol').value.trim().toUpperCase(),name=$('#txName').value.trim(),qty=Number($('#txQty').value||0),price=Number($('#txPrice').value||0),amount=Number($('#txAmount').value||0),sector=$('#txSector').value.trim(),assetClass=$('#txClass').value.trim();if(['Kauf','Verkauf'].includes(type)&&(!symbol||qty<=0||price<0)){toast('Ticker, Stück und Preis prüfen');return}if(['Dividende','Einzahlung','Auszahlung'].includes(type)&&amount<=0){toast('Betrag fehlt');return}const t={id:crypto.randomUUID(),type,date,symbol,name,qty,price,amount,sector,assetClass};state.transactions.push(t);applyTx(t);save();$('#txDialog').close();render();toast('Gespeichert')}
function applyTx(t){if(t.type==='Einzahlung'){state.cash+=t.amount;return}if(t.type==='Auszahlung'){state.cash-=t.amount;return}if(t.type==='Dividende'){state.cash+=t.amount;return}let p=state.positions.find(x=>x.symbol===t.symbol);if(!p){p={symbol:t.symbol,name:t.name,qty:0,avg:0,price:t.price,sector:t.sector,assetClass:t.assetClass};state.positions.push(p)}if(t.type==='Kauf'){const oldCost=p.qty*p.avg;const newCost=t.qty*t.price;p.avg=(oldCost+newCost)/(p.qty+t.qty);p.qty+=t.qty;p.price=t.price;p.name=p.name||t.name;p.sector=p.sector||t.sector;p.assetClass=p.assetClass||t.assetClass;state.cash-=newCost}else if(t.type==='Verkauf'){p.qty=Math.max(0,p.qty-t.qty);p.price=t.price;state.cash+=t.qty*t.price;if(p.qty===0)state.positions=state.positions.filter(x=>x!==p)}}
function rebuild(){const tx=state.transactions.slice();const keep={watchlist:state.watchlist,halal:state.halal,news:state.news,rules:state.rules};state=Object.assign(structuredClone(DEFAULT),keep);state.transactions=tx;tx.forEach(applyTx);save()}
function delTx(id){if(!confirm('Transaktion löschen und Bestand neu berechnen?'))return;state.transactions=state.transactions.filter(t=>t.id!==id);rebuild();render();toast('Gelöscht') }window.delTx=delTx;
function openWatch(){$('#watchDialog').innerHTML=`<div class="dialog-body"><div class="dialog-head"><h2>Watchlist</h2><button class="close" onclick="$('#watchDialog').close()">×</button></div><div class="form-grid"><div class="field"><label>Ticker</label><input id="wSymbol"></div><div class="field"><label>Lager</label><select id="wBucket"><option>A · Engpass</option><option>B · Compounder</option><option>C · Spezialfall</option></select></div><div class="field"><label>Notiz</label><textarea id="wNote"></textarea></div></div><div class="actions"><button class="btn primary" onclick="addWatch()">Hinzufügen</button></div></div>`;$('#watchDialog').showModal()}window.openWatch=openWatch;
function addWatch(){if(state.watchlist.length>=RULES.watchlistMax){toast('Watchlist-Limit erreicht');return}const symbol=$('#wSymbol').value.trim().toUpperCase();if(!symbol)return;state.watchlist.push({symbol,bucket:$('#wBucket').value,note:$('#wNote').value.trim()});save();$('#watchDialog').close();render()}window.addWatch=addWatch;
function openHalal(){$('#halalDialog').innerHTML=`<div class="dialog-body"><div class="dialog-head"><h2>Halal Prüfung</h2><button class="close" onclick="$('#halalDialog').close()">×</button></div><div class="form-grid"><div class="field"><label>Ticker</label><input id="hSymbol"></div><div class="field"><label>Status</label><select id="hStatus"><option>H1</option><option>H2</option><option>H0</option></select></div><div class="field"><label>Quelle</label><input id="hSource" placeholder="Musaffa / Zoya / ..."></div><div class="field"><label>Prüfdatum</label><input id="hDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div></div><div class="actions"><button class="btn primary" onclick="addHalal()">Speichern</button></div></div>`;$('#halalDialog').showModal()}window.openHalal=openHalal;
function addHalal(){const symbol=$('#hSymbol').value.trim().toUpperCase();if(!symbol)return;state.halal.push({symbol,status:$('#hStatus').value,source:$('#hSource').value.trim(),date:$('#hDate').value});save();$('#halalDialog').close();render()}window.addHalal=addHalal;
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`HPOS-Backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}window.exportData=exportData;
function importData(){const f=$('#importFile')?.files?.[0];if(!f){toast('Datei auswählen');return}const r=new FileReader();r.onload=()=>{try{state=Object.assign(structuredClone(DEFAULT),JSON.parse(r.result));save();render();toast('Importiert')}catch{toast('Ungültige JSON-Datei')}};r.readAsText(f)}window.importData=importData;
function resetAll(){if(!confirm('Alle lokalen HPOS-Daten auf diesem Gerät löschen?'))return;state=structuredClone(DEFAULT);save();render();toast('Zurückgesetzt')}window.resetAll=resetAll;
$('#menuBtn').onclick=openMenu;$('#scrim').onclick=closeMenu;$('#quickAddBtn').onclick=openTx;
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
render();
