(()=>{'use strict';
const $=s=>document.querySelector(s);
const PASS=new Set(['PASS','HALAL','COMPLIANT','SHARIA_COMPLIANT']);
const FAIL=new Set(['FAIL','HARAM','NON_COMPLIANT','NOT_HALAL']);
const FILTERS=[['ALL','Alle'],['OPEN_REVIEW','Offen'],['FREEZE','Freeze'],['REVIEW','Review'],['EXIT_REVIEW','Exit-Review']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const eur=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(num(v));
let catalog=null,theses=null,activeFilter='ALL',expanded=false,renderToken=0;
async function loadReference(){if(catalog&&theses)return;const [c,t]=await Promise.all([fetch('../data/asset_catalog.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null),fetch('../data/thesis_registry.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)]);catalog=c?.assets||{};theses=t?.assets||{};}
function state(){return window.HPOS_STATE_SNAPSHOT?.()||{holdings:[],cash:0};}
function halal(h){return String(h?.halal??h?.halalStatus??'UNKNOWN').toUpperCase();}
function refFor(h){const isin=String(h?.isin||'').toUpperCase(),name=String(h?.name||'').toLowerCase();return Object.entries(catalog||{}).find(([,a])=>String(a?.isin||'').toUpperCase()===isin||(a?.aliases||[]).some(x=>String(x).toLowerCase()===name))?.[0]||null;}
function classify(h,total){
 const hs=halal(h),value=num(h?.value??h?.currentValue??h?.marketValue),weight=total>0?value/total*100:0,key=refFor(h),thesis=key?theses?.[key]:null;
 const common={holding:h,value,weight,thesis,key};
 if(FAIL.has(hs))return{...common,status:'EXIT_REVIEW',label:'EXIT-REVIEW',tone:'neg',gate:'Gate 1 nicht bestanden',winning:'Das Halal-Veto hat höchste Priorität.',blocking:'Gate 1 ist mit belastbarer Evidenz nicht bestanden.',next:'Position und belastbare Ausstiegsfolgen prüfen. Keine automatische Order.'};
 if(!PASS.has(hs))return{...common,status:'OPEN_REVIEW',label:'PRÜFUNG OFFEN',tone:'warn',gate:'Gate 1 offen',winning:'Halal steht vor Rendite, Kurs und Dividende.',blocking:'Für Gate 1 fehlt vollständige, belastbare AAOIFI-Evidenz.',next:'AAOIFI-Pflichtdaten und offizielle Quellen vervollständigen.'};
 if(value<300)return{...common,status:'REVIEW',label:'REVIEW',tone:'warn',gate:'Gate 1 bestanden · Gate 2 offen',winning:'Halal ist belegt; der Unter-300-€-Review greift.',blocking:'Portfolio Fit ist ohne freigegebene Toleranz- und Konzentrationsgrenzen offen.',next:'Rolle, Zielgewicht und Fortführungsgrund der kleinen Position belegen.'};
 return{...common,status:'FREEZE',label:'FREEZE',tone:'',gate:'Gate 1 bestanden · Gate 2 offen',winning:'Halal ist belegt; der Bestand bleibt beobachtbar.',blocking:'Portfolio Fit ist ohne freigegebene Toleranz- und Konzentrationsgrenzen offen.',next:'Gate 2 vervollständigen; bis dahin keine Aufstockungsfreigabe.'};
}
function summary(items){const open=items.filter(x=>x.status==='OPEN_REVIEW').length,review=items.filter(x=>x.status==='REVIEW').length,fail=items.filter(x=>x.status==='EXIT_REVIEW').length,risk=fail?'ROT':open?'GELB':'GRÜN',riskClass=fail?'neg':open?'warn':'pos';return `<div class="decisionSignal"><small>Regime</small><strong>Evidenzaufbau</strong></div><div class="decisionSignal"><small>Risikoampel</small><strong class="${riskClass}">${risk}</strong></div><div class="decisionSignal"><small>Spannungen</small><strong>${open} Halal offen · ${review} unter 300 €</strong></div><div class="decisionSignal"><small>Priorität</small><strong>${fail?'Exit-Review vor neuer Analyse':open?'Halal-Evidenz schließen':'Portfolio Fit vervollständigen'}</strong></div>`;}
function card(x){const h=x.holding,name=h?.name||h?.ticker||h?.isin||'Unbekannt',thesis=x.thesis?.thesis?.length?'Thesis vorbereitet, noch nicht Gate-geprüft':'Keine belegte Thesis im Register',key=encodeURIComponent(String(h?.isin||h?.ticker||name));return `<article class="decisionItem"><div class="decisionItemHead"><span><strong>${esc(name)}</strong><small>${esc(x.gate)}</small></span><b class="${x.tone}">${esc(x.label)}</b></div><div class="decisionItemMeta"><span>${eur(x.value)}</span><span>${x.weight.toFixed(1).replace('.',',')} % Depot</span></div><div class="decisionNext"><small>Kleinster nächster Schritt</small><strong>${esc(x.next)}</strong></div><details class="decisionDetails"><summary>Regeln und Evidenz</summary><div class="decisionRuleGrid"><span><small>Gewinnende Regel</small>${esc(x.winning)}</span><span><small>Blockierende Regel</small>${esc(x.blocking)}</span><span><small>Thesis-Stand</small>${esc(thesis)}</span></div></details><button class="decisionOpen" type="button" data-board-asset="${esc(key)}">Investment-Akte öffnen</button></article>`;}
function bind(items){document.querySelectorAll('[data-board-filter]').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.boardFilter||'ALL';expanded=false;renderItems(items)});document.querySelectorAll('[data-board-asset]').forEach(b=>b.onclick=()=>{const id=decodeURIComponent(b.dataset.boardAsset||'');const match=items.find(x=>String(x.holding?.isin||x.holding?.ticker||x.holding?.name)===id)?.holding;if(match)window.HPOS_OPEN_ASSET?.(match)});const more=$('#decisionBoardMore');if(more)more.onclick=()=>{expanded=!expanded;renderItems(items)};}
function renderItems(items){const counts=Object.fromEntries(FILTERS.map(([k])=>[k,k==='ALL'?items.length:items.filter(x=>x.status===k).length]));if(activeFilter!=='ALL'&&!counts[activeFilter])activeFilter='ALL';const filters=$('#decisionBoardFilters'),board=$('#decisionBoard');if(filters)filters.innerHTML=FILTERS.filter(([k])=>k==='ALL'||counts[k]).map(([k,label])=>`<button class="chip${activeFilter===k?' on':''}" data-board-filter="${k}">${label} ${counts[k]}</button>`).join('');const filtered=activeFilter==='ALL'?items:items.filter(x=>x.status===activeFilter),visible=expanded?filtered:filtered.slice(0,5),remaining=Math.max(0,filtered.length-visible.length);if(board)board.innerHTML=filtered.length?`<div class="decisionQueueHead"><strong>Nächste Entscheidungen</strong><span>${visible.length} von ${filtered.length}</span></div>${visible.map(card).join('')}${filtered.length>5?`<button id="decisionBoardMore" class="secondary full" type="button">${expanded?'Auf Top 5 reduzieren':`${remaining} weitere Werte anzeigen`}</button>`:''}`:'<div class="empty">Keine Entscheidungsvorlage in diesem Filter.</div>';bind(items);}
async function render(){if(!$('#analyse')?.classList.contains('on'))return;const my=++renderToken;await loadReference();if(my!==renderToken)return;const s=state(),holdings=Array.isArray(s.holdings)?s.holdings:[],total=holdings.reduce((n,h)=>n+num(h?.value??h?.currentValue??h?.marketValue),0)+num(s.cash),items=holdings.map(h=>classify(h,total)).sort((a,b)=>({EXIT_REVIEW:0,OPEN_REVIEW:1,REVIEW:2,FREEZE:3}[a.status]-{EXIT_REVIEW:0,OPEN_REVIEW:1,REVIEW:2,FREEZE:3}[b.status])||b.value-a.value);const count=$('#decisionBoardCount'),sum=$('#decisionBoardSummary');if(count)count.textContent=`${items.length} Werte`;if(sum)sum.innerHTML=summary(items);renderItems(items);}
function schedule(ms=80){setTimeout(render,ms)}
document.addEventListener('click',e=>{if(e.target.closest('[data-view="analyse"], [data-go="analyse"], #refresh'))schedule()},true);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule()});
document.addEventListener('hpos:halal-prescreen',()=>schedule(0));
document.addEventListener('hpos:halal-canonical',()=>schedule(0));
setTimeout(()=>schedule(0),900);
})();
