(()=>{'use strict';
const $=s=>document.querySelector(s),VALID=/^[A-Z]{2}[A-Z0-9]{9}\d$/;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let index=null,active=null,token=0;
async function getIndex(){if(index)return index;try{const r=await fetch('../data/investment_cases/index.json',{cache:'no-store'});index=r.ok?await r.json():null}catch{index=null}return index}
function detail(label){const row=[...document.querySelectorAll('#assetDetails .drow')].find(x=>x.firstElementChild?.textContent?.trim()===label);return row?.lastElementChild?.textContent?.trim()||''}
function isin(){const v=detail('ISIN').toUpperCase();return VALID.test(v)?v:''}
function tone(state){return ['PASS','SUPPORTED','STRENGTHENING','CURRENT'].includes(state)?'pos':['FAIL','BROKEN'].includes(state)?'neg':'warn'}
function gateLabel(g){return g?.label||g?.state||'Keine Evidenz'}
function setGate(rowIndex,g){const row=[...document.querySelectorAll('#assetGateRows .drow')][rowIndex],v=row?.lastElementChild;if(!v||!g)return;v.textContent=gateLabel(g);v.className=tone(g.state)}
function metricGrid(items=[]){return `<div class="caseMetricGrid">${items.map(x=>`<div><small>${esc(x.label)}</small><strong>${esc(x.value)}</strong>${x.change?`<span class="${x.tone==='positive'?'pos':''}">${esc(x.change)}</span>`:''}</div>`).join('')}</div>`}
function list(items=[]){return items.length?`<ul class="caseList">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}
function sources(items=[]){return `<div class="caseSources">${items.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)} ↗</a>`).join('')}</div>`}
function mount(){let s=$('#investmentCaseSection');if(s)return s;const anchor=$('#portfolioFitSection')||$('#halalEvidenceSection');if(!anchor)return null;s=document.createElement('div');s.id='investmentCaseSection';s.className='section';anchor.insertAdjacentElement('afterend',s);return s}
function visual(c){const gates=[c.gate1,c.gate2,c.gate3,c.gate4,c.gate5,c.gate6,c.gate7,c.gate8];return `<div class="caseVisual" aria-label="Cardinal Prüfpfad">${gates.map((g,i)=>`<span class="${tone(g.state)}"><b>${i+1}</b><small>${esc(i===0?'Halal':i===1?'Fit':i===2?'These':i===3?'Fund.':i===4?'Wert':i===5?'Timing':i===6?'News':'Broker')}</small></span>`).join('')}</div>`}
function renderCase(c){const s=mount();if(!s)return;s.innerHTML=`<div class="sectionHead"><h2>Vollständige Investment-Prüfung</h2><span class="caseAsOf">Stand ${esc(new Date(c.asOf+'T12:00:00Z').toLocaleDateString('de-DE'))}</span></div><div class="caseDecision ${tone(c.decision.state)}"><small>HPOS Ergebnis</small><strong>${esc(c.decision.label)}</strong><p>${esc(c.decision.summary)}</p></div>${visual(c)}<details class="caseBlock" open><summary>Gate 3 · Investmentthese <b class="${tone(c.gate3.state)}">${esc(c.gate3.label)}</b></summary>${list(c.gate3.thesis)}<h3>These wäre widerlegt, wenn</h3>${list(c.gate3.falsification)}</details><details class="caseBlock"><summary>Gate 4 · Fundamentaldaten <b class="${tone(c.gate4.state)}">${esc(c.gate4.label)}</b></summary>${metricGrid(c.gate4.metrics)}<h3>Hauptrisiken</h3>${list(c.gate4.risks)}</details><details class="caseBlock"><summary>Gate 5 · Bewertung <b class="${tone(c.gate5.state)}">${esc(c.gate5.label)}</b></summary>${metricGrid(c.gate5.metrics)}<p>${esc(c.gate5.basis)}</p></details><details class="caseBlock"><summary>Gate 6 · Timing <b class="${tone(c.gate6.state)}">${esc(c.gate6.label)}</b></summary>${metricGrid(c.gate6.metrics)}<p>${esc(c.gate6.basis)}</p></details><details class="caseBlock"><summary>Gate 7 · News-Evidenz <b class="${tone(c.gate7.state)}">${esc(c.gate7.label)}</b></summary><p>${esc(c.gate7.latestMaterialEvent)}</p><div class="caseNext"><small>Nächster Pflichttermin</small><strong>${esc(new Date(c.gate7.nextReview+'T12:00:00Z').toLocaleDateString('de-DE'))}</strong><span>${esc(c.gate7.nextReviewReason)}</span></div></details><div class="notice"><strong>Kleinster nächster Schritt</strong><br>${esc(c.decision.nextStep)}</div><details class="caseBlock"><summary>Primärquellen <b>${c.sources.length}</b></summary>${sources(c.sources)}</details>`}
async function render(){if(!$('#asset')?.classList.contains('on'))return;const mine=++token,id=isin(),idx=await getIndex();if(mine!==token)return;const file=idx?.casesByIsin?.[id];if(!file){$('#investmentCaseSection')?.remove();active=null;return}try{const r=await fetch('../data/investment_cases/'+encodeURIComponent(file),{cache:'no-store'}),c=r.ok?await r.json():null;if(mine!==token||!c)return;active=c;setGate(1,c.gate2);setGate(2,c.gate3);setGate(3,c.gate4);setGate(4,c.gate5);setGate(5,c.gate6);setGate(6,c.gate7);setGate(7,c.gate8);renderCase(c)}catch{active=null}}
function schedule(){[180,700,1500].forEach(ms=>setTimeout(render,ms))}
document.addEventListener('click',schedule,true);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule()});setTimeout(schedule,950);
window.HPOS_INVESTMENT_CASE=Object.freeze({current:()=>active});
})();
