(()=>{'use strict';
const API=(window.HPOS_RUNTIME?.integration?.baseUrl)||'https://moxyhjfbrmsnphikxqje.supabase.co/functions/v1/hpos-api';
const OPENFIGI='https://api.openfigi.com/v3/mapping';
const WATCH_KEY='hpos_watchlist_v1';
const VALID_KEY='hpos_parqet_validated';
const RESTORE_KEY='hpos_search_restore_v1';
const $=s=>document.querySelector(s);
let catalog=[],previewAsset=null,verifyingPreview=false;
function norm(v){return String(v||'').trim()}
function up(v){return norm(v).toUpperCase()}
function validTicker(v){v=up(v);return /^[A-Z0-9.^=\-]{1,24}$/.test(v)&&!/^\d+$/.test(v)}
function validIsinSyntax(v){v=up(v);return /^[A-Z]{2}[A-Z0-9]{9}\d$/.test(v)}
function validIsin(v){v=up(v);if(!validIsinSyntax(v))return false;let s='';for(const c of v)s+=/[A-Z]/.test(c)?String(c.charCodeAt(0)-55):c;let sum=0,alt=false;for(let i=s.length-1;i>=0;i--){let n=Number(s[i]);if(alt){n*=2;if(n>9)n-=9}sum+=n;alt=!alt}return sum%10===0}
function readWatch(){try{const a=JSON.parse(localStorage.getItem(WATCH_KEY)||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function writeWatch(a){localStorage.setItem(WATCH_KEY,JSON.stringify(a))}
function identityKey(a){const isin=up(a?.isin);if(validIsin(isin))return `I:${isin}`;const ticker=up(a?.ticker||a?.symbol),exchange=up(a?.exchange||a?.exchDisp);return ticker?`T:${ticker}${exchange?'@'+exchange:''}`:''}
function inWatch(a){const k=identityKey(a);return !!k&&readWatch().some(x=>identityKey(x)===k)}
function readDepotIsins(){try{const p=JSON.parse(localStorage.getItem(VALID_KEY)||'null'),a=Array.isArray(p?.holdings)?p.holdings:[];return new Set(a.map(x=>up(x?.isin)).filter(validIsin))}catch{return new Set()}}
function inDepot(a){const isin=up(a?.isin);return validIsin(isin)&&readDepotIsins().has(isin)}
function canonical(a,source='VERIFIED_SEARCH'){return{name:norm(a.name||a.shortname||a.longname||a.symbol||a.ticker||a.isin),isin:up(a.isin),ticker:up(a.ticker||a.symbol),source,verified:validIsin(a.isin),identityStatus:validIsin(a.isin)?'VERIFIED':'DISCOVERY',quoteType:up(a.quoteType),exchange:norm(a.exchange||a.exchDisp),sector:norm(a.sector||a.sectorDisp),industry:norm(a.industry||a.industryDisp),addedAt:a.addedAt||new Date().toISOString()}}
function migrateWatch(){const before=readWatch(),seen=new Set(),after=[];for(const x of before){const c=canonical(x,x.source||'WATCHLIST');if(validIsin(c.isin)&&inDepot({isin:c.isin}))continue;if(!validIsin(c.isin)&&!validTicker(c.ticker))continue;const k=identityKey(c);if(!k||seen.has(k))continue;seen.add(k);after.push(c)}if(JSON.stringify(before)!==JSON.stringify(after))writeWatch(after)}
function promoteWatchIdentity(oldA,newA){const oldK=identityKey(oldA),promoted=canonical(newA,newA.source||'IDENTITY_VERIFIED'),newK=identityKey(promoted),before=readWatch();if(!oldK||!newK)return;let replaced=false,seen=new Set(),after=[];for(const x of before){let c=canonical(x,x.source||'WATCHLIST');if(identityKey(c)===oldK){c={...promoted,addedAt:x.addedAt||promoted.addedAt};replaced=true}const k=identityKey(c);if(!k||seen.has(k))continue;seen.add(k);after.push(c)}if(replaced)writeWatch(after)}
async function loadCatalog(){try{const r=await fetch('../config/market_sources.json',{cache:'no-store'});if(r.ok){const d=await r.json();catalog=(d.assets||[]).filter(x=>x.enabled!==false&&validIsin(x.isin)).map(x=>canonical({name:x.name,isin:x.isin,ticker:x.symbol,exchange:x.exchange},'MARKET_CONFIG'))}}catch{catalog=[]}}
function localSearch(q){q=up(q);if(!q)return[];return catalog.filter(x=>[x.name,x.isin,x.ticker].some(v=>up(v).includes(q))).slice(0,12)}
function allowedType(v){v=up(v);return !v||['EQUITY','ETF','MUTUALFUND'].includes(v)}
function parseYahoo(d){const q=Array.isArray(d?.quotes)?d.quotes:Array.isArray(d?.results)?d.results:Array.isArray(d)?d:[],out=[];for(const x of q){const ticker=up(x.symbol||x.ticker),isin=up(x.isin),name=norm(x.longname||x.shortname||x.name||ticker),quoteType=up(x.quoteType);if(!name||!validTicker(ticker)||!allowedType(quoteType))continue;if(validIsin(isin)){out.push(canonical({...x,name,isin,ticker,quoteType},'YAHOO_ISIN'));continue}const local=catalog.find(c=>up(c.ticker)===ticker);if(local){out.push({...local,source:'MARKET_CONFIG_MATCH'});continue}out.push(canonical({...x,name,ticker,quoteType,isin:''},'YAHOO_DISCOVERY'))}return out}
async function externalSearch(q){if(norm(q).length<2)return[];for(const mode of ['search','yahoo-search']){try{const r=await fetch(`${API}?s=${mode}&q=${encodeURIComponent(q)}`,{cache:'no-store'});if(!r.ok)continue;const a=parseYahoo(await r.json());if(a.length)return a.slice(0,15)}catch{}}return[]}
async function verifyOpenFigiIsin(isin){try{const r=await fetch(OPENFIGI,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify([{idType:'ID_ISIN',idValue:isin}]),cache:'no-store'});if(!r.ok)return[];const d=await r.json();const rows=Array.isArray(d?.[0]?.data)?d[0].data:[];const seen=new Set(),out=[];for(const x of rows){const ticker=up(x.ticker),name=norm(x.name||x.securityDescription||ticker);if(!name||!validTicker(ticker))continue;const k=`${isin}|${ticker}`;if(seen.has(k))continue;seen.add(k);out.push(canonical({name,isin,ticker,exchange:x.exchCode},'OPENFIGI_ISIN'))}return out.slice(0,8)}catch{return[]}}
function merge(...lists){const out=[],seen=new Set();for(const a of lists.flat()){const k=identityKey(a);if(!k||seen.has(k))continue;seen.add(k);out.push(a)}return out}
function addWatch(a){if(inDepot(a)||inWatch(a))return false;const c=canonical(a,a.source||'GLOBAL_DISCOVERY');if(!c.verified&&!validTicker(c.ticker))return false;const w=readWatch();w.push(c);writeWatch(w);return true}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function resultRow(a){const verified=validIsin(a?.isin);const meta=verified?[a.isin,a.ticker,a.exchange].filter(Boolean).join(' · '):[a.ticker,a.exchange].filter(Boolean).join(' · ');const state=verified?'ISIN verifiziert':'Vorschau · Identität noch offen';const id=encodeURIComponent(JSON.stringify(a));let action='';if(inDepot(a))action='<span class="guardDepot">Im Depot</span>';else if(inWatch(a))action='<span class="guardDepot">✓ Watchlist</span>';else action=`<button class="guardAdd" data-security="${id}">+ Watchlist</button>`;return `<div class="guardResult"><button class="guardOpen" data-preview="${id}" aria-label="${esc(a.name)} ansehen"><strong>${esc(a.name)}</strong><small>${esc(meta)} · ${state}</small><span>Ansehen</span></button>${action}</div>`}
function statusBox(text,kind='info'){let box=$('#verifiedResults');if(!box){box=document.createElement('div');box.id='verifiedResults';box.className='verifiedResults';$('#searchResults')?.insertAdjacentElement('afterend',box)}box.innerHTML=`<div class="manualVerifyStatus ${kind==='ok'?'ok':''}">${esc(text)}</div>`;return box}
function showPreview(a){a=canonical(a,a.source||'GLOBAL_DISCOVERY');previewAsset=a;const d=$('#searchDialog');if(d?.open)d.close();const verified=validIsin(a.isin),watched=inWatch(a);$('#assetName').textContent=a.name;$('#assetMeta').textContent=[a.isin,a.ticker,a.exchange,watched?'WATCHLIST':'VORSCHAU'].filter(Boolean).join(' · ');const wt=$('#watchToggle');if(wt){wt.disabled=false;wt.textContent=watched?'★ Watchlist':'☆ Zur Watchlist'}const ob=$('#orderBtn');if(ob){ob.disabled=verified;ob.textContent=verified?'✓ Identität verifiziert':'Identität prüfen'}$('#assetDecision').innerHTML=`<strong>HPOS Vorschau</strong><p>Dieses Wertpapier wird nur angesehen und wurde nicht automatisch zur Watchlist hinzugefügt. Identitätsstatus: <b>${verified?'ISIN verifiziert':'noch offen'}</b>. Halal-, Thesis- und Broker-Entscheidungen bleiben bis zur kanonischen Verifikation gesperrt.</p>`;$('#assetCards').innerHTML='<div class="card"><small>Positionswert</small><strong>—</strong></div><div class="card"><small>Stück</small><strong>—</strong></div><div class="card"><small>Ø Einstand</small><strong>—</strong></div><div class="card"><small>Seit Einstand</small><strong>—</strong></div>';$('#assetDetails').innerHTML=`<div class="drow"><span>Portfolio-Status</span><strong>${watched?'WATCHLIST':'VORSCHAU'}</strong></div><div class="drow"><span>Börsenplatz</span><strong>${esc(a.exchange||'—')}</strong></div><div class="drow"><span>ISIN</span><strong>${esc(a.isin||'—')}</strong></div><div class="drow"><span>Ticker</span><strong>${esc(a.ticker||'—')}</strong></div><div class="drow"><span>Identität</span><strong class="${verified?'pos':'warn'}">${verified?'VERIFIZIERT':'OFFEN'}</strong></div><div class="drow"><span>Halal</span><strong class="warn">UNKNOWN</strong></div>`;$('#assetEvidence').innerHTML=`<div class="drow"><span>Letzter Kurs</span><strong>—</strong></div><div class="drow"><span>Marktdaten-Symbol</span><strong>${esc(a.ticker||'—')}</strong></div><div class="drow"><span>Datenquelle</span><strong>${esc(a.source||'—')}</strong></div><div class="drow"><span>Unrealisiert</span><strong>—</strong></div>`;$('#assetIncome').innerHTML='<div class="empty">Keine positionsbezogenen Ausschüttungen, solange das Wertpapier nur angesehen wird.</div>';document.querySelectorAll('.view').forEach(x=>x.classList.remove('on'));$('#asset')?.classList.add('on');document.querySelectorAll('.nav').forEach(x=>x.classList.remove('on'));window.scrollTo(0,0)}
async function verifyPreviewIdentity(){if(!previewAsset||verifyingPreview)return;if(validIsin(previewAsset.isin)){toastLocal('Identität ist bereits per ISIN verifiziert.');return}verifyingPreview=true;const b=$('#orderBtn');if(b){b.disabled=true;b.textContent='Identität wird geprüft …'}try{const before=previewAsset,ticker=up(before.ticker),name=norm(before.name),exchange=up(before.exchange),local=catalog.filter(x=>(ticker&&up(x.ticker)===ticker)||(name&&up(x.name)===up(name)));const remote=merge(await externalSearch(ticker||name),await externalSearch(name));let candidates=merge(local,remote).filter(x=>validIsin(x.isin)).filter(x=>(ticker&&up(x.ticker)===ticker)||(name&&up(x.name)===up(name)));if(exchange){const sameExchange=candidates.filter(x=>up(x.exchange)===exchange);if(sameExchange.length)candidates=sameExchange}if(candidates.length===1){if(inWatch(before))promoteWatchIdentity(before,candidates[0]);previewAsset=candidates[0];showPreview(candidates[0]);toastLocal('Identität per ISIN verifiziert.');return}if(candidates.length>1)toastLocal('Mehrere ISIN-Kandidaten gefunden. Keine automatische Zuordnung.');else toastLocal('Noch keine eindeutige ISIN verfügbar. Vorschau bleibt unverändert.')}finally{verifyingPreview=false;if(previewAsset&&!validIsin(previewAsset.isin)&&b){b.disabled=false;b.textContent='Identität prüfen'}}}
function toastLocal(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toastLocal.t);toastLocal.t=setTimeout(()=>t.classList.remove('show'),3200)}
function renderExternal(list,label='Globale Treffer'){let box=$('#verifiedResults');if(!box){box=document.createElement('div');box.id='verifiedResults';box.className='verifiedResults';$('#searchResults')?.insertAdjacentElement('afterend',box)}box.innerHTML=list.length?`<div class="guardHeading"><div class="eye guardEye">${esc(label)}</div><span class="guardCount" aria-label="${list.length} Treffer">${list.length}</span></div>${list.map(resultRow).join('')}`:'';box.querySelectorAll('.guardOpen').forEach(b=>b.onclick=()=>showPreview(JSON.parse(decodeURIComponent(b.dataset.preview))));box.querySelectorAll('.guardAdd').forEach(b=>b.onclick=e=>{e.stopPropagation();const a=JSON.parse(decodeURIComponent(b.dataset.security));if(addWatch(a)){b.textContent='✓ Watchlist';try{sessionStorage.setItem(RESTORE_KEY,JSON.stringify({q:$('#securityQuery')?.value||a.isin||a.ticker,at:Date.now()}))}catch{}setTimeout(()=>location.reload(),250)}else if(inDepot(a)){b.textContent='Im Depot'}else if(inWatch(a)){b.textContent='✓ Watchlist'}})}
async function verifyExactIsin(isin){isin=up(isin);if(!validIsin(isin)){statusBox('ISIN ungültig. Format oder Prüfziffer stimmt nicht.');return[]}const local=catalog.find(x=>up(x.isin)===isin);if(local)return[local];statusBox('ISIN wird exakt verifiziert …');const figi=await verifyOpenFigiIsin(isin);if(figi.length)return figi;const ext=await externalSearch(isin);const exact=ext.filter(x=>up(x.isin)===isin);if(exact.length)return exact;statusBox('ISIN formal gültig, aber aktuell nicht eindeutig durch eine externe Quelle bestätigt. Es wurde nichts übernommen.');return[]}
async function search(q){q=norm(q);if(!q){renderExternal([]);return[]}if(q.length===12&&/^[A-Za-z]{2}/.test(q)){const hits=await verifyExactIsin(q);if(hits.length)renderExternal(hits,'Exakt verifizierte ISIN');return hits}const local=localSearch(q),external=await externalSearch(q),all=merge(external,local);renderExternal(all,all.length?'Globale Treffer':'');if(!all.length)statusBox('Kein passender börsennotierter Treffer gefunden. Name, Ticker oder ISIN prüfen.');return all}
function restoreSearch(){let saved=null;try{saved=JSON.parse(sessionStorage.getItem(RESTORE_KEY)||'null');sessionStorage.removeItem(RESTORE_KEY)}catch{}if(!saved||Date.now()-Number(saved.at||0)>10000)return;setTimeout(()=>{const d=$('#searchDialog'),q=$('#securityQuery');if(!d||!q)return;if(!d.open)d.showModal();q.value=String(saved.q||'');if(q.value)search(q.value)},40)}
function wire(){migrateWatch();const q=$('#securityQuery');if(q){let t;q.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(()=>search(q.value),320)});q.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(t);search(q.value)}})}document.addEventListener('click',e=>{if(previewAsset&&e.target.closest('#orderBtn')){e.preventDefault();e.stopImmediatePropagation();verifyPreviewIdentity();return}if(previewAsset&&e.target.closest('#watchToggle')){e.preventDefault();e.stopImmediatePropagation();if(!inWatch(previewAsset)&&addWatch(previewAsset)){try{sessionStorage.setItem(RESTORE_KEY,JSON.stringify({q:previewAsset.ticker||previewAsset.name,at:Date.now()}))}catch{}setTimeout(()=>location.reload(),180)}return}if(e.target.closest('[data-asset],.searchRow,[data-view],#assetBack'))previewAsset=null},true);restoreSearch()}
loadCatalog().finally(()=>{if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire()});
})();
