(()=>{'use strict';
const $=s=>document.querySelector(s);let data=null,loading=null,last='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stateLabel=v=>({STRENGTHENING:'STÄRKEND',WEAKENING:'SCHWÄCHEND',NEUTRAL:'NEUTRAL',INSUFFICIENT:'EVIDENZ OFFEN',BROKEN:'WIDERLEGT'})[v]||String(v||'OFFEN');
const classLabel=v=>({PROOFPOINT_MATCH:'PROOFPOINT',RISK_MATCH:'RISIKO',FALSIFICATION_CANDIDATE:'FALSIFIZIERUNG PRÜFEN'})[v]||String(v||'OFFEN');
const tone=v=>v==='BROKEN'||v==='FALSIFICATION_CANDIDATE'?'neg':v==='STRENGTHENING'||v==='PROOFPOINT_MATCH'?'pos':'warn';
async function load(){if(data)return data;if(!loading)loading=fetch('../data/fundamental/thesis_agent.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null).then(x=>data=x);return loading}
function identity(){const name=$('#assetName')?.textContent?.trim()||'',row=[...document.querySelectorAll('#assetDetails .drow')].find(r=>r.firstElementChild?.textContent?.trim()==='ISIN');return{name,isin:row?.lastElementChild?.textContent?.trim().toUpperCase()||''}}
function findAsset(d,id,name=''){const n=String(name).toLowerCase();return(d?.assets||[]).find(x=>(id&&String(x.isin||'').toUpperCase()===id)||(n&&String(x.name||'').toLowerCase()===n))||null}
function assessment(a){const matches=[...(a.proofpointMatches||[]),...(a.riskMatches||[]),...(a.falsificationMatches||[])];return `<article class="thsEvent"><div><b>${esc(classLabel(a.classification))}</b><span class="${tone(a.classification)}">${esc(a.sourceTier)}</span></div><strong>${esc(a.title)}</strong><small>${esc(a.publishedAt||'Stand offen')} · Treffer: ${esc([...new Set(matches)].join(', ')||'—')}</small>${a.sourceUrl?`<a href="${esc(a.sourceUrl)}" target="_blank" rel="noopener noreferrer">Quelle öffnen ↗</a>`:''}</article>`}
function mount(){let s=$('#thesisAgentSection');if(s)return s;const anchor=$('#verificationExplainSection')||$('#assetDecision')?.closest('.section');if(!anchor)return null;s=document.createElement('div');s.id='thesisAgentSection';s.className='section';anchor.insertAdjacentElement('afterend',s);return s}
async function renderAsset(){if(!$('#asset')?.classList.contains('on'))return;const s=mount(),d=await load();if(!s||!d)return;const i=identity(),sig=i.isin+'|'+i.name;if(sig===last&&s.dataset.ready==='1')return;last=sig;const a=findAsset(d,i.isin,i.name);if(!a){s.innerHTML='<div class="sectionHead"><h2>Thesis & Ereignisse</h2><span class="warn">NICHT REGISTRIERT</span></div><div class="notice">Für diesen Wert ist noch keine versionierte Investmentthese hinterlegt.</div>';s.dataset.ready='1';return}s.innerHTML=`<div class="sectionHead"><h2>Thesis & Ereignisse</h2><span class="${tone(a.currentSignalState)}">THS v${esc(a.thsVersion)}</span></div><div class="thsMeta"><span><small>THS-Signal</small><b class="${tone(a.currentSignalState)}">${esc(stateLabel(a.currentSignalState))}</b></span><span><small>Delta</small><b class="${a.reviewRequired?'warn':'pos'}">${esc(a.proposedDelta==='FALSIFICATION_REVIEW'?'FALSIFIZIERUNG PRÜFEN':a.reviewRequired?'REVIEW NÖTIG':'KEINE ÄNDERUNG')}</b></span><span><small>Evidenz</small><b>${esc(a.evidenceFingerprint)}</b></span><span><small>Automatische Änderung</small><b>NEIN</b></span></div><details class="thsBlock"><summary>Proofpoints und Falsifizierungen</summary><h3>These</h3><ul>${(a.registeredThesis||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Widerlegt, wenn</h3><ul>${(a.registeredFalsification||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details><div class="thsEvents">${(a.assessments||[]).map(assessment).join('')||'<div class="notice">Noch kein zuordenbares Primärereignis.</div>'}</div><div class="notice">News und IR-Evidenz ändern weder THS noch Kaufstatus automatisch. Jede Änderung braucht eine begründete Review-Entscheidung.</div>`;s.dataset.ready='1'}
async function renderModule(){const box=$('#moduleContent'),d=await load();if(!box||!d||$('#moduleTitle')?.textContent?.trim()!=='News & Evidenz')return;const s=d.summary||{},rows=(d.assets||[]).filter(x=>x.reviewRequired).sort((a,b)=>(b.proposedDelta==='FALSIFICATION_REVIEW')-(a.proposedDelta==='FALSIFICATION_REVIEW')||b.assessmentCount-a.assessmentCount);box.innerHTML=`<div class="thsSummary"><span><small>THS-Akten</small><b>${esc(s.assets||0)}</b></span><span><small>Review offen</small><b class="warn">${esc(s.reviewRequired||0)}</b></span><span><small>Falsifizierung</small><b class="${s.falsificationReviews?'neg':'pos'}">${esc(s.falsificationReviews||0)}</b></span><span><small>Duplikate entfernt</small><b>${esc(s.duplicatesSuppressed||0)}</b></span></div><div class="notice">Stand ${esc(d.generatedAt||'offen')}. Nur neue Primärevidenz erzeugt eine neue THS-Version. Eine Version ist keine Kaufentscheidung.</div><div class="thsAssetList">${rows.map(a=>`<article><div><strong>${esc(a.name)}</strong><b class="${a.proposedDelta==='FALSIFICATION_REVIEW'?'neg':'warn'}">THS v${esc(a.thsVersion)}</b></div><small>${esc(stateLabel(a.currentSignalState))} · ${esc(a.assessmentCount)} relevante Ereignisse · ${esc(a.evidenceFingerprint)}</small><span>${esc(a.proposedDelta==='FALSIFICATION_REVIEW'?'Falsifizierung fachlich prüfen':'Proofpoints und Risiken fachlich prüfen')}</span></article>`).join('')||'<div class="notice">Keine fachliche Review offen.</div>'}</div>`}
async function forIdentity(id,name=''){const d=await load();return findAsset(d,String(id||'').toUpperCase(),name)}
document.addEventListener('click',e=>{if(e.target.closest('[data-module="news"]'))setTimeout(renderModule,30);if(e.target.closest('#portfolioList,#searchResults,[data-board-asset]'))setTimeout(()=>{last='';renderAsset()},500)},true);
document.addEventListener('hpos:halal-canonical',()=>{last='';renderAsset()});setTimeout(renderAsset,1000);
window.HPOS_THESIS_AGENT=Object.freeze({forIdentity,refresh:async()=>{data=null;loading=null;last='';await Promise.all([renderModule(),renderAsset()])}});
})();
