/* HPOS Alpha 4.5 – State & Ledger Foundation */
(()=>{'use strict';
const VERSION='1.3.0-alpha.4.5';
const DAY=86400000;
const norm=v=>String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const iso=v=>{try{return new Date(v).toISOString()}catch{return null}};
function localProjection(){try{return window.HPOSLocalProjection433?.()||null}catch{return null}}
function localState(){try{return window.state||state||{}}catch{return {}}}
function assetMap(s){return new Map((s.assets||[]).map(a=>[a.assetId,a]));}
function ledgerType(t){const x=String(t||'').toUpperCase();return({BUY:'BUY',SELL:'SELL',DIVIDEND:'DIVIDEND',INTEREST:'INTEREST',DEPOSIT:'DEPOSIT',WITHDRAWAL:'WITHDRAWAL',FEES_TAXES:'FEE_TAX',FEE_TAX:'FEE_TAX',TRANSFER_IN:'TRANSFER_IN',TRANSFER_OUT:'TRANSFER_OUT',OPENING_POSITION:'OPENING_POSITION'}[x]||null)}
function buildLedger(){const s=localState(),byId=assetMap(s),rows=[];for(const t of (s.transactions||[])){const type=ledgerType(t.type);if(!type)continue;const a=byId.get(t.assetId)||{};rows.push({id:String(t.sourceId||t.id||`${type}:${t.date||t.datetime}:${t.assetId||'CASH'}:${t.qty||t.amount||0}`),type,datetime:iso(t.datetime||t.date||t.createdAt)||String(t.date||''),assetKey:a.assetKey||a.ticker||a.name||null,isin:a.isin||t.isin||null,broker:t.broker||a.broker||null,shares:t.qty==null?null:num(t.qty),price:t.price==null?null:num(t.price),amountGross:t.grossAmount==null?(t.amount==null?null:num(t.amount)):num(t.grossAmount),amountNet:t.amountNet==null?(t.amount==null?null:num(t.amount)):num(t.amountNet),tax:t.tax==null?null:num(t.tax),fee:t.fee==null?null:num(t.fee),currency:t.currency||'EUR',source:String(t.source||s.appMeta?.parqetImport?'PARQET':'LOCAL_IMPORT').toUpperCase().includes('PARQET')?'PARQET':'USER_CONFIRMED',sourceId:t.sourceId||null,confidence:'HIGH',notes:t.notes||null});}
rows.sort((a,b)=>String(a.datetime).localeCompare(String(b.datetime))||a.id.localeCompare(b.id));return{schemaVersion:1,asOf:new Date().toISOString(),source:s.appMeta?.parqetImport?'PARQET':'LOCAL_IMPORT',entries:rows};}
function quoteMeta(asset){const q=asset?.priceQuote||{},at=q.datetime||q.asOf||q.updatedAt||null,age=at?Date.now()-Date.parse(at):Infinity;return{price:q.price==null?null:num(q.price),asOf:at,source:q.provider||q.exchange||q.source||null,state:age<=36*60*60*1000?'CURRENT':Number.isFinite(age)?'STALE':'UNKNOWN'};}
function overrides(s){return Array.isArray(s.hposOverrides)?s.hposOverrides:(Array.isArray(s.overrides)?s.overrides:[])}
function applyOverride(position,ovs){const keys=[norm(position.assetKey),norm(position.isin)].filter(Boolean);const matches=ovs.filter(o=>keys.includes(norm(o.assetKey||o.isin))).sort((a,b)=>Date.parse(b.confirmedAt||0)-Date.parse(a.confirmedAt||0));for(const o of matches){if(o.field==='currentPrice'||o.field==='currentValue'){position[o.field]=num(o.value);position.quoteState='OVERRIDDEN';position.quoteSource=o.source||'USER_CONFIRMED';position.quoteAsOf=o.confirmedAt||position.quoteAsOf;if(o.field==='currentPrice'&&position.shares!=null)position.currentValue=position.shares*position.currentPrice;if(o.field==='currentValue'&&position.shares>0)position.currentPrice=position.currentValue/position.shares;}}return position}
function orderCommitment(s){return (s.openOrders||[]).filter(o=>!['FILLED','CANCELLED','REJECTED','EXPIRED'].includes(String(o.status||'OPEN').toUpperCase())).reduce((sum,o)=>{if(String(o.side||o.type||'BUY').toUpperCase().includes('SELL'))return sum;const explicit=num(o.reservedCashEur||o.amountEur);if(explicit>0)return sum+explicit;return sum+num(o.qty||o.shares)*num(o.limitPrice||o.price);},0)}
function buildCurrentState(){const s=localState(),p=localProjection(),byIsin=new Map((s.assets||[]).filter(a=>a.isin).map(a=>[norm(a.isin),a])),ovs=overrides(s);const positions=(p?.holdings||[]).map(h=>{const a=byIsin.get(norm(h.isin))||{},qm=quoteMeta(a);return applyOverride({assetKey:a.assetKey||a.ticker||h.name||null,isin:h.isin||null,broker:h.broker||a.broker||null,shares:num(h.shares),currentPrice:num(h.currentPrice),currentValue:num(h.currentValue),avgEntryPrice:num(h.purchasePrice||h.avgEntryPrice),quoteAsOf:qm.asOf,quoteSource:qm.source,quoteState:qm.state},ovs)});const cash=(p?.cash||[]).reduce((x,c)=>x+num(c.value),0)||num(p?.kpis?.cash||0);const committed=orderCommitment(s),ledger=buildLedger();const issues=[];for(const x of positions){if(x.quoteState==='STALE'||x.quoteState==='UNKNOWN')issues.push({code:'QUOTE_'+x.quoteState,assetKey:x.assetKey,isin:x.isin,message:`Kursquelle ${x.quoteState.toLowerCase()}; vor Ausführung verifizieren.`});if(!x.broker||x.broker==='LOCAL')issues.push({code:'BROKER_PROVENANCE_MISSING',assetKey:x.assetKey,isin:x.isin,message:'Broker-Zuordnung ist lokal/aggregiert und nicht als Broker-Wahrheit bestätigt.'});}
const portfolioValue=positions.reduce((z,x)=>z+x.currentValue,0)+cash;const importMeta=s.appMeta?.parqetImport||{};return{asOf:new Date().toISOString(),provenance:{portfolioSource:importMeta.generatedAt?'PARQET':'LOCAL_IMPORT',lastPortfolioSyncAt:importMeta.generatedAt||s.dataStatus?.portfolio?.asOf||null,parqetPortfolioId:null,brokerCoverage:[...new Set(positions.map(x=>String(x.broker||'').toUpperCase()).filter(Boolean))],notes:'Parqet normalisiert Portfoliohistorie; brokerkritische Felder werden lokal reconciled.'},portfolio:{portfolioValueEur:portfolioValue,cashEur:cash,cashCommittedEur:committed,availableCashEur:Math.max(0,cash-committed),ttwrorPct:null,xirrPct:null,netDividendsEur:ledger.entries.filter(x=>x.type==='DIVIDEND').reduce((z,x)=>z+num(x.amountNet),0)},positions,overrides:ovs,openOrders:s.openOrders||[],savingPlans:s.savingPlans||[],ledger:{schemaVersion:1,entryCount:ledger.entries.length,lastEntryAt:ledger.entries.at(-1)?.datetime||null,source:ledger.source},reconciliation:{status:issues.some(x=>x.code==='QUOTE_STALE')?'STALE':issues.length?'WARN':'OK',issues},lastController:s.lastController||null};}
function cashGate(current,constitution){const c=constitution?.portfolioRules?.cash||{targetPct:3,relativeHardMinimumPct:2,absoluteHardFloorEur:150},v=num(current.portfolio.portfolioValueEur),cash=num(current.portfolio.availableCashEur),pct=v>0?cash/v*100:0;return{cashEur:cash,cashPct:pct,targetPct:num(c.targetPct),relativeHardMinimumPct:num(c.relativeHardMinimumPct),absoluteHardFloorEur:num(c.absoluteHardFloorEur),status:cash<num(c.absoluteHardFloorEur)||pct<num(c.relativeHardMinimumPct)?'RED':pct<num(c.targetPct)?'YELLOW':'GREEN'};}
async function snapshot(){const current=buildCurrentState(),ledger=buildLedger();let constitution=null;try{constitution=(await window.HPOSArchitecture442?.load?.())?.constitution||null}catch{}return{current,ledger,cash:cashGate(current,constitution)}}
function saveLocal(){const x=buildCurrentState();localStorage.setItem('hpos_current_state_v1',JSON.stringify(x));return x}
function exportPrivate(){return JSON.stringify({current:buildCurrentState(),ledger:buildLedger()},null,2)}
window.HPOSStateLedger45={version:VERSION,buildCurrentState,buildLedger,cashGate,snapshot,saveLocal,exportPrivate};
})();