/* HPOS Alpha 4.4.2 – Architecture Runtime */
(()=>{'use strict';
const VERSION='1.3.0-alpha.4.4.2';
const BASE='../';
let architecturePromise=null;
const norm=v=>String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const esc=v=>typeof window.esc==='function'?window.esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function getJson(path){const r=await fetch(`${BASE}${path}?v=442`,{cache:'no-cache'});if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return r.json()}
function localProjection(){try{return window.HPOSLocalProjection433?.()||null}catch{return null}}
function registryKey(asset,registry){if(!asset||!registry?.assets)return null;const candidates=[asset.assetKey,asset.name,asset.ticker,asset.symbol].map(norm).filter(Boolean);for(const key of Object.keys(registry.assets)){const nk=norm(key);if(candidates.some(c=>c===nk||c.includes(nk)||nk.includes(c)))return key;}const aliases={NOVONORDISK:'NOVO_NORDISK',IVUTRAFFIC:'IVU_TRAFFIC',JUDGESSCIENTIFIC:'JUDGES_SCIENTIFIC',BUREAUVERITAS:'BUREAU_VERITAS',MERCKCO:'MERCK'};for(const c of candidates)for(const[a,k]of Object.entries(aliases))if(c.includes(a)||a.includes(c))return registry.assets[k]?k:null;return null}
function holdingWeight(asset){const p=localProjection(),h=p?.holdings?.find(x=>norm(x.isin)===norm(asset?.isin));const total=Number(p?.kpis?.importedPortfolioTotal||p?.portfolioValue||0);return h&&total>0?{holding:h,weight:Number(h.currentValue||0)/total*100,total}:null}
function matchRegistryHolding(h,registry){const name=norm(h?.name||h?.securityName||h?.ticker||'');if(!name)return null;for(const key of Object.keys(registry?.assets||{})){const k=norm(key);if(name.includes(k)||k.includes(name))return key;}const map={NOVONORDISK:'NOVO_NORDISK',ABBOTT:'ABBOTT',MEDTRONIC:'MEDTRONIC',NOVARTIS:'NOVARTIS',MERCK:'MERCK',GSK:'GSK'};for(const[a,k]of Object.entries(map))if(name.includes(a))return k;return null}
function healthcareWeight(registry){const p=localProjection(),total=Number(p?.kpis?.importedPortfolioTotal||p?.portfolioValue||0);if(!total||!p?.holdings)return null;let value=0,matched=0;for(const h of p.holdings){const k=matchRegistryHolding(h,registry),role=k?String(registry.assets[k]?.role||''):'';if(role.includes('HEALTHCARE')){value+=Number(h.currentValue||0);matched++;}}return matched?value/total*100:null}
async function architecture(){if(architecturePromise)return architecturePromise;architecturePromise=(async()=>{try{const[constitution,registry]=await Promise.all([getJson('config/hpos_constitution.json'),getJson('data/thesis_registry.json')]);return{ok:true,constitution,registry,error:null}}catch(e){return{ok:false,constitution:null,registry:null,error:String(e?.message||e)}}})();return architecturePromise}
function applyHardGates(bundle,asset,a){const d=bundle.decision||{},c=a.constitution,r=a.registry,key=registryKey(asset,r),thesis=key?r.assets[key]:null,hw=holdingWeight(asset),hc=healthcareWeight(r);d.reasons=Array.isArray(d.reasons)?d.reasons:[];d.architecture={source:'HPOS_CONSTITUTION',constitutionVersion:c?.version||null,registryAsOf:r?.asOf||null,thesisKey:key,thesis,healthcareWeightPct:hc,positionWeightPct:hw?.weight??null,degraded:!a.ok};
if(!a.ok){if(d.action==='KAUFEN'||d.action==='ADD'||d.action==='AUFSTOCKEN')d.action='PRÜFEN';d.tone='warn';d.reasons.unshift(['⚠','Architektur nicht vollständig geladen','Keine Kauf-/Aufstockungsfreigabe im Degraded Mode.']);return d}
const hal=d.halal?.status||'UNKNOWN';if(hal==='H0'){d.action='NICHT KAUFEN';d.tone='bad'}else if(hal==='H2'){d.action='EINFRIEREN';d.tone='warn'}else if(hal==='UNKNOWN'){d.action='PRÜFEN';d.tone='warn'}
const singleCap=Number(c.portfolioRules?.singleStock?.hardCapPct||25);if(hw?.weight>singleCap){d.action=hal==='H0'?'NICHT KAUFEN':'NICHT AUFSTOCKEN';d.tone='bad';d.reasons.unshift(['⛔',`Einzelpositions-Cap ${singleCap}% überschritten`,`Aktuell ca. ${hw.weight.toFixed(1)} %.`])}
const hcCap=Number(c.portfolioRules?.healthcare?.hardCapPct||30);if(thesis?.role?.includes('HEALTHCARE')&&hc!=null&&hc>hcCap){if(!['NICHT KAUFEN','EINFRIEREN'].includes(d.action))d.action='NICHT AUFSTOCKEN';d.tone='bad';d.reasons.unshift(['⛔',`Healthcare-Cap ${hcCap}% überschritten`,`Aktuell ca. ${hc.toFixed(1)} %. Healthcare-Kauf bleibt blockiert.`])}
if(thesis)d.reasons.push(['▣',`Registry: ${thesis.role||'ROLE'}`,`These versioniert · Stand ${r.asOf||'unbekannt'}.`]);d.reasons=d.reasons.slice(0,5);return d}
const original=window.HPOSDecision44;if(original?.bundle){const oldBundle=original.bundle.bind(original);original.bundle=async asset=>{const[b,a]=await Promise.all([oldBundle(asset),architecture()]);b.decision=applyHardGates(b,asset,a);b.architecture=a;return b};}
function registryCard(asset,b){const a=b?.architecture,d=b?.decision?.architecture;if(!a?.ok||!d?.thesis)return`<div class="card"><div class="a441-head"><div><h3>Thesis Registry</h3><p>Architekturstatus</p></div><span class="badge warn">DEGRADED</span></div><p>Constitution oder Thesis Registry nicht verfügbar. Keine neue Kauf-/Aufstockungsfreigabe.</p></div>`;const t=d.thesis;const rows=[['These',t.thesis||[]],['Risiken',t.risks||[]],['Falsifizierung',t.falsification||[]]];return`<div class="card a442-registry"><div class="a441-head"><div><h3>Investmentthese</h3><p>Versionierte Thesis Registry · ${esc(a.registry.asOf||'')}</p></div><span class="badge info">${esc(t.role||'ROLE')}</span></div><div class="a441-thesis">${rows.map(([k,v])=>`<div class="a441-thesisrow"><small>${esc(k)}</small>${v.length?v.map(x=>`<p>${esc(x)}</p>`).join(''):'<p>Keine Definition hinterlegt.</p>'}</div>`).join('')}</div><div class="rule-source">Source of Truth: Thesis Registry. Kurs und News verändern diese Definition nicht automatisch; sie liefern Evidenz für Review/Falsifizierung.</div></div>`}
function methodCard(b){const d=b?.decision?.architecture,a=b?.architecture;if(!d)return'';const c=a?.constitution;return`<div class="card a442-source"><div class="a441-head"><div><h3>Systemquellen</h3><p>Welche Ebene diese Entscheidung steuert</p></div><span class="badge ${a?.ok?'good':'warn'}">${a?.ok?'ARCHITECTURE OK':'DEGRADED'}</span></div><div class="a441-chips"><span class="a441-chip info">Constitution ${esc(c?.version||'?')}</span><span class="a441-chip">Thesis ${esc(d.thesisKey||'nicht gemappt')}</span><span class="a441-chip">Registry ${esc(a?.registry?.asOf||'?')}</span>${d.positionWeightPct!=null?`<span class="a441-chip">Position ${d.positionWeightPct.toFixed(1)} %</span>`:''}${d.healthcareWeightPct!=null?`<span class="a441-chip">Healthcare ${d.healthcareWeightPct.toFixed(1)} %</span>`:''}</div></div>`}
const oldRender=typeof window.renderAssetTab==='function'?window.renderAssetTab:null;if(oldRender){window.renderAssetTab=function(v,tab){const out=oldRender(v,tab);if(v?.asset&&['overview','analysis','news'].includes(tab)){setTimeout(async()=>{const host=document.getElementById('a441host');if(!host)return;try{const b=await window.HPOSDecision44.bundle(v.asset);const cards=[...host.querySelectorAll('.card')];const generic=cards.find(x=>x.querySelector('h3')?.textContent?.trim()==='Investmentthese');if(generic)generic.outerHTML=registryCard(v.asset,b);if(!host.querySelector('.a442-source'))host.insertAdjacentHTML('beforeend',methodCard(b));}catch(e){if(!host.querySelector('.a442-source'))host.insertAdjacentHTML('beforeend',`<div class="card a442-source"><div class="notice warn">Architecture Runtime: ${esc(e.message||e)}</div></div>`)}},80)}return out}}
function badge(){document.querySelectorAll('.version-badge,.badge').forEach(x=>{if((x.textContent||'').includes('ALPHA 4.4.1'))x.textContent='ALPHA 4.4.2 · Architecture Runtime'});}
new MutationObserver(badge).observe(document.body,{childList:true,subtree:true});badge();
window.HPOSArchitecture442={version:VERSION,load:architecture,registryKey,healthcareWeight};
})();