/* HPOS Alpha 4.6 – Fundamental Data Adapters */
(()=>{'use strict';
const VERSION='1.3.0-alpha.4.6';let cache=null;
const norm=v=>String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
async function load(){if(cache)return cache;try{let r=await fetch('../data/fundamental/evidence.json',{cache:'no-store'});if(!r.ok)throw new Error('evidence HTTP '+r.status);cache=await r.json()}catch(e){cache={schemaVersion:1,generatedAt:null,items:[],adapterStatus:[],error:String(e?.message||e)}}return cache}
function state(){try{return window.state||state||{}}catch{return {}}}
function assetForId(id){return (state().assets||[]).find(a=>String(a.assetId)===String(id))||null}
function itemsFor(data,asset){if(!asset)return[];let keys=[norm(asset.assetKey),norm(asset.ticker),norm(asset.name),norm(asset.isin)].filter(Boolean);return(data.items||[]).filter(x=>keys.includes(norm(x.assetKey))||keys.includes(norm(x.isin)))}
function requiredFor(asset){let role=String(asset?.role||asset?.category||'').toUpperCase();if(/HEALTH/.test(role))return['EARNINGS','GUIDANCE','FREE_CASH_FLOW','MARGIN','PIPELINE','REGULATORY','DIVIDEND'];if(/COMPOUNDER/.test(role))return['EARNINGS','REVENUE','MARGIN','FREE_CASH_FLOW','BALANCE_SHEET','ACQUISITION','CAPITAL_ALLOCATION'];return['EARNINGS','REVENUE','FREE_CASH_FLOW','BALANCE_SHEET']}
function summary(asset,data){let items=itemsFor(data,asset),cats=[...new Set(items.map(x=>x.category))],req=requiredFor(asset),missing=req.filter(x=>!cats.includes(x)),reg=items.filter(x=>x.sourceTier==='REGULATOR'||x.sourceTier==='PRIMARY').length;let score=Math.max(0,Math.min(100,Math.round((req.length?((req.length-missing.length)/req.length):0)*75+(items.length?15:0)+(reg?10:0))));return{items,categories:cats,required:req,missing,coveragePct:score,latest:items.map(x=>x.publishedAt||x.observedAt).filter(Boolean).sort().at(-1)||null,sourceQuality:reg?'PRIMARY/REGULATOR':'MISSING'}}
function fmtDate(v){if(!v)return'—';try{return new Date(v).toLocaleDateString('de-DE')}catch{return v}}
function card(asset,s){let shown=s.items.slice().sort((a,b)=>String(b.publishedAt||b.observedAt).localeCompare(String(a.publishedAt||a.observedAt))).slice(0,4);return`<div class="card" id="alpha46Evidence"><div class="row441"><div><h3>Fundamentale Evidenz</h3><p>Primär-/Regulatordaten gegen die Investmentthese</p></div><span class="badge ${s.coveragePct>=70?'good':s.coveragePct>=40?'warn':'bad'}">${s.coveragePct}% Coverage</span></div><div class="chips441"><span class="chip441 info">${s.items.length} Fakten</span><span class="chip441">${s.sourceQuality}</span><span class="chip441">Stand ${fmtDate(s.latest)}</span></div>${shown.length?`<div class="reasons441">${shown.map(x=>`<div class="reason441"><i>▦</i><div><strong>${String(x.category||'').replaceAll('_',' ')}</strong><small>${x.metric?x.metric+': ':''}${x.value??'—'} ${x.unit||''} · ${x.sourceName||x.sourceTier} · ${fmtDate(x.publishedAt)}</small></div></div>`).join('')}</div>`:'<div class="empty">Noch keine strukturierte fundamentale Evidenz für diesen Titel.</div>'}${s.missing.length?`<div class="rule-source">Fehlende erwartete Evidenz: ${s.missing.join(', ')}. Fehlende Daten reduzieren Konfidenz und erzeugen keine Freigabe.</div>`:''}</div>`}
async function inject(){let host=document.getElementById('a441host');if(!host||host.querySelector('#alpha46Evidence'))return;let asset=assetForId(host.dataset.id);if(!asset)return;let data=await load(),s=summary(asset,data);host.insertAdjacentHTML('beforeend',card(asset,s))}
new MutationObserver(()=>{inject().catch(()=>{})}).observe(document.body,{childList:true,subtree:true});setTimeout(()=>inject().catch(()=>{}),700);
window.HPOSFundamental46={version:VERSION,load,itemsFor,summary};})();
