/* HPOS Alpha 4.6.4 – Asset Interchangeability */
(()=>{'use strict';
const VERSION='1.3.0-alpha.4.6.4',BASE='../';let cache=null;
const norm=v=>String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const esc=v=>typeof window.esc==='function'?window.esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function j(p){let r=await fetch(BASE+p+'?v=464',{cache:'no-store'});if(!r.ok)throw new Error(p+': HTTP '+r.status);return r.json()}
async function load(){if(cache)return cache;let [catalog,policy,roles,thesis,signals]=await Promise.all([j('data/asset_catalog.json'),j('config/asset_interchangeability.json'),j('config/role_taxonomy.json'),j('data/thesis_registry.json'),j('data/fundamental/thesis_signals.json').catch(()=>({signals:[]}))]);cache={catalog,policy,roles,thesis,signals};return cache}
function resolve(asset,catalog){if(!asset||!catalog?.assets)return null;let isin=norm(asset.isin);if(isin)for(let[k,v]of Object.entries(catalog.assets))if(norm(v.isin)===isin)return k;let c=[asset.assetKey,asset.name,asset.ticker,asset.symbol].map(norm).filter(Boolean);for(let[k,v]of Object.entries(catalog.assets)){let ids=[k,v.name,...(v.aliases||[])].map(norm).filter(Boolean);if(c.some(x=>ids.some(i=>x===i||x.includes(i)||i.includes(x))))return k}return null}
function competitors(key,data){let row=data.catalog.assets[key];if(!row)return{direct:[],global:[]};let direct=[],global=[];for(let[k,v]of Object.entries(data.catalog.assets)){if(k===key)continue;global.push(k);if(v.family&&v.family===row.family)direct.push(k)}return{direct,global}}
function signalFor(key,data){return(data.signals?.signals||[]).find(x=>x.assetKey===key)||null}
function card(asset,data){let key=resolve(asset,data.catalog);if(!key)return'';let c=competitors(key,data),sig=signalFor(key,data),row=data.catalog.assets[key];let s=sig?.state||'INSUFFICIENT';return`<div class="card" id="alpha464Competition"><div class="row441"><div><h3>Kapitalwettbewerb</h3><p>Kein Titel besitzt Bestandsschutz</p></div><span class="badge info">AUSTAUSCHBAR</span></div><div class="chips441"><span class="chip441">Rolle ${esc(row.role||'—')}</span><span class="chip441">Familie ${esc(row.family||'—')}</span><span class="chip441 info">${c.direct.length} direkte Alternativen</span><span class="chip441">${c.global.length} globale Konkurrenten</span>${sig?`<span class="chip441 ${s==='STRENGTHENING'?'good':s==='WEAKENING'||s==='BROKEN'?'bad':'warn'}">These ${esc(s)}</span>`:''}</div><div class="rule-source">Jeder neue Euro vergleicht diesen Titel mit allen zulässigen Aktien. Eine Rotation bevorzugt rollennahe Alternativen, darf aber rollenübergreifend erfolgen, wenn Portfoliofunktion, Risiko und Nettoeffekt besser werden. Besitz erzeugt keinen Bonus.</div></div>`}
async function inject(){let h=document.getElementById('a441host');if(!h||h.querySelector('#alpha464Competition'))return;let asset=(window.state?.assets||[]).find(a=>String(a.assetId)===String(h.dataset.id));if(!asset)return;let d=await load(),html=card(asset,d);if(html)h.insertAdjacentHTML('beforeend',html)}
new MutationObserver(()=>inject().catch(()=>{})).observe(document.body,{childList:true,subtree:true});setTimeout(()=>inject().catch(()=>{}),900);
function badge(){document.querySelectorAll('.version-badge,.badge').forEach(x=>{if(/ALPHA 4\.6\b/.test(x.textContent||''))x.textContent='ALPHA 4.6.4 · Interchangeable Assets'})}new MutationObserver(badge).observe(document.body,{childList:true,subtree:true});badge();
window.HPOSInterchangeability464={version:VERSION,load,resolve,competitors,signalFor};
})();
