/* HPOS Alpha 4.5.1 – Tax Allowance + Halal Purification/Zakat */
(()=>{'use strict';
const VERSION='1.3.0-alpha.4.5.1';
const num=v=>Number.isFinite(Number(v))?Number(v):0;
function localState(){try{return window.state||state||{}}catch{return {}}}
function ledger(){try{return window.HPOSStateLedger45?.buildLedger?.()||{entries:[]}}catch{return{entries:[]}}}
function taxProfile(){const s=localState();return s.taxProfile||JSON.parse(localStorage.getItem('hpos_tax_profile_v1')||'null')||null}
function allowance(tp){if(!tp)return null;const total=num(tp.allowanceEur||(tp.assessment==='JOINT'?2000:1000));const used=(tp.brokers||[]).reduce((z,b)=>z+num(b.usedAllowanceEur),0);return{total,used,remaining:Math.max(0,total-used),exceededBy:Math.max(0,used-total)}}
function avgCostForIsin(isin){const rows=ledger().entries.filter(x=>x.isin===isin&&['BUY','SELL','OPENING_POSITION'].includes(x.type)).sort((a,b)=>String(a.datetime).localeCompare(String(b.datetime)));let qty=0,cost=0;for(const r of rows){const q=num(r.shares),p=num(r.price);if(r.type==='SELL'){if(qty<=0)continue;const sold=Math.min(q,qty),avg=cost/qty;qty-=sold;cost=Math.max(0,cost-avg*sold)}else{qty+=q;cost+=q*p+num(r.fee)}}return{qty,avg:qty>0?cost/qty:0}}
function saleSimulation({isin,shares,salePrice,fees=0,partialExemptionPct=0}){const tp=taxProfile(),a=allowance(tp),basis=avgCostForIsin(isin),q=Math.min(num(shares),basis.qty),gross=q*num(salePrice),cost=q*basis.avg+num(fees),rawGain=gross-cost,taxableBeforeLoss=Math.max(0,rawGain)*(1-num(partialExemptionPct)/100);const stockLoss=(tp?.brokers||[]).reduce((z,b)=>z+num(b.stockLossPotEur),0);const offset=Math.min(stockLoss,taxableBeforeLoss);const taxableAfterLoss=Math.max(0,taxableBeforeLoss-offset);const fsaUsed=Math.min(a?.remaining||0,taxableAfterLoss);const taxableAfterFsa=Math.max(0,taxableAfterLoss-fsaUsed);const capTax=taxableAfterFsa*.25;return{shares:q,grossProceeds:gross,costBasis:cost,rawGain,taxableBeforeLoss,stockLossOffset:offset,fsaUsed,taxableAfterFsa,estimatedCapitalGainsTax:capTax,allowanceRemainingAfter:Math.max(0,(a?.remaining||0)-fsaUsed),warning:!tp?'TAX_PROFILE_MISSING':a?.exceededBy>0?'ALLOWANCE_ALREADY_EXCEEDED':taxableAfterFsa>0?'ALLOWANCE_EXCEEDED_BY_SALE':'WITHIN_ALLOWANCE'}}
function maxSharesWithinAllowance({isin,salePrice,fees=0,partialExemptionPct=0}){const basis=avgCostForIsin(isin),tp=taxProfile(),a=allowance(tp);if(!tp||basis.qty<=0)return{shares:0,reason:'MISSING_TAX_OR_COST_BASIS'};const gainPerShare=Math.max(0,num(salePrice)-basis.avg)*(1-num(partialExemptionPct)/100);const stockLoss=(tp.brokers||[]).reduce((z,b)=>z+num(b.stockLossPotEur),0);if(gainPerShare<=0)return{shares:basis.qty,reason:'NO_POSITIVE_TAXABLE_GAIN'};const room=(a.remaining||0)+stockLoss+Math.max(0,num(fees));return{shares:Math.min(basis.qty,room/gainPerShare),reason:'ALLOWANCE_LIMIT',allowanceRemaining:a.remaining,stockLossPot:stockLoss,gainPerShare}}
function utilizationTip(){const tp=taxProfile(),a=allowance(tp);if(!tp)return{status:'UNKNOWN',text:'Broker-Steueransicht/Freistellungsauftrag lokal hinterlegen.'};if(a.remaining===0)return{status:'FULL',text:'Sparer-Pauschbetrag ausgeschöpft. Verkäufe nur nach Thesis-/Portfolioentscheidung; Steuer ist kein alleiniger Haltegrund.'};const month=new Date().getMonth()+1;if(month>=10)return{status:'REVIEW',text:`Noch ${a.remaining.toFixed(2)} € Pauschbetrag offen. Vor Jahresende gezielt realisierbare Gewinne prüfen, aber keine gute Position nur für Steueroptimierung drehen.`};return{status:'OK',text:`Noch ${a.remaining.toFixed(2)} € Pauschbetrag offen. HPOS berücksichtigt ihn bei echten Verkaufs-/Rotationsfällen.`}}
async function halalPolicy(){try{const r=await fetch('../config/halal_sources.json?v=451',{cache:'no-cache'});return r.ok?r.json():null}catch{return null}}
function purification({cashIncome,ratioPct}){return{purificationEur:Math.max(0,num(cashIncome)*num(ratioPct)/100),method:'SOURCE_RATIO_REQUIRED'}}
function zakat({marketValue,method='ACTIVE_MARKET_VALUE',zakatableAssetPct=30,ratePct=2.5}){const v=num(marketValue),rate=num(ratePct)/100;let base=v;if(method==='LONG_TERM_30PCT_PROXY')base=v*num(zakatableAssetPct)/100;return{method,baseEur:base,ratePct:num(ratePct),zakatEur:Math.max(0,base*rate),assumption:method==='LONG_TERM_ZAKATABLE_ASSETS'?'UNDERLYING_DATA_REQUIRED':method==='LONG_TERM_30PCT_PROXY'?'SCHOLARLY_PROXY':'MARKET_VALUE'}}
window.HPOSTaxHalal451={version:VERSION,taxProfile,allowance,saleSimulation,maxSharesWithinAllowance,utilizationTip,halalPolicy,purification,zakat};
})();
