/* HPOS Alpha 4.7 – Capital Allocation Engine */
(()=>{'use strict';
const VERSION='1.3.0-alpha.4.7',BASE='../';let cache=null;
const norm=v=>String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const esc=v=>typeof window.esc==='function'?window.esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):null;
async function j(p){let r=await fetch(BASE+p+'?v=47',{cache:'no-store'});if(!r.ok)throw new Error(p+': HTTP '+r.status);return r.json()}
async function load(){if(cache)return cache;const [policy,catalog,signals,constitution]=await Promise.all([j('config/capital_competition_policy.json'),j('data/asset_catalog.json'),j('data/fundamental/thesis_signals.json').catch(()=>({signals:[]})),j('config/hpos_constitution.json')]);cache={policy,catalog,signals,constitution};return cache}
function localState(){try{return window.state||{}}catch{return {}}}
function current(){try{return window.HPOSStateLedger45?.buildCurrentState?.()||null}catch{return null}}
function resolveAsset(asset,catalog){if(window.HPOSInterchangeability464?.resolve)return window.HPOSInterchangeability464.resolve(asset,catalog);const isin=norm(asset?.isin);if(isin)for(const[k,v]of Object.entries(catalog?.assets||{}))if(norm(v.isin)===isin)return k;return null}
function signal(key,d){return(d.signals?.signals||[]).find(x=>x.assetKey===key)||null}
function localAsset(key,d){return(localState().assets||[]).find(a=>resolveAsset(a,d.catalog)===key)||null}
function holdingByKey(key,d){return(current()?.positions||[]).find(p=>resolveAsset(p,d.catalog)===key)||null}
function portfolioValue(){return Number(current()?.portfolio?.portfolioValueEur||0)}
function familyWeights(d){const c=current(),total=Number(c?.portfolio?.portfolioValueEur||0),out={};if(!total)return out;for(const p of c.positions||[]){const k=resolveAsset(p,d.catalog),fam=d.catalog.assets?.[k]?.family||'UNKNOWN';out[fam]=(out[fam]||0)+Number(p.currentValue||0)/total*100}return out}
function dataTradeable(a){const x=String(a?.tradeability||a?.brokerAvailability||a?.tradable||'').toUpperCase();if(['YES','TRUE','TRADEABLE','AVAILABLE','CONFIRMED'].includes(x))return true;if(['NO','FALSE','UNAVAILABLE','BLOCKED'].includes(x))return false;return null}
async function halalOf(a){if(!a)return'UNKNOWN';try{const b=await window.HPOSDecision44?.bundle?.(a);return b?.decision?.halal?.status||'UNKNOWN'}catch{return'UNKNOWN'}}
function evidenceState(key,d){return signal(key,d)?.state||'INSUFFICIENT'}
function ordinal(value,map){const k=String(value||'').toUpperCase();return Object.prototype.hasOwnProperty.call(map,k)?map[k]:null}
function valuationDimension(a){return ordinal(a?.valuationStatus||a?.valuation?.status,{VERY_ATTRACTIVE:4,ATTRACTIVE:3,FAIR:2,EXPENSIVE:1,VERY_EXPENSIVE:0})}
function incomeDimension(a){return ordinal(a?.incomeQuality||a?.dividendQuality||a?.income?.quality,{EXCELLENT:4,STRONG:3,GOOD:2,WEAK:1,UNSAFE:0})}
function thesisDimension(s){return ordinal(s,{BROKEN:0,WEAKENING:1,NEUTRAL:2,STRENGTHENING:3})}
function netEconomicDimension(a){return num(a?.netEconomicEffectPct??a?.execution?.netEconomicEffectPct)}
async function evaluate(key,d){const cat=d.catalog.assets[key],a=localAsset(key,d),h=holdingByKey(key,d),halal=await halalOf(a),ev=evidenceState(key,d),blocks=[],notes=[],fw=familyWeights(d),familyPct=Number(fw[cat?.family]||0),total=portfolioValue(),weight=h&&total?Number(h.currentValue||0)/total*100:0,trade=dataTradeable(a),singleCap=Number(d.constitution.portfolioRules?.singleStock?.hardCapPct||25),hcCap=Number(d.constitution.portfolioRules?.healthcare?.hardCapPct||30);
if(halal!=='H1')blocks.push(`HALAL_${halal}`);
if(ev==='BROKEN')blocks.push('THESIS_BROKEN');else if(ev==='WEAKENING')blocks.push('THESIS_WEAKENING_REVIEW');else if(ev==='INSUFFICIENT')blocks.push('EVIDENCE_INSUFFICIENT');
if(cat?.family==='HEALTHCARE'&&familyPct>hcCap)blocks.push('HEALTHCARE_CAP');
if(weight>=singleCap)blocks.push('SINGLE_STOCK_CAP');
if(trade===false)blocks.push('NOT_TRADEABLE');else if(trade===null)blocks.push('TRADEABILITY_UNKNOWN');
if(!a)notes.push('Kein lokales Asset-/Watchlist-Objekt: Halal und Handelbarkeit bleiben unbekannt.');
const thesis=thesisDimension(ev),val=valuationDimension(a),income=incomeDimension(a),net=netEconomicDimension(a);
const dimensions={
 THESIS_EVIDENCE:{value:thesis,known:thesis!=null,higherIsBetter:true,label:ev},
 PORTFOLIO_FIT:{value:(weight>=singleCap||(cat?.family==='HEALTHCARE'&&familyPct>hcCap))?0:2,known:true,higherIsBetter:true,label:(weight>=singleCap?'SINGLE_CAP':cat?.family==='HEALTHCARE'&&familyPct>hcCap?'SECTOR_CAP':'PASS')},
 VALUATION:{value:val,known:val!=null,higherIsBetter:true,label:a?.valuationStatus||a?.valuation?.status||'UNKNOWN'},
 INCOME_QUALITY:{value:income,known:income!=null,higherIsBetter:true,label:a?.incomeQuality||a?.dividendQuality||a?.income?.quality||'UNKNOWN'},
 DIVERSIFICATION:{value:familyPct,known:!!cat?.family,higherIsBetter:false,label:`${cat?.family||'UNKNOWN'} ${familyPct.toFixed(1)}%`},
 NET_ECONOMIC_EFFECT:{value:net,known:net!=null,higherIsBetter:true,label:net==null?'UNKNOWN':`${net.toFixed(2)}%`}
};
return{assetKey:key,name:cat?.name||key,role:cat?.role||null,family:cat?.family||null,owned:!!h,positionWeightPct:weight,familyWeightPct:familyPct,halal,evidenceState:ev,tradeability:trade===true?'CONFIRMED':trade===false?'NO':'UNKNOWN',eligible:blocks.length===0,blocks,notes,dimensions};}
function compareDimension(a,b,name){const da=a.dimensions[name],db=b.dimensions[name];if(!da?.known||!db?.known)return{name,comparable:false,result:'UNKNOWN'};if(da.value===db.value)return{name,comparable:true,result:'EQUAL',a:da.label,b:db.label};const aBetter=da.higherIsBetter?da.value>db.value:da.value<db.value;return{name,comparable:true,result:aBetter?'A_BETTER':'B_BETTER',a:da.label,b:db.label}}
function compare(a,b){const names=['THESIS_EVIDENCE','PORTFOLIO_FIT','VALUATION','INCOME_QUALITY','DIVERSIFICATION','NET_ECONOMIC_EFFECT'],trace=names.map(n=>compareDimension(a,b,n)),known=trace.filter(x=>x.comparable),aAdv=known.filter(x=>x.result==='A_BETTER'),bAdv=known.filter(x=>x.result==='B_BETTER');return{a:a.assetKey,b:b.assetKey,trace,aDominates:a.eligible&&b.eligible&&aAdv.length>0&&bAdv.length===0,bDominates:a.eligible&&b.eligible&&bAdv.length>0&&aAdv.length===0,knownDimensions:known.length}}
function choose(rows){const eligible=rows.filter(x=>x.eligible);if(!eligible.length)return{outcome:'WAIT',best:null,reason:'Kein Titel passiert aktuell alle bekannten Gates.'};const undominated=eligible.filter(a=>!eligible.some(b=>b.assetKey!==a.assetKey&&compare(b,a).aDominates));if(undominated.length===1){const best=undominated[0],beats=eligible.filter(x=>x.assetKey!==best.assetKey&&compare(best,x).aDominates);if(beats.length)return{outcome:'BEST_NEW_MONEY_DESTINATION',best,reason:'Ein Kandidat ist auf keiner bekannten vergleichbaren Dimension schlechter und auf mindestens einer besser.',comparisonBasis:'PARETO'}}return{outcome:'NO_CLEAR_ADVANTAGE',best:null,candidates:undominated.map(x=>x.assetKey),reason:'Kein belastbarer dominanter Vorteil. Unbekannte Daten zählen nicht als Pluspunkt.',comparisonBasis:'PARETO'}}
function rotation(rows){const owned=rows.filter(x=>x.owned),dest=rows.filter(x=>x.eligible),options=[];for(const src of owned)for(const dst of dest){if(src.assetKey===dst.assetKey)continue;const c=compare(dst,src);if(!c.aDominates)continue;const thesisAdv=c.trace.some(x=>x.name==='THESIS_EVIDENCE'&&x.result==='A_BETTER'),otherAdv=c.trace.some(x=>!['THESIS_EVIDENCE','NET_ECONOMIC_EFFECT'].includes(x.name)&&x.result==='A_BETTER'),netKnown=dst.dimensions.NET_ECONOMIC_EFFECT.known&&src.dimensions.NET_ECONOMIC_EFFECT.known;if((src.evidenceState==='WEAKENING'||thesisAdv)&&otherAdv&&netKnown)options.push({source:src.assetKey,destination:dst.assetKey,comparison:c,status:'ROTATION_ELIGIBLE_FOR_REVIEW'});}
if(options.length===1)return{outcome:'BEST_ROTATION',...options[0],reason:'Rotation erfüllt Thesis-/Portfolio-Vorteil und bekannten Nettoeffekt; Ausführung bleibt Nutzerentscheidung.'};if(options.length>1)return{outcome:'NO_CLEAR_ROTATION',candidates:options,reason:'Mehrere Rotationen erfüllen die Mindestbedingungen; keine Scheingenauigkeit.'};return{outcome:'NONE',reason:'Keine Rotation erfüllt aktuell Thesis-Vorteil + weiteren belegten Vorteil + bekannten Nettoeffekt.'}}
async function run(){const d=await load(),rows=[];for(const k of Object.keys(d.catalog.assets||{}))rows.push(await evaluate(k,d));const cash=window.HPOSStateLedger45?.snapshot?await window.HPOSStateLedger45.snapshot():null,choice=choose(rows),rot=rotation(rows);if(cash?.cash?.status==='RED'){choice.outcome='BLOCKED';choice.best=null;choice.reason='Cash-Hard-Limit blockiert reguläre Neuallokation.'}return{version:VERSION,asOf:new Date().toISOString(),rows,choice,rotation:rot,cash:cash?.cash||null,policy:d.policy}}
function compact(r){const b=r.choice.best;return`<div class="card" id="alpha47Allocation"><div class="row441"><div><h3>Nächster Euro</h3><p>Alle zulässigen Aktien konkurrieren</p></div><span class="badge ${b?'good':'warn'}">${esc(r.choice.outcome)}</span></div>${b?`<div style="margin-top:10px"><strong style="font-size:18px">${esc(b.name)}</strong><p>${esc(r.choice.reason)}</p><div class="chips441"><span class="chip441 good">☪ H1</span><span class="chip441 info">These ${esc(b.evidenceState)}</span><span class="chip441">${b.owned?'Bestand':'Kandidat'}</span><span class="chip441">Gewicht ${b.positionWeightPct.toFixed(1)} %</span></div></div>`:`<div class="notice warn" style="margin-top:10px">${esc(r.choice.reason)}</div>`}<div class="rule-source">Rotation: ${esc(r.rotation.outcome)} · ${esc(r.rotation.reason||'')}</div><details class="detail441" style="margin-top:10px"><summary>Methodik</summary><p>Gates zuerst, danach Pareto-Dominanz statt Punktesumme. Ein Titel gewinnt nur, wenn er auf keiner bekannten vergleichbaren Dimension schlechter und auf mindestens einer besser ist. Unbekannte Daten, Besitz und Momentum zählen nie als Vorteil.</p></details></div>`}
async function inject(){const h=document.getElementById('a441host');if(!h||h.querySelector('#alpha47Allocation'))return;const r=await run();h.insertAdjacentHTML('afterbegin',compact(r))}
new MutationObserver(()=>inject().catch(()=>{})).observe(document.body,{childList:true,subtree:true});setTimeout(()=>inject().catch(()=>{}),1000);
function badge(){document.querySelectorAll('.version-badge,.badge').forEach(x=>{if(/ALPHA 4\.6\.4\b/.test(x.textContent||''))x.textContent='ALPHA 4.7 · Capital Allocation'})}new MutationObserver(badge).observe(document.body,{childList:true,subtree:true});badge();
window.HPOSCapital47={version:VERSION,load,evaluate,run,compare,choose,rotation};
})();
