/* HPOS Alpha 4.3.2 – Halal & News Hardening
   - gleiche Halal-Quelle: neueste dokumentierte Prüfung ersetzt nur den effektiven Status,
     die Historie bleibt unveränderlich sichtbar
   - gleiche Quelle + exakt unauflösbarer widersprüchlicher Zeitstempel => H2/Review statt Zufall
   - News werden VOR Pagination nach Depot/Watchlist, Qualität und Suche gefiltert
   - Primärquellen-Registry deckt alle realen Depotpositionen ab
*/
(() => {
'use strict';
const VERSION432='1.3.0-alpha.4.3.2';
const FEED432='../data/news/news_feed.json', STATUS432='../data/news/news_status.json';
const REG432='../config/source_registry.json', ASSET_SOURCES432='../config/asset_sources.json';
let feed432=null,status432=null,load432=null,registry432=null,assetSources432=null,limit432=20;
const rank432={PRIMARY:0,PROFESSIONAL:1,RESEARCH:2,DISCOVERY:3};
const strictRank432={H0:4,H2:3,UNKNOWN:2,H1:1};
const norm432=v=>String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const srcEq432=(a,b)=>String(a??'').trim().toLowerCase()===String(b??'').trim().toLowerCase();

function css432(){if($('#alpha432css'))return;const s=document.createElement('style');s.id='alpha432css';s.textContent=`
.halal-current432{display:grid;gap:8px}.halal-row432{border-top:1px solid var(--line);padding:10px 0}.halal-row432:first-child{border-top:0}.halal-row432 .top{align-items:center}.historical432{opacity:.68}.current-tag432{font-size:9px;color:var(--green);border:1px solid rgba(56,217,150,.32);border-radius:999px;padding:2px 6px;margin-left:5px}.history-tag432{font-size:9px;color:var(--muted);border:1px solid var(--line);border-radius:999px;padding:2px 6px;margin-left:5px}.halal-warning432{border-left:4px solid var(--orange)}
.news-scope432{display:flex;gap:6px;overflow-x:auto;scrollbar-width:none;margin:12px 0}.news-scope432::-webkit-scrollbar{display:none}.news-scope432 button{white-space:nowrap;border:1px solid var(--line);background:var(--panel);color:var(--muted);border-radius:999px;padding:7px 10px;font-size:11px}.news-scope432 button.active{background:var(--green);border-color:var(--green);color:#062116;font-weight:800}.source-coverage432{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.source-row432{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 0;border-top:1px solid var(--line)}.source-row432:first-child{border-top:0}.source-row432 small{display:block;color:var(--muted);margin-top:3px}.source-row432 a{white-space:nowrap}
.news-empty432{padding:24px;text-align:center;color:var(--muted)}
`;document.head.appendChild(s);}

function parseTime432(v){if(!v)return NaN;const t=Date.parse(v);return Number.isFinite(t)?t:NaN;}
function compareChecks432(a,b){
  const ca=parseTime432(a.checkedAt),cb=parseTime432(b.checkedAt);if(Number.isFinite(ca)&&Number.isFinite(cb)&&ca!==cb)return cb-ca;
  const ar=parseTime432(a.recordedAt||a.updatedAt||a.createdAt),br=parseTime432(b.recordedAt||b.updatedAt||b.createdAt);if(Number.isFinite(ar)&&Number.isFinite(br)&&ar!==br)return br-ar;
  if(Number.isFinite(ar)!==Number.isFinite(br))return Number.isFinite(br)?1:-1;
  return String(b.checkId||'').localeCompare(String(a.checkId||''));
}
function sourceState432(checks){
  const sorted=[...checks].sort(compareChecks432),top=sorted[0];if(!top)return{current:null,ambiguous:false,history:[]};
  const sameMoment=sorted.filter(c=>String(c.checkedAt||'')===String(top.checkedAt||'')&&String(c.recordedAt||c.updatedAt||c.createdAt||'')===String(top.recordedAt||top.updatedAt||top.createdAt||''));
  const statuses=new Set(sameMoment.map(c=>c.status));
  return{current:top,ambiguous:statuses.size>1,history:sorted};
}
function latestSources432(stateObj,asset){
  const all=(stateObj.halalChecks||[]).filter(c=>c.assetId===asset.assetId),groups=[];
  for(const c of all){let g=groups.find(x=>srcEq432(x.source,c.source));if(!g){g={source:c.source,checks:[]};groups.push(g)}g.checks.push(c)}
  return groups.map(g=>({...g,...sourceState432(g.checks)}));
}
function getEffectiveHalal432(stateObj,asset){
  const exception=stateObj.standardProfile.rules.nvoException;
  const nvoMatch=(exception.match.isin&&asset.isin===exception.match.isin)||(exception.match.ticker&&String(asset.ticker??'').toUpperCase()===exception.match.ticker);
  const groups=latestSources432(stateObj,asset),all=groups.flatMap(g=>g.history).sort(compareChecks432);
  if(nvoMatch)return{status:'H2',conflict:true,reason:'Explizite NVO-Einzelregel im Masterfile.',ruleId:exception.ruleId,checks:all,latestBySource:groups};
  if(!groups.length)return{status:'UNKNOWN',conflict:false,reason:'Keine Halal-Prüfung hinterlegt.',ruleId:null,checks:[],latestBySource:[]};
  const ambiguous=groups.filter(g=>g.ambiguous);
  if(ambiguous.length)return{status:'H2',conflict:true,reason:`Widersprüchliche Prüfungen derselben Quelle ohne eindeutig neueren Zeitstempel: ${ambiguous.map(g=>g.source).join(', ')}. Manuelle Klärung erforderlich.`,ruleId:'HALAL.SAME_SOURCE.AMBIGUOUS',checks:all,latestBySource:groups};
  const latest=groups.map(g=>g.current).filter(Boolean),statuses=[...new Set(latest.map(c=>c.status))];
  if(statuses.length===1)return{status:statuses[0],conflict:false,reason:latest.length===1?`Aktuelles Urteil von ${latest[0].source}; ältere Prüfungen derselben Quelle sind Historie.`:'Aktuelle Urteile der Quellen stimmen überein.',ruleId:statuses[0]==='H0'?'HALAL.H0.VETO':statuses[0]==='H2'?'HALAL.H2.FREEZE':null,checks:latest,latestBySource:groups};
  const effective=getEffectiveProfile(stateObj),policy=effective.halalConflictPolicy,priority=effective.rules.halalSourcePriority.effectiveValue||[];
  if(policy==='STRICTEST'){const strict=[...latest].sort((a,b)=>(strictRank432[b.status]||0)-(strictRank432[a.status]||0))[0];return{status:strict.status,conflict:true,reason:'Aktuelle Quellen widersprechen sich; strengstes Urteil gemäß Nutzerpolitik.',ruleId:'HALAL.SOURCE.POLICY',checks:latest,latestBySource:groups};}
  if(policy==='PRIORITY_SOURCE'){for(const src of priority){const c=latest.find(x=>srcEq432(x.source,src));if(c)return{status:c.status,conflict:true,reason:`Aktuelle Quellen widersprechen sich; ${src} entscheidet gemäß Quellenpriorität.`,ruleId:'HALAL.SOURCE.POLICY',checks:latest,latestBySource:groups};}return{status:'UNKNOWN',conflict:true,reason:'Quellenkonflikt; keine priorisierte Quelle vorhanden.',ruleId:'HALAL.SOURCE.POLICY',checks:latest,latestBySource:groups};}
  return{status:'H2',conflict:true,reason:'Aktuelle Quellen widersprechen sich → H2 / manuelle Klärung.',ruleId:'HALAL.SOURCE.POLICY',checks:latest,latestBySource:groups};
}
getEffectiveHalal=getEffectiveHalal432;

function sourceOptions432(){const pref=getEffectiveProfile(state).rules.halalSourcePriority.effectiveValue||[];return[...new Set([...pref,'Musaffa','Zoya','Muslim Xchange','Sharlife','Manuell'])].map(x=>`<option>${esc(x)}</option>`).join('');}
openHalalForm=function(assetId=null){
  openModal('Halal-Prüfung',`<form id="halalForm" class="form">${assetFields()}<div class="two"><div class="field"><label>Quelle</label><select id="halalSource">${sourceOptions432()}</select></div><div class="field"><label>Status</label><select id="halalStatus" required><option value="">Status auswählen</option><option>H1</option><option>H2</option><option>H0</option><option>UNKNOWN</option></select></div></div><div class="notice info">Pro Quelle zählt für den effektiven Status nur die eindeutig neueste Prüfung. Ältere Einträge bleiben unverändert als Historie sichtbar. H2 = FREEZE, H0 = VETO.</div><div class="field"><label>Prüfdatum</label><input id="halalDate" type="date" value="${isoDate()}"></div><div class="field"><label>Beleg / Referenz</label><input id="halalEvidence" placeholder="URL, Screenshot, Notiz-ID …"><div class="field-help">Für H1 und H0 ist ein Beleg verpflichtend.</div></div><div class="field"><label>Notiz</label><textarea id="halalNote" placeholder="Was wurde geprüft / warum ändert sich ggf. der Status?"></textarea></div><button class="btn primary" type="submit">Prüfung speichern</button></form>`);
  bindAssetToggle();if(assetId&&$('#assetSelect')){$('#assetSelect').value=assetId;$('#assetSelect').dispatchEvent(new Event('change'));}
  $('#halalForm').onsubmit=e=>{e.preventDefault();try{const a=resolveAsset(),status=$('#halalStatus').value,evidence=$('#halalEvidence').value.trim(),now=new Date().toISOString();if(!status)throw new Error('Halal-Status auswählen.');if(['H1','H0'].includes(status)&&!evidence)throw new Error(`${status} benötigt einen Beleg / eine Referenz.`);state.halalChecks.push({checkId:crypto.randomUUID(),assetId:a.assetId,source:$('#halalSource').value,status,checkedAt:$('#halalDate').value,evidenceRef:evidence||null,note:$('#halalNote').value.trim()||null,enteredBy:'user',createdAt:now,recordedAt:now,updatedAt:now});persist();recompute();closeModal();toast('Halal-Prüfung dokumentiert');if(currentPage==='asset'&&currentAssetId===a.assetId){currentAssetTab='halal';renderAssetDetail();}else route('halal',false);}catch(err){toast(err.message);}};
};

const baseTab432=renderAssetTab;
renderAssetTab=function(v,tab){
  if(tab==='halal'){
    const a=v.asset,eff=getEffectiveHalal(state,a),groups=latestSources432(state,a),all=groups.flatMap(g=>g.history).sort(compareChecks432),currentIds=new Set(groups.filter(g=>g.current).map(g=>g.current.checkId));
    return `<div id="assetFacts431" class="stack"><div class="card"><div class="top"><div><h3>Halal-Verifikation</h3><p>Automatik getrennt von manueller, belegter Historie.</p></div><span class="badge info">Auto nicht verbunden</span></div><div class="asset-facts431" style="margin-top:10px"><div class="asset-fact431"><small>Automatische Vorprüfung</small><strong>UNKNOWN</strong></div><div class="asset-fact431"><small>Manuell effektiv</small><strong>${esc(eff.status)}</strong></div><div class="asset-fact431"><small>Aktuelle Quellen</small><strong>${groups.length}</strong></div><div class="asset-fact431"><small>Historieneinträge</small><strong>${all.length}</strong></div></div><div class="rule-source">Ohne verifizierte Screening-API wird kein automatisches H1 erzeugt.</div></div>${halalWorkflowNotice(v)}<div class="card ${eff.ruleId==='HALAL.SAME_SOURCE.AMBIGUOUS'?'halal-warning432':''}"><div class="top"><div><h3>Effektiver Status</h3><p>${esc(eff.reason)}</p></div><span class="badge ${statusClass(eff.status)}">${esc(eff.status)}</span></div><div class="section-head" style="margin-top:14px"><div><h3>Aktuell je Quelle</h3><p>Nur diese Urteile fließen in den effektiven Status ein</p></div></div><div class="halal-current432">${groups.length?groups.map(g=>{const c=g.current;return`<div class="halal-row432"><div class="top"><div><strong>${esc(g.source)}</strong><span class="current-tag432">aktuell</span><div class="sub">Prüfung ${esc(dateFmt(c.checkedAt))}${c.recordedAt||c.updatedAt?` · erfasst ${esc(dateFmt(c.recordedAt||c.updatedAt))}`:''}</div></div><span class="badge ${statusClass(g.ambiguous?'H2':c.status)}">${esc(g.ambiguous?'KLÄREN':c.status)}</span></div>${c.evidenceRef?`<div class="rule-source">Beleg: ${esc(c.evidenceRef)}</div>`:''}${g.history.length>1?`<div class="rule-source">${g.history.length-1} ältere Prüfung${g.history.length===2?'':'en'} dieser Quelle in der Historie.</div>`:''}</div>`;}).join(''):'<div class="empty">Noch keine Prüfung.</div>'}</div><div class="action-row"><button class="btn primary small" data-add-halal>＋ Prüfung erfassen</button></div></div>${all.length>1?`<details class="card" style="margin-top:0"><summary>Vollständige Historie (${all.length})</summary><div>${all.map(c=>`<div class="halal-row432 ${currentIds.has(c.checkId)?'':'historical432'}"><div class="top"><div><strong>${esc(c.source)}</strong><span class="${currentIds.has(c.checkId)?'current-tag432':'history-tag432'}">${currentIds.has(c.checkId)?'aktuell':'historisch'}</span><div class="sub">${esc(dateFmt(c.checkedAt))}</div></div><span class="badge ${statusClass(c.status)}">${esc(c.status)}</span></div>${c.evidenceRef?`<div class="rule-source">Beleg: ${esc(c.evidenceRef)}</div>`:''}${c.note?`<div class="rule-source">${esc(c.note)}</div>`:''}</div>`).join('')}</div></details>`:''}</div>`;
  }
  if(tab==='news')return renderAssetNews432(v);
  return baseTab432(v,tab);
};

async function json432(url){const r=await fetch(`${url}${url.includes('?')?'&':'?'}v=432`,{cache:'no-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
async function loadNews432(force=false){if(feed432&&!force)return feed432;if(load432&&!force)return load432;load432=Promise.all([json432(FEED432),json432(STATUS432)]).then(([f,s])=>{feed432=f;status432=s;return f}).catch(()=>{feed432={items:[],assetIndex:{},loadError:true};status432={state:'ERROR',message:'News-Snapshot nicht erreichbar.'};return feed432}).finally(()=>load432=null);return load432;}
function aid432(n){const m=feed432?.assetIndex?.[n.assetKey]||{},isin=String(n.isin||m.isin||'').toUpperCase();if(isin){const a=state.assets.find(x=>String(x.isin||'').toUpperCase()===isin);if(a)return a.assetId;}const t=norm432(n.ticker||m.ticker);if(t){const hits=state.assets.filter(x=>norm432(x.ticker)===t);if(hits.length===1)return hits[0].assetId;}const aliases=[n.assetName,m.name,...(m.aliases||[])].filter(Boolean).map(norm432);for(const a of state.assets){if([a.name,a.ticker,a.isin].filter(Boolean).map(norm432).some(x=>aliases.includes(x)))return a.assetId;}return null;}
function allNews432(assetId=null){const auto=(feed432?.items||[]).map(n=>{const m=feed432?.assetIndex?.[n.assetKey]||{};const id=aid432(n);return{...n,assetId:id,assetName:n.assetName||m.name,scope:n.scope||m.scope,origin:'AUTO',sourceTier:n.sourceTier||(n.primarySource?'PRIMARY':'DISCOVERY')}}),local=(state.newsEntries||[]).map(n=>({...n,origin:'MANUAL',sourceTier:n.sourceTier||'RESEARCH'}));const rows=[...auto,...local].filter(n=>!assetId||n.assetId===assetId),seen=new Set(),out=[];for(const n of rows.sort((a,b)=>String(b.publishedAt||b.updatedAt||'').localeCompare(String(a.publishedAt||a.updatedAt||'')))){const k=n.url||`${n.assetId||n.assetKey}|${norm432(n.title)}`;if(seen.has(k))continue;seen.add(k);out.push(n)}return out;}
function scope432(n){const a=n.assetId?state.assets.find(x=>x.assetId===n.assetId):null;if(a?.portfolioRole==='HOLDING')return a.broker==='TRADE_REPUBLIC'?'TRADE_REPUBLIC':'SCALABLE';if(a?.portfolioRole==='WATCHLIST')return'WATCHLIST';if(n.scope==='PORTFOLIO')return'PORTFOLIO';if(n.scope==='WATCHLIST')return'WATCHLIST';return'OTHER';}
function newsState432(){const u=state.userProfile.ui=state.userProfile.ui||{};u.n42=u.n42||{tier:'ALL',sort:'priority',q:''};u.alpha431=u.alpha431||{newsScope:'ALL'};u.alpha432=u.alpha432||{lastAccount:null};const account=state.userProfile.ui?.alpha43?.account||'ALL';if(u.alpha432.lastAccount!==account){u.alpha432.lastAccount=account;u.alpha431.newsScope=account==='SCALABLE'?'SCALABLE':account==='TRADE_REPUBLIC'?'TRADE_REPUBLIC':account==='WATCHLIST'?'WATCHLIST':'PORTFOLIO';persist();}return{f:u.n42,scope:u.alpha431.newsScope||'PORTFOLIO'};}
function scopeMatch432(n,s){const x=scope432(n);if(s==='ALL')return true;if(s==='PORTFOLIO')return x==='SCALABLE'||x==='TRADE_REPUBLIC'||x==='PORTFOLIO';return x===s;}
function filteredNews432(){const {f,scope}=newsState432(),q=String(f.q||'').toLowerCase();let rows=allNews432().filter(n=>scopeMatch432(n,scope)).filter(n=>f.tier==='ALL'||n.sourceTier===f.tier).filter(n=>!q||`${n.title||''} ${n.source||''} ${n.assetName||''}`.toLowerCase().includes(q));rows.sort((a,b)=>f.sort==='date'?String(b.publishedAt||b.updatedAt||'').localeCompare(String(a.publishedAt||a.updatedAt||'')):(rank432[a.sourceTier]??9)-(rank432[b.sourceTier]??9)||String(b.publishedAt||b.updatedAt||'').localeCompare(String(a.publishedAt||a.updatedAt||'')));return rows;}
function newsCard432(n){const a=n.assetId?state.assets.find(x=>x.assetId===n.assetId):null,t=n.sourceTier||'DISCOVERY',lab={PRIMARY:'Primär',PROFESSIONAL:'Profi',RESEARCH:'Research',DISCOVERY:'Discovery'}[t]||t;return`<div class="card news-card" data-nt42="${esc(t)}" data-na-scope432="${esc(scope432(n))}" data-nd42="${esc(n.publishedAt||n.updatedAt||'')}"><div class="top"><div><strong>${esc(n.title||'Meldung')}</strong>${a?`<button class="asset-link" data-na42="${esc(a.assetId)}">${esc(a.name)}</button>`:n.assetName?`<div class="sub">${esc(n.assetName)}</div>`:''}</div><span class="badge info">${esc(n.source||'Quelle unbekannt')}</span></div><div class="asset-badges"><span class="badge ${t==='PRIMARY'?'good':t==='RESEARCH'?'warn':'info'}">${esc(lab)}</span><span class="badge">${n.origin==='AUTO'?'Automatisch':'Manuell'}</span></div><p>${esc(n.summary||n.note||(n.origin==='AUTO'?'Gefundene Meldung. Inhalt noch nicht automatisch als Investmentwirkung bewertet.':'Keine Zusammenfassung gespeichert.'))}</p><div class="rule-source">${esc(dateFmt(n.publishedAt||n.updatedAt))}</div>${n.url?`<div class="action-row"><a class="btn small" href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">Quelle öffnen</a></div>`:''}</div>`;}
async function loadSources432(){if(!registry432){try{registry432=await json432(REG432)}catch{registry432={sources:[]}}}if(!assetSources432){try{assetSources432=await json432(ASSET_SOURCES432)}catch{assetSources432={assets:[]}}}}
async function openSources432(){await loadSources432();const holdings=new Set((state.assets||[]).filter(a=>a.portfolioRole==='HOLDING').map(a=>String(a.isin||'').toUpperCase())),rows=(assetSources432.assets||[]).filter(s=>holdings.has(String(s.isin).toUpperCase()));openModal('Quellen & Abdeckung',`<div class="stack"><div class="card"><div class="top"><div><h3>Primärquellen reales Depot</h3><p>Unternehmens-/Fondsanbieterquellen, unabhängig vom früheren Testbestand.</p></div><span class="badge good">${rows.length}/${holdings.size}</span></div>${rows.map(s=>`<div class="source-row432"><div><strong>${esc(s.name)}</strong><small>${esc(s.sourceName)} · ${esc(s.registry||'Primärquelle')} · ${esc(s.automationMode||'REFERENCE')}</small></div><a class="btn small" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Öffnen</a></div>`).join('')}</div><div class="card"><h3>Übergreifende Research-Quellen</h3>${(registry432.sources||[]).filter(s=>['PROFESSIONAL','RESEARCH'].includes(s.tier)).map(s=>`<div class="source-row432"><div><strong>${esc(s.name)}</strong><small>${esc(s.use||'')}</small></div>${s.url?`<a class="btn small" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Öffnen</a>`:''}</div>`).join('')}</div></div>`);}
function setScope432(s){state.userProfile.ui.alpha431=state.userProfile.ui.alpha431||{};state.userProfile.ui.alpha431.newsScope=s;state.userProfile.ui.alpha432=state.userProfile.ui.alpha432||{};state.userProfile.ui.alpha432.lastAccount=state.userProfile.ui?.alpha43?.account||'ALL';limit432=20;persist();renderNews();}

renderNews=async function(){
  if(!feed432){$('#main').innerHTML='<div class="card">News werden geladen …</div>';await loadNews432();if(currentPage!=='news')return;}
  const {f,scope}=newsState432(),all=allNews432(),rows=filteredNews432(),items=rows.slice(0,limit432),d=status432||state.dataStatus.news||{state:'UNKNOWN',message:'News-Status unbekannt.'};
  const count=s=>all.filter(n=>scopeMatch432(n,s)).length;
  $('#main').innerHTML=`<div class="section-head"><div><h1>News</h1><p>Primärquellen → Profi → Research → Discovery</p></div><div class="action-row" style="margin:0"><button class="btn small" id="nsrc42">Quellen</button><button class="btn small" id="nref42">Neu laden</button><button class="btn small" id="newsAi">Mit ChatGPT prüfen</button><button class="btn primary small" id="newsAdd">＋ Meldung</button></div></div><div class="card"><div class="top"><div><h3>Datenstatus</h3><p>${esc(d.message||'')}</p></div>${dataStateBadge(d)}</div><div class="source-coverage432"><span class="badge">Portfolio-News ${count('PORTFOLIO')}</span><span class="badge">Watchlist-News ${count('WATCHLIST')}</span>${feed432.directSources?`<span class="badge info">Direktadapter ${feed432.directSources.filter(x=>x.ok).length}/${feed432.directSources.length}</span>`:''}</div></div><div id="newsScope431" class="news-scope432">${[['ALL','Alle'],['PORTFOLIO','Mein Depot'],['SCALABLE','Scalable'],['TRADE_REPUBLIC','Trade Republic'],['WATCHLIST','Watchlist']].map(([x,l])=>`<button class="${scope===x?'active':''}" data-scope432="${x}">${l} <span class="scope-count431">${count(x)}</span></button>`).join('')}</div><div class="chips42">${[['ALL','Alle'],['PRIMARY','Primär'],['PROFESSIONAL','Profi'],['RESEARCH','Research'],['DISCOVERY','Discovery']].map(([x,l])=>`<button class="chip42 ${f.tier===x?'active':''}" data-tier432="${x}">${l}</button>`).join('')}</div><div class="controls42"><input id="nq432" value="${esc(f.q||'')}" placeholder="Titel, Quelle oder Asset"><select id="ns432"><option value="priority">Priorität</option><option value="date">Neueste</option></select></div><div class="section-head"><div><h2>Meldungen</h2><p>${items.length} von ${rows.length} im aktuellen Filter</p></div></div><div class="stack" id="nst42">${items.length?items.map(newsCard432).join(''):`<div class="card news-empty432">Keine Meldung für diesen Filter im gesamten geladenen Snapshot.</div>`}</div>${rows.length>limit432?'<div class="action-row"><button class="btn" id="nmore432">Weitere 20</button></div>':''}`;
  $('#ns432').value=f.sort;$$('[data-scope432]').forEach(b=>b.onclick=()=>setScope432(b.dataset.scope432));$$('[data-tier432]').forEach(b=>b.onclick=()=>{f.tier=b.dataset.tier432;limit432=20;persist();renderNews();});let timer;$('#nq432').oninput=e=>{f.q=e.target.value;clearTimeout(timer);timer=setTimeout(()=>{limit432=20;persist();renderNews();},180);};$('#ns432').onchange=e=>{f.sort=e.target.value;limit432=20;persist();renderNews();};$('#nmore432')?.addEventListener('click',()=>{limit432+=20;renderNews();});$('#nsrc42').onclick=openSources432;$('#nref42').onclick=async()=>{feed432=null;status432=null;limit432=20;await loadNews432(true);toast('News-Snapshot neu geladen');renderNews();};$('#newsAdd').onclick=()=>openNewsForm();$('#newsAi').onclick=openAiHandoff;$$('[data-na42]').forEach(b=>b.onclick=()=>openAsset(b.dataset.na42,'news'));renderNav();
};

function renderAssetNews432(v){const a=v.asset;if(!feed432&&!load432)loadNews432().then(()=>{if(currentPage==='asset'&&currentAssetTab==='news')renderAssetDetail();});const rows=feed432?allNews432(a.assetId):[],items=rows.slice(0,15),src=(assetSources432?.assets||[]).find(s=>String(s.isin).toUpperCase()===String(a.isin||'').toUpperCase());if(!assetSources432)loadSources432().then(()=>{if(currentPage==='asset'&&currentAssetTab==='news')renderAssetDetail();});return`<div class="stack">${src?`<div class="card asset-source431"><div class="top"><div><strong>Offizielle Primärquelle</strong><p>${esc(src.sourceName)}</p></div><a class="btn small" href="${esc(src.url)}" target="_blank" rel="noopener noreferrer">Öffnen</a></div></div>`:''}<div class="section-head"><div><h2>News</h2><p>${rows.length} Meldung${rows.length===1?'':'en'} diesem Asset zugeordnet</p></div><button class="btn primary small" data-add-news>＋ Meldung</button></div><div class="stack">${items.length?items.map(newsCard432).join(''):`<div class="card empty">${feed432?'Keine Meldung zu diesem Asset im aktuellen Snapshot.':'News werden geladen …'}</div>`}</div>${rows.length>15?`<div class="rule-source">Weitere Meldungen im Hauptbereich News verfügbar.</div>`:''}</div>`;}

const baseAssetDetail432=renderAssetDetail;
renderAssetDetail=function(){baseAssetDetail432();if(currentAssetTab==='halal'||currentAssetTab==='news')setTimeout(()=>{$('[data-add-halal]')?.addEventListener('click',()=>openHalalForm(currentAssetId));$('[data-add-news]')?.addEventListener('click',()=>openNewsForm(currentAssetId));},0);};

css432();loadNews432();loadSources432();state.appMeta.appVersion=VERSION432;document.title='HPOS Alpha 4.3.2 · Halal & News Hardening';
})();
