/* HPOS Alpha 4.4 – Decision Engine
   Ziel: aus lokalen Depotdaten + Markt + Halal + Regeln + News eine nachvollziehbare
   Entscheidungslage erzeugen. Keine Kauf-/Verkaufsautomatik; Signale bleiben erklärbar.
*/
(() => {
'use strict';
const VERSION44='1.3.0-alpha.4.4';
const MARKET_SUM44='../data/market/market_summary.json';
const MARKET_DIR44='../data/market/';
const NEWS_FEED44='../data/news/news_feed.json';
let marketSummary44=null,newsFeed44=null;
const marketFiles44=new Map();
const DAY=86400000;

function css44(){
  if(document.getElementById('alpha44css'))return;
  const s=document.createElement('style');s.id='alpha44css';s.textContent=`
  :root{--bg:#08111c;--panel:#0e1927;--panel2:#142235;--line:#26364a;--text:#f3f6fa;--muted:#91a4ba;--green:#24c98b;--orange:#e7a847;--red:#e26a6a;--blue:#5b9cf6;--yellow:#d9c76c}
  .decision44{border-left:4px solid var(--blue)}.decision44.good{border-left-color:var(--green)}.decision44.warn{border-left-color:var(--orange)}.decision44.bad{border-left-color:var(--red)}
  .decision-head44{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.decision-label44{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.055em}.decision-title44{font-size:25px;font-weight:850;margin-top:4px}.decision-sub44{color:var(--muted);margin-top:4px}.signal-grid44{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:12px}.signal44{border:1px solid var(--line);background:rgba(255,255,255,.025);border-radius:12px;padding:10px}.signal44 small{display:block;color:var(--muted);font-size:10px}.signal44 strong{display:block;margin-top:4px;font-size:14px}.reason44{display:flex;gap:9px;align-items:flex-start;border-top:1px solid var(--line);padding:9px 0}.reason44:first-child{border-top:0}.reason-icon44{width:26px;height:26px;border-radius:8px;display:grid;place-items:center;background:var(--panel2);flex:0 0 auto}.reason44 small{display:block;color:var(--muted);margin-top:2px}
  .market44 svg{width:100%;height:180px;display:block;margin-top:10px}.market-line44{fill:none;stroke:var(--blue);stroke-width:3;vector-effect:non-scaling-stroke}.market-area44{fill:rgba(91,156,246,.09)}.market-axis44{stroke:var(--line);stroke-width:1}.market-kpis44{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:10px}.market-kpi44{padding:9px;border:1px solid var(--line);border-radius:11px}.market-kpi44 small{display:block;color:var(--muted);font-size:10px}.market-kpi44 strong{display:block;margin-top:3px;font-size:13px}.up44{color:var(--green)}.down44{color:var(--red)}
  .news44{display:grid;gap:8px}.news-event44{border:1px solid var(--line);border-radius:13px;padding:11px;background:rgba(255,255,255,.02)}.news-event44 .top44{display:flex;align-items:center;justify-content:space-between;gap:8px}.impact44{font-size:10px;border:1px solid var(--line);border-radius:999px;padding:3px 7px}.impact44.pos{color:var(--green);border-color:rgba(36,201,139,.35)}.impact44.neg{color:var(--red);border-color:rgba(226,106,106,.35)}.impact44.neu{color:var(--blue);border-color:rgba(91,156,246,.35)}.news-event44 h4{margin:7px 0 4px;font-size:14px;line-height:1.35}.news-meta44{font-size:10px;color:var(--muted)}.news-impact44{font-size:12px;margin-top:7px;color:var(--muted)}
  .priority-strip44{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;margin:10px 0}.priority44{border:1px solid var(--line);border-radius:10px;padding:8px;text-align:center}.priority44 b{display:block;font-size:16px}.priority44 small{color:var(--muted);font-size:9px}.p-red44{border-color:rgba(226,106,106,.32)}.p-orange44{border-color:rgba(231,168,71,.32)}.p-blue44{border-color:rgba(91,156,246,.32)}.p-green44{border-color:rgba(36,201,139,.32)}
  @media(min-width:760px){.signal-grid44,.market-kpis44{grid-template-columns:repeat(4,minmax(0,1fr))}}
  `;document.head.appendChild(s);
}
function esc44(v){return typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmt44(v,d=1){return Number(v).toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d});}
function eur44(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));}
function norm44(v){return String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');}
async function json44(url){const r=await fetch(`${url}${url.includes('?')?'&':'?'}v=44`,{cache:'no-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
async function loadSummary44(){if(marketSummary44)return marketSummary44;try{marketSummary44=await json44(MARKET_SUM44)}catch{marketSummary44={assetIndex:{},assets:{}}}return marketSummary44;}
async function loadNews44(){if(newsFeed44)return newsFeed44;try{newsFeed44=await json44(NEWS_FEED44)}catch{newsFeed44={assetIndex:{},items:[]}}return newsFeed44;}
function marketKey44(asset){if(!marketSummary44||!asset)return null;const isin=norm44(asset.isin),ticker=norm44(asset.ticker);for(const[k,m]of Object.entries(marketSummary44.assetIndex||{})){if(isin&&norm44(m.isin)===isin)return k;if(ticker&&([m.symbol,...(m.aliases||[])].some(x=>norm44(x)===ticker)))return k;}return null;}
async function marketFile44(key){if(!key)return null;if(marketFiles44.has(key))return marketFiles44.get(key);try{const x=await json44(`${MARKET_DIR44}${encodeURIComponent(key)}.json`);marketFiles44.set(key,x);return x}catch{marketFiles44.set(key,null);return null}}
function firstBefore44(rows,ms){if(!rows?.length)return null;for(let i=rows.length-1;i>=0;i--){if(rows[i][0]*1000<=ms)return Number(rows[i][1]);}return Number(rows[0][1]);}
function perf44(rows,days){if(!rows?.length)return null;const last=Number(rows.at(-1)?.[1]);const target=Date.now()-days*DAY,base=firstBefore44(rows,target);return base>0?(last/base-1)*100:null;}
function marketStats44(file){const rows=(file?.daily||[]).filter(x=>Number.isFinite(Number(x?.[1])));if(!rows.length)return null;const last=Number(rows.at(-1)[1]),year=rows.filter(x=>x[0]*1000>=Date.now()-365*DAY).map(x=>Number(x[1]));const high=Math.max(...(year.length?year:[last])),low=Math.min(...(year.length?year:[last]));return{last,p1m:perf44(rows,30),p3m:perf44(rows,90),p1y:perf44(rows,365),high52:high,low52:low,drawdown:high>0?(last/high-1)*100:0,rows};}
function localHolding44(asset){try{const p=window.HPOSLocalProjection433?.();return p?.holdings?.find(h=>norm44(h.isin)===norm44(asset.isin))||null}catch{return null}}
function halal44(asset){try{return typeof getEffectiveHalal==='function'?getEffectiveHalal(state,asset):{status:'UNKNOWN',reason:'Keine Halal-Engine verfügbar.'}}catch{return{status:'UNKNOWN',reason:'Halal-Status konnte nicht berechnet werden.'}}}
function assetAlerts44(asset){try{return (alerts||[]).filter(a=>a.assetId===asset.assetId||norm44(a.isin)===norm44(asset.isin))}catch{return[]}}
function classifyAlert44(a){const s=String(a?.severity||a?.level||a?.status||'').toUpperCase();if(/CRITICAL|ERROR|H0|VETO/.test(s))return'red';if(/WARN|H2|FREEZE|REVIEW/.test(s))return'orange';return'blue';}
function assetNewsKey44(feed,asset){const isin=norm44(asset.isin),ticker=norm44(asset.ticker),name=norm44(asset.name);for(const[k,m]of Object.entries(feed.assetIndex||{})){if(isin&&norm44(m.isin)===isin)return k;if(ticker&&norm44(m.ticker)===ticker)return k;if(name&&norm44(m.name)===name)return k;}return null;}
function tokens44(title){const stop=new Set(['THE','AND','FOR','WITH','FROM','THAT','THIS','UND','DER','DIE','DAS','MIT','VON','FÜR','EIN','EINE','AKTIE','NEWS']);return new Set(norm44(title).match(/[A-Z0-9]{3,}/g)?.filter(x=>!stop.has(x))||[]);}
function similar44(a,b){const A=tokens44(a),B=tokens44(b);if(!A.size||!B.size)return false;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.min(A.size,B.size)>=.55;}
function newsImpact44(title){const t=String(title||'').toLowerCase();const neg=['recall','warn','warning','cuts','cut ','lawsuit','investigation','probe','misses','downgrade','decline','falls','minus','verlust','senkt','rückruf','klage','ermittlung'];const pos=['approves','approval','beats','raises','raised','growth','record','contract','wins','dividend','genehmigt','zulassung','steigert','wachstum','auftrag','übertrifft'];if(neg.some(x=>t.includes(x)))return{dir:'neg',label:'NEGATIV',text:'Kann Risiko, Ergebnis oder Bewertung belasten.'};if(pos.some(x=>t.includes(x)))return{dir:'pos',label:'POSITIV',text:'Kann Fundamentaldaten oder Erwartungsbild stützen.'};return{dir:'neu',label:'NEUTRAL',text:'Aktuell kein eindeutiger Entscheidungsimpuls aus der Überschrift.'};}
function newsEvents44(feed,asset){const key=assetNewsKey44(feed,asset);if(!key)return[];const now=Date.now();const rows=(feed.items||[]).filter(n=>n.assetKey===key&&n.publishedAt&&now-Date.parse(n.publishedAt)<=7*DAY).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt));const groups=[];for(const n of rows){let g=groups.find(x=>similar44(x[0].title,n.title));if(g)g.push(n);else groups.push([n]);}return groups.slice(0,3).map(g=>({lead:g[0],count:g.length,impact:newsImpact44(g[0].title)}));}
function decision44(asset,stats,events){const h=localHolding44(asset),hal=halal44(asset),aa=assetAlerts44(asset);let action='HALTEN',tone='good',score=0;const reasons=[];
  if(hal.status==='H0'){action='NICHT KAUFEN',tone='bad',score-=100;reasons.push(['⛔','Halal-Veto',hal.reason||'H0'])}
  else if(hal.status==='H2'){action='EINFRIEREN',tone='warn',score-=40;reasons.push(['⏸','Halal prüfen',hal.reason||'H2'])}
  else if(hal.status==='UNKNOWN'){action='PRÜFEN',tone='warn',score-=20;reasons.push(['☪','Halal ungeklärt','Vor Kauf oder Aufstockung verifizieren.'])}
  else reasons.push(['✓','Halal freigegeben','Belegter effektiver Status H1.']);
  const red=aa.filter(a=>classifyAlert44(a)==='red').length,orange=aa.filter(a=>classifyAlert44(a)==='orange').length;if(red){score-=30;reasons.push(['●',`${red} kritische Regelmeldung${red>1?'en':''}`,'Vor einer Aktion zuerst auflösen.'])}else if(orange){score-=10;reasons.push(['▲',`${orange} offene Warnung${orange>1?'en':''}`,'Regel-/Limitprüfung erforderlich.'])}
  if(stats){if(stats.p3m!=null&&stats.p3m>15){score-=5;reasons.push(['↗',`3M +${fmt44(stats.p3m)} %`,'Starker Lauf: Nachkauf nicht allein aus Momentum ableiten.'])}else if(stats.p3m!=null&&stats.p3m<-12){score+=4;reasons.push(['↘',`3M ${fmt44(stats.p3m)} %`,'Rückgang erkannt; nur zusammen mit Fundamentaldaten bewerten.'])}if(stats.drawdown<-15)reasons.push(['◒',`${fmt44(stats.drawdown)} % unter 52W-Hoch`,'Bewertungskontext verändert; kein automatisches Kaufsignal.']);}
  const neg=events.filter(e=>e.impact.dir==='neg').length,pos=events.filter(e=>e.impact.dir==='pos').length;if(neg>pos){score-=6;reasons.push(['📰','Newslage eher negativ',`${neg} relevantes negatives Ereignis in den letzten 7 Tagen.`])}else if(pos>neg&&pos){score+=3;reasons.push(['📰','Newslage eher positiv',`${pos} positives Ereignis in den letzten 7 Tagen.`])}
  if(action==='HALTEN'&&score<=-10){action='BEOBACHTEN';tone='warn'}
  return{action,tone,score,reasons:reasons.slice(0,4),holding:h,halal:hal,alerts:aa};}
function svg44(stats){if(!stats?.rows?.length)return'';const rows=stats.rows.slice(-260),vals=rows.map(x=>Number(x[1])),min=Math.min(...vals),max=Math.max(...vals),w=600,h=180,p=8,span=Math.max(.0001,max-min);const pts=vals.map((v,i)=>`${p+i/(vals.length-1)*(w-2*p)},${h-p-(v-min)/span*(h-2*p)}`).join(' ');return`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-label="Kursentwicklung"><line class="market-axis44" x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/><polyline class="market-line44" points="${pts}"/></svg>`;}
function marketCard44(asset,file,stats){if(!file||!stats)return`<div class="card market44"><h3>Kurs & Entwicklung</h3><div class="empty">Für diesen Wert liegt aktuell keine belastbare Marktzeitreihe vor.</div></div>`;const cur=Number(file.regularMarketPriceEur);return`<div class="card market44"><div class="top"><div><h3>Kurs & Entwicklung</h3><p>Historische Zeitreihe · keine Fantasiekurse</p></div><span class="badge info">${esc44(file.state||'DATA')}</span></div>${svg44(stats)}<div class="market-kpis44"><div class="market-kpi44"><small>Aktuell EUR</small><strong>${Number.isFinite(cur)?eur44(cur):'—'}</strong></div><div class="market-kpi44"><small>1 Monat</small><strong class="${stats.p1m>=0?'up44':'down44'}">${stats.p1m==null?'—':`${stats.p1m>=0?'+':''}${fmt44(stats.p1m)} %`}</strong></div><div class="market-kpi44"><small>3 Monate</small><strong class="${stats.p3m>=0?'up44':'down44'}">${stats.p3m==null?'—':`${stats.p3m>=0?'+':''}${fmt44(stats.p3m)} %`}</strong></div><div class="market-kpi44"><small>1 Jahr</small><strong class="${stats.p1y>=0?'up44':'down44'}">${stats.p1y==null?'—':`${stats.p1y>=0?'+':''}${fmt44(stats.p1y)} %`}</strong></div><div class="market-kpi44"><small>52W Hoch</small><strong>${fmt44(stats.high52,2)} ${esc44(file.currency||'')}</strong></div><div class="market-kpi44"><small>Abstand Hoch</small><strong class="${stats.drawdown<-10?'down44':''}">${fmt44(stats.drawdown)} %</strong></div></div><div class="rule-source">Markt: ${esc44(file.provider||'')} · Stand ${esc44(String(file.asOf||'').replace('T',' ').slice(0,16))} · Performance in Handelswährung.</div></div>`;}
function newsCard44(events){return`<div class="card"><div class="top"><div><h3>Entscheidungsrelevante News</h3><p>Max. 3 Ereignisse · letzte 7 Tage · ähnliche Meldungen gebündelt</p></div><span class="badge info">${events.length}</span></div><div class="news44">${events.length?events.map(e=>`<div class="news-event44"><div class="top44"><span class="impact44 ${e.impact.dir}">${e.impact.label}</span><span class="news-meta44">${e.count>1?`${e.count} Meldungen · `:''}${esc44(e.lead.sourceTier||'')}</span></div><h4>${esc44(e.lead.title)}</h4><div class="news-meta44">${esc44(e.lead.source||'Quelle')} · ${new Date(e.lead.publishedAt).toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</div><div class="news-impact44"><strong>HPOS-Einordnung:</strong> ${esc44(e.impact.text)}</div></div>`).join(''):'<div class="empty">Keine aktuellen entscheidungsrelevanten Meldungen im 7-Tage-Fenster.</div>'}</div><div class="rule-source">Einordnung ist regelbasiert aus Titel/Quelle, keine Fundamentalanalyse und keine automatische Handelsfreigabe.</div></div>`;}
function decisionCard44(d,stats,events){const h=d.holding;const weight=(()=>{try{const p=window.HPOSLocalProjection433?.();const total=Number(p?.kpis?.importedPortfolioTotal||0);return h&&total>0?h.currentValue/total*100:null}catch{return null}})();return`<div class="card decision44 ${d.tone}"><div class="decision-head44"><div><div class="decision-label44">HPOS Entscheidungslage</div><div class="decision-title44">${esc44(d.action)}</div><div class="decision-sub44">Deterministisch aus verfügbaren Daten, keine KI-Freigabe.</div></div><span class="badge ${d.tone==='good'?'good':d.tone==='bad'?'bad':'warn'}">Daten ${stats?'MARKT ✓':'MARKT ?'}</span></div><div class="signal-grid44"><div class="signal44"><small>Depotgewicht</small><strong>${weight==null?'—':`${fmt44(weight)} %`}</strong></div><div class="signal44"><small>Seit Einstand</small><strong class="${Number(h?.unrealizedReturnNet)>=0?'up44':'down44'}">${h?`${Number(h.unrealizedReturnNet)>=0?'+':''}${fmt44(h.unrealizedReturnNet)} %`:'—'}</strong></div><div class="signal44"><small>Halal</small><strong>${esc44(d.halal.status||'UNKNOWN')}</strong></div><div class="signal44"><small>News 7T</small><strong>${events.length} Ereignis${events.length===1?'':'se'}</strong></div></div><div style="margin-top:11px">${d.reasons.map(r=>`<div class="reason44"><div class="reason-icon44">${r[0]}</div><div><strong>${esc44(r[1])}</strong><small>${esc44(r[2])}</small></div></div>`).join('')}</div></div>`;}
async function bundle44(asset){await Promise.all([loadSummary44(),loadNews44()]);const key=marketKey44(asset),file=await marketFile44(key),stats=marketStats44(file),events=newsEvents44(newsFeed44,asset),decision=decision44(asset,stats,events);return{file,stats,events,decision};}
function suppressLegacyMissingChart44(root){for(const c of root.querySelectorAll('.card')){if(/Kursverlauf nicht verfügbar/i.test(c.textContent||''))c.style.display='none';}}
async function hydrateAsset44(assetId){const host=document.getElementById('assetDecision44');if(!host||host.dataset.assetId!==assetId)return;const asset=(state.assets||[]).find(a=>a.assetId===assetId);if(!asset)return;try{const b=await bundle44(asset);if(!document.getElementById('assetDecision44')||document.getElementById('assetDecision44').dataset.assetId!==assetId)return;host.innerHTML=decisionCard44(b.decision,b.stats,b.events)+marketCard44(asset,b.file,b.stats)+newsCard44(b.events);suppressLegacyMissingChart44(document.getElementById('main'));}catch(e){host.innerHTML=`<div class="notice warn">Decision Engine konnte nicht vollständig laden: ${esc44(e.message)}</div>`;}}

const baseTab44=typeof renderAssetTab==='function'?renderAssetTab:null;
if(baseTab44){renderAssetTab=function(v,tab){const html=baseTab44(v,tab);if(!v?.asset||!['overview','analysis','news'].includes(tab))return html;const id=esc44(v.asset.assetId);setTimeout(()=>hydrateAsset44(v.asset.assetId),0);if(tab==='analysis')return`<div id="assetDecision44" data-asset-id="${id}" class="stack"><div class="card"><p>Decision Engine lädt Markt, Halal, Regeln und aktuelle News …</p></div></div>`;if(tab==='news')return`<div id="assetDecision44" data-asset-id="${id}" class="stack"><div class="card"><p>Aktuelle entscheidungsrelevante News werden verdichtet …</p></div></div>`;return`<div id="assetDecision44" data-asset-id="${id}" class="stack"><div class="card"><p>Decision Engine lädt …</p></div></div>${html}`;};}

function prioritySummary44(){const list=(()=>{try{return alerts||[]}catch{return[]}})(),r=list.filter(a=>classifyAlert44(a)==='red').length,o=list.filter(a=>classifyAlert44(a)==='orange').length,b=Math.max(0,list.length-r-o);return`<div class="priority-strip44"><div class="priority44 p-red44"><b>${r}</b><small>Handeln</small></div><div class="priority44 p-orange44"><b>${o}</b><small>Prüfen</small></div><div class="priority44 p-blue44"><b>${b}</b><small>Beobachten</small></div><div class="priority44 p-green44"><b>✓</b><small>System</small></div></div>`;}
function enhanceAnalysis44(){if(typeof currentPage==='undefined'||currentPage!=='analysis')return;const main=document.getElementById('main');if(!main||main.querySelector('#priority44'))return;const first=main.querySelector('.section-head');if(!first)return;const el=document.createElement('div');el.id='priority44';el.innerHTML=`<div class="card"><div class="top"><div><h3>Entscheidungsübersicht</h3><p>Hinweise nach Handlungsdruck statt Textmenge</p></div><span class="badge info">Alpha 4.4</span></div>${prioritySummary44()}<div class="rule-source">Rot = Handlungs-/Veto-Thema · Orange = prüfen · Blau = beobachten. Detailkarten bleiben darunter nachvollziehbar.</div></div>`;first.insertAdjacentElement('afterend',el);}
const obs44=new MutationObserver(()=>{clearTimeout(window.__hpos44t);window.__hpos44t=setTimeout(enhanceAnalysis44,20)});const main44=document.getElementById('main');if(main44)obs44.observe(main44,{childList:true,subtree:false});
css44();setTimeout(enhanceAnalysis44,50);
window.HPOSDecision44={bundle:bundle44,marketStats:marketStats44,newsEvents:newsEvents44,decision:decision44};
})();
