/* HPOS Alpha 4.3.1 – Usability & Information Depth
   Ergänzt Interaktionen und Drilldowns ohne bestehende 4.3-Datenlogik zu duplizieren.
   Zeitraumwerte sind klar als gewichtete Kursentwicklung des aktuellen Bestands gekennzeichnet,
   solange keine vollständige historische Depot-Zeitreihe aus allen Parqet-Aktivitäten persistiert ist. */
(() => {
'use strict';
const SNAP431='../data/portfolio/parqet_snapshot.json';
const MARKET_SUM431='../data/market/market_summary.json';
const VERSION431='1.3.0-alpha.4.3.1';
let pq431=null,market431=null;
const marketFiles431=new Map();

function ui431(){state.userProfile.ui=state.userProfile.ui||{};state.userProfile.ui.alpha431=state.userProfile.ui.alpha431||{period:'Aktuell',newsScope:'ALL'};return state.userProfile.ui.alpha431;}
function account431(){return state.userProfile.ui?.alpha43?.account||'ALL';}
function label431(){return {ALL:'Gesamtdepot',SCALABLE:'Scalable Capital',TRADE_REPUBLIC:'Trade Republic',WATCHLIST:'Watchlist'}[account431()]||'Gesamtdepot';}
function fmt431(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));}
function pct431(v,d=1){return `${Number(v||0).toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d})} %`;}
function norm431(v){return String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');}
function asset431(isin){return state.assets.find(a=>String(a.isin||'').toUpperCase()===String(isin||'').toUpperCase())||null;}
function holdings431(acct=account431()){if(!pq431||acct==='WATCHLIST')return[];return (pq431.holdings||[]).filter(h=>acct==='ALL'||h.broker===acct);}
function watch431(){const ids=new Set((state.watchlistEntries||[]).filter(w=>w.status!=='ARCHIVED').map(w=>w.assetId));return state.assets.filter(a=>ids.has(a.assetId)&&a.portfolioRole!=='HOLDING');}
function dividends431(acct=account431()){if(!pq431||acct==='WATCHLIST')return[];return (pq431.dividends||[]).filter(d=>acct==='ALL'||d.broker===acct);}
function brokerName431(b){return b==='TRADE_REPUBLIC'?'Trade Republic':'Scalable Capital';}

function css431(){if($('#alpha431css'))return;const s=document.createElement('style');s.id='alpha431css';s.textContent=`
.context431{display:flex;gap:7px;overflow-x:auto;scrollbar-width:none;margin:-2px 0 13px;padding:1px 0 2px}.context431::-webkit-scrollbar{display:none}.context431 button{white-space:nowrap;border:1px solid var(--line);background:rgba(255,255,255,.025);color:var(--muted);border-radius:999px;padding:7px 10px;font-size:11px}.context431 button.active{color:var(--green);border-color:rgba(56,217,150,.35);background:rgba(56,217,150,.07)}
.kpi43.click431,.analysis-card43.click431{cursor:pointer;transition:transform .12s ease,border-color .12s ease}.kpi43.click431:active,.analysis-card43.click431:active{transform:scale(.985)}.kpi43.click431:focus-visible,.analysis-card43.click431:focus-visible{outline:2px solid var(--blue);outline-offset:2px}.kpi43 .hint431{font-size:9px;color:var(--muted);margin-top:5px}
.periods43 button{cursor:pointer}.periods43 button:disabled{opacity:1;cursor:pointer}.period-note431{font-size:10px;color:var(--muted);margin-top:8px;line-height:1.35}.period-load431{opacity:.72}
.ring43{width:176px!important;height:176px!important}.ring-center43{inset:39px!important}.ring-center43 strong{font-size:17px!important;white-space:nowrap;letter-spacing:-.02em}.ring-center43 small{display:block!important;font-size:9px!important;margin-top:3px}.ring43 .seg1,.ring43 .seg2{pointer-events:stroke;cursor:pointer;transition:stroke-width .12s ease}.ring43 .seg1:hover,.ring43 .seg2:hover{stroke-width:21}
.broker431{display:inline-flex!important;align-items:center;gap:4px;font-weight:700}.broker431 i{width:16px;height:16px;border-radius:5px;display:grid;place-items:center;font-style:normal;font-size:7px;font-weight:900}.broker431.scalable{color:#78aaff;background:rgba(112,167,255,.10)}.broker431.scalable i{background:#467fdc;color:white}.broker431.tr{color:#51dfb4;background:rgba(56,217,150,.10)}.broker431.tr i{background:#19a77f;color:#041a13;border-radius:50%}
.movers431{display:grid;grid-template-columns:1fr 1fr;gap:9px}.mover-card431{padding:12px}.mover-card431 h3{font-size:14px;margin:0}.mover-card431.win{border-top:3px solid var(--green)}.mover-card431.lose{border-top:3px solid var(--red)}.mover-row431{width:100%;border:0;border-top:1px solid var(--line);background:transparent;color:var(--text);padding:9px 0;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;text-align:left}.mover-row431:first-of-type{border-top:0}.mover-row431 small{display:block;color:var(--muted);font-size:9px;margin-top:2px}.mover-row431 strong:last-child{font-size:12px}.mover-row431.win strong:last-child{color:var(--green)}.mover-row431.lose strong:last-child{color:var(--red)}
.goal431{padding:13px;margin-top:10px;cursor:pointer}.goal-head431{display:flex;justify-content:space-between;gap:10px}.goal-head431 small{display:block;color:var(--muted)}.goal-head431 strong{font-size:20px}.goal-bar431{height:9px;background:var(--line);border-radius:99px;overflow:hidden;margin-top:10px}.goal-bar431 span{display:block;height:100%;background:var(--green)}.goal-meta431{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:9px}.goal-meta431 div{border:1px solid var(--line);border-radius:10px;padding:8px}.goal-meta431 small{display:block;color:var(--muted);font-size:9px}.goal-meta431 strong{display:block;margin-top:3px;font-size:12px}
.scope431{display:flex;gap:6px;overflow-x:auto;margin:10px 0;scrollbar-width:none}.scope431::-webkit-scrollbar{display:none}.scope431 button{white-space:nowrap;border:1px solid var(--line);background:var(--panel);color:var(--muted);padding:7px 10px;border-radius:999px;font-size:11px}.scope431 button.active{background:var(--green);border-color:var(--green);color:#062116;font-weight:750}.scope-count431{font-size:9px;opacity:.75;margin-left:3px}
.asset-facts431{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-bottom:11px}.asset-fact431{border:1px solid var(--line);background:var(--panel);border-radius:12px;padding:10px}.asset-fact431 small{display:block;color:var(--muted);font-size:10px}.asset-fact431 strong{display:block;margin-top:4px;font-size:14px}.asset-source431{border-left:3px solid var(--blue);padding:11px 12px;margin-bottom:11px}
.modal-list431{display:grid;gap:7px}.modal-row431{width:100%;border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:12px;padding:10px;text-align:left}.modal-row431 small{display:block;color:var(--muted);margin-top:3px}
@media(max-width:380px){.movers431{grid-template-columns:1fr}.goal-meta431{grid-template-columns:1fr 1fr}.ring43{width:160px!important;height:160px!important}.ring-center43 strong{font-size:15px!important}}
`;document.head.appendChild(s);}

async function loadPQ431(){if(pq431)return pq431;try{const r=await fetch(`${SNAP431}?v=431`,{cache:'no-cache'});if(!r.ok)throw new Error();pq431=await r.json();return pq431}catch{return null}}
async function loadMarketSummary431(){if(market431)return market431;try{const r=await fetch(`${MARKET_SUM431}?v=431`,{cache:'no-cache'});if(!r.ok)throw new Error();market431=await r.json();return market431}catch{return null}}
function marketKey431(isin){if(!market431)return null;const target=norm431(isin);for(const[k,m]of Object.entries(market431.assetIndex||{})){if(norm431(m.isin)===target)return k;}return null;}
async function marketFile431(key){if(!key)return null;if(marketFiles431.has(key))return marketFiles431.get(key);try{const r=await fetch(`../data/market/${encodeURIComponent(key)}.json?v=431`,{cache:'no-cache'});if(!r.ok)throw new Error();const x=await r.json();marketFiles431.set(key,x);return x}catch{marketFiles431.set(key,null);return null}}

function makeClick431(el,handler,label){if(!el)return;el.classList.add('click431');el.tabIndex=0;el.setAttribute('role','button');if(label)el.setAttribute('aria-label',label);el.onclick=handler;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();handler();}};}
function scrollHeading431(text){const h=[...$('#main').querySelectorAll('h2,h3')].find(x=>x.textContent.toLowerCase().includes(text.toLowerCase()));h?.scrollIntoView({behavior:'smooth',block:'start'});}

function contextItems431(){
  const p=currentPage;
  if(p==='dashboard')return[['Übersicht',()=>window.scrollTo({top:0,behavior:'smooth'}),true],['Depots',()=>scrollHeading431('Depotverteilung')],['Mover',()=>scrollHeading431('Top Mover')],['Daten',()=>scrollHeading431('Datenqualität')]];
  if(p==='portfolio')return[['Bestände',()=>window.scrollTo({top:0,behavior:'smooth'}),true],['Mover',()=>showMoversModal431()],['Journal',()=>route('transactions')],['Watchlist',()=>{state.userProfile.ui.alpha43.account='WATCHLIST';persist();route('portfolio');}]];
  if(p==='income')return[['Übersicht',()=>window.scrollTo({top:0,behavior:'smooth'}),true],['Monate',()=>scrollHeading431('Monatsentwicklung')],['Ausschüttungen',()=>scrollHeading431('Ausschüttungen')],['Ziel',()=>openIncomeGoal431()]];
  if(p==='analysis')return[['Übersicht',()=>window.scrollTo({top:0,behavior:'smooth'}),true],['Halal',()=>route('halal')],['Risiken',()=>showAlerts431('ALL')],['Watchlist',()=>{state.userProfile.ui.alpha43.account='WATCHLIST';persist();route('portfolio');}],['Regeln',()=>route('strategy')]];
  if(p==='news')return[['Alle',()=>setNewsScope431('ALL'),ui431().newsScope==='ALL'],['Depot',()=>setNewsScope431('PORTFOLIO'),ui431().newsScope==='PORTFOLIO'],['Watchlist',()=>setNewsScope431('WATCHLIST'),ui431().newsScope==='WATCHLIST'],['Quellen',()=>$('#nsrc42')?.click()]];
  if(p==='asset')return[['‹ Depot',()=>route('portfolio')],['Übersicht',()=>setAssetTab431('overview'),currentAssetTab==='overview'],['Analyse',()=>setAssetTab431('analysis'),currentAssetTab==='analysis'],['Halal',()=>setAssetTab431('halal'),currentAssetTab==='halal'],['News',()=>setAssetTab431('news'),currentAssetTab==='news'],['Aktivitäten',()=>setAssetTab431('activities'),currentAssetTab==='activities']];
  if(p==='transactions')return[['‹ Depot',()=>route('portfolio')],['Journal',()=>window.scrollTo({top:0,behavior:'smooth'}),true]];
  if(p==='watchlist')return[['‹ Analyse',()=>route('analysis')],['Watchlist',()=>window.scrollTo({top:0,behavior:'smooth'}),true],['News',()=>{route('news');setTimeout(()=>setNewsScope431('WATCHLIST'),100);}]];
  if(p==='halal')return[['‹ Analyse',()=>route('analysis')],['Halal Register',()=>window.scrollTo({top:0,behavior:'smooth'}),true],['Offen',()=>showHalal431(['UNKNOWN'])],['H2/H0',()=>showHalal431(['H2','H0'])]];
  if(['strategy','data','diagnostics','settings'].includes(p))return[['‹ Home',()=>route('dashboard')],['Einstellungen',()=>route('settings'),p==='settings'],['Strategie',()=>route('strategy'),p==='strategy'],['Daten',()=>route('data'),p==='data'],['Diagnose',()=>route('diagnostics'),p==='diagnostics']];
  return[];
}
function injectContext431(){const main=$('#main');if(!main)return;$('#context431')?.remove();const items=contextItems431();if(!items.length)return;const nav=document.createElement('nav');nav.id='context431';nav.className='context431';nav.setAttribute('aria-label','Bereichsnavigation');nav.innerHTML=items.map((x,i)=>`<button class="${x[2]?'active':''}" data-c431="${i}">${esc(x[0])}</button>`).join('');main.prepend(nav);$$('[data-c431]',nav).forEach(b=>b.onclick=items[Number(b.dataset.c431)][1]);}
function setAssetTab431(tab){currentAssetTab=tab;renderAssetDetail();window.scrollTo({top:0,behavior:'smooth'});}

function fixBrokerLabels431(root=document){$$('.broker43',root).forEach(x=>{const tr=/Trade Republic/i.test(x.textContent);x.classList.add('broker431',tr?'tr':'scalable');x.innerHTML=`<i>${tr?'TR':'S'}</i>${tr?'Trade Republic':'Scalable'}`;});}
function fixRing431(){const ring=$('.ring43');if(!ring||!pq431)return;const total=Number(pq431.kpis?.importedPortfolioTotal||0),center=$('.ring-center43',ring);if(center)center.innerHTML=`<div><strong>${Math.round(total).toLocaleString('de-DE')} €</strong><small>Gesamtdepot</small></div>`;const s1=$('.seg1',ring),s2=$('.seg2',ring);if(s1)s1.onclick=()=>{state.userProfile.ui.alpha43.account='SCALABLE';persist();route('dashboard');};if(s2)s2.onclick=()=>{state.userProfile.ui.alpha43.account='TRADE_REPUBLIC';persist();route('dashboard');};fixBrokerLabels431(ring.parentElement||document);}

function movers431(acct=account431()){const hs=holdings431(acct==='WATCHLIST'?'ALL':acct).slice();const winners=hs.filter(h=>Number(h.unrealizedReturnNet)>=0).sort((a,b)=>Number(b.unrealizedReturnNet)-Number(a.unrealizedReturnNet)).slice(0,3);const losers=hs.filter(h=>Number(h.unrealizedReturnNet)<0).sort((a,b)=>Number(a.unrealizedReturnNet)-Number(b.unrealizedReturnNet)).slice(0,3);return{winners,losers};}
function moverRows431(rows,kind){if(!rows.length)return'<div class="empty" style="padding:10px 0">Keine Position.</div>';return rows.map(h=>{const a=asset431(h.isin);return`<button class="mover-row431 ${kind}" data-mover431="${esc(a?.assetId||'')}"><span><strong>${kind==='win'?'▲':'▼'} ${esc(h.name)}</strong><small>${fmt431(h.currentValue)}</small></span><strong>${Number(h.unrealizedReturnNet)>=0?'+':''}${pct431(h.unrealizedReturnNet,1)}</strong></button>`;}).join('');}
function moversBlock431(){const m=movers431();return`<div class="section-head"><div><h2>Top Mover</h2><p>Seit Einstand · gewählte Depotansicht</p></div></div><div class="movers431"><div class="card mover-card431 win"><h3>▲ Gewinner</h3>${moverRows431(m.winners,'win')}</div><div class="card mover-card431 lose"><h3>▼ Verlierer</h3>${moverRows431(m.losers,'lose')}</div></div>`;}
function bindMovers431(root=document){$$('[data-mover431]',root).forEach(b=>{if(b.dataset.mover431)b.onclick=()=>openAsset(b.dataset.mover431);});}
function showMoversModal431(){const m=movers431();openModal('Top Mover · '+label431(),`<div class="movers431"><div class="card mover-card431 win"><h3>▲ Gewinner</h3>${moverRows431(m.winners,'win')}</div><div class="card mover-card431 lose"><h3>▼ Verlierer</h3>${moverRows431(m.losers,'lose')}</div></div>`);bindMovers431($('#modalBody')||document);}

async function periodReturn431(period){if(period==='Aktuell')return null;await loadMarketSummary431();const hs=holdings431(),cash=account431()==='ALL'||account431()==='SCALABLE'?Number(pq431?.cash?.filter(c=>account431()==='ALL'||c.broker===account431()).reduce((s,c)=>s+Number(c.value||0),0)||0):0,total=hs.reduce((s,h)=>s+Number(h.currentValue||0),0)+cash;if(!total)return{pct:null,covered:0,total:hs.length};const now=new Date(pq431?.generatedAt||Date.now());let cutoff;if(period==='7T')cutoff=new Date(now.getTime()-7*86400000);else if(period==='30T')cutoff=new Date(now.getTime()-30*86400000);else if(period==='1J')cutoff=new Date(now.getTime()-365*86400000);else if(period==='YTD')cutoff=new Date(Date.UTC(now.getUTCFullYear(),0,1));else cutoff=null;let weighted=0,covered=0;await Promise.all(hs.map(async h=>{const key=marketKey431(h.isin),d=await marketFile431(key);const pts=(d?.daily||[]).filter(p=>Array.isArray(p)&&Number.isFinite(Number(p[1])));if(pts.length<2)return;let use=pts;if(cutoff)use=pts.filter(p=>Number(p[0])*1000>=cutoff.getTime());if(use.length<2)return;const first=Number(use[0][1]),last=Number(use.at(-1)[1]);if(!first||!Number.isFinite(last))return;const r=last/first-1;weighted+=(Number(h.currentValue||0)/total)*r;covered++;}));return{pct:weighted*100,covered,total:hs.length};}
async function selectPeriod431(period){ui431().period=period;persist();const buttons=$$('.periods43 button');buttons.forEach(b=>b.classList.toggle('active',b.textContent.trim()===period));const gain=$('.hero-gain43'),note=$('.period-note431');if(period==='Aktuell'){const un=holdings431().reduce((s,h)=>s+Number(h.unrealizedGainNet||0),0),inv=holdings431().reduce((s,h)=>s+Number(h.purchaseValue||0),0),r=inv?un/inv*100:0;if(gain){gain.className=`hero-gain43 ${un>=0?'pos43':'neg43'}`;gain.textContent=`${un>=0?'+':''}${fmt431(un)} · ${un>=0?'+':''}${pct431(r,2)} unrealisiert`;}if(note)note.textContent='Aktuell = reale Parqet-Werte seit Einstand.';return;}if(gain){gain.classList.add('period-load431');gain.textContent='Zeitraum wird aus Kursreihen berechnet …';}const r=await periodReturn431(period);if(gain){gain.classList.remove('period-load431');gain.className=`hero-gain43 ${(r?.pct??0)>=0?'pos43':'neg43'}`;gain.textContent=r?.pct===null?'Keine ausreichende Kursreihe':`${r.pct>=0?'+':''}${pct431(r.pct,2)} · ${r.covered}/${r.total} Positionen abgedeckt`;}if(note)note.textContent=`${period}: gewichtete Kursentwicklung des aktuellen Bestands. Transaktionszeitpunkte und historische FX-Beiträge sind noch nicht rückgerechnet; daher kein IZF/TWR.`;}
function enablePeriods431(){const p=$('.periods43');if(!p)return;const labels=['Aktuell','7T','30T','1J','YTD','Max'];[...p.querySelectorAll('button')].forEach((b,i)=>{b.disabled=false;b.removeAttribute('title');b.textContent=labels[i]||b.textContent;b.onclick=()=>selectPeriod431(b.textContent.trim());});if(!$('.period-note431')){const n=document.createElement('div');n.className='period-note431';p.after(n);}selectPeriod431(ui431().period||'Aktuell');}

function clickHomeKpis431(){const ks=$$('.kpis43 .kpi43');if(!ks.length)return;const all=account431()==='ALL';const actions=all?[
 ()=>openModal('IZF / XIRR',`<div class="card"><h3>${pct431(pq431?.kpis?.xirrPct,2)}</h3><p>Interner Zinsfuß aus dem Parqet-Snapshot. Er berücksichtigt Zahlungszeitpunkte und ist nicht mit der einfachen Kursrendite identisch.</p></div>`),
 ()=>route('transactions'),()=>route('income'),()=>{state.userProfile.ui.alpha43.account='WATCHLIST';persist();route('portfolio');}
]:[()=>route('portfolio'),()=>{ui431().period='Aktuell';persist();route('portfolio');},()=>route('income'),()=>route('portfolio')];ks.slice(0,4).forEach((k,i)=>{k.insertAdjacentHTML('beforeend','<div class="hint431">Antippen für Details</div>');makeClick431(k,actions[i],k.querySelector('small')?.textContent||'Kennzahl');});}

function addMoversHome431(){if($('#moversHome431'))return;const heads=[...$('#main').querySelectorAll('.section-head')],h=heads.find(x=>x.textContent.includes('Größte Positionen'));if(!h)return;const card=h.nextElementSibling;if(!card)return;const wrap=document.createElement('div');wrap.id='moversHome431';wrap.innerHTML=moversBlock431();card.after(wrap);bindMovers431(wrap);}

function incomeGoal431(){const acct=account431()==='WATCHLIST'?'ALL':account431(),all=dividends431(acct),asOf=new Date(pq431?.generatedAt||Date.now()),cut=new Date(asOf.getTime()-365*86400000),ttm=all.filter(d=>new Date(`${d.date}T00:00:00`)>=cut).reduce((s,d)=>s+Number(d.net||0),0),monthly=ttm/12,goal=Number(snapshot.effectiveProfile.rules.dividendGoalNetMonthlyEur.effectiveValue||0),gap=Math.max(0,goal-monthly),progress=goal?Math.min(100,monthly/goal*100):0;return{ttm,monthly,goal,gap,progress};}
function goalBlock431(){const g=incomeGoal431();return`<div class="card goal431" id="incomeGoal431"><div class="goal-head431"><div><small>Aktuelle Income-Rate · TTM Ø / Monat</small><strong>${fmt431(g.monthly)}</strong></div><div style="text-align:right"><small>Ziel / Monat</small><strong>${fmt431(g.goal)}</strong></div></div><div class="goal-bar431"><span style="width:${g.progress}%"></span></div><div class="goal-meta431"><div><small>Fortschritt</small><strong>${pct431(g.progress,1)}</strong></div><div><small>Gap / Monat</small><strong>${fmt431(g.gap)}</strong></div><div><small>TTM netto</small><strong>${fmt431(g.ttm)}</strong></div></div></div>`;}
function openIncomeGoal431(){if(!pq431)return;const g=incomeGoal431();openModal('Income-Ziel · '+label431(),`<div class="card"><div class="details"><div class="kv"><span>Letzte 12 Monate netto</span><strong>${fmt431(g.ttm)}</strong></div><div class="kv"><span>TTM Ø / Monat</span><strong>${fmt431(g.monthly)}</strong></div><div class="kv"><span>HPOS Ziel / Monat</span><strong>${fmt431(g.goal)}</strong></div><div class="kv"><span>Gap / Monat</span><strong>${fmt431(g.gap)}</strong></div><div class="kv"><span>Zielgrad</span><strong>${pct431(g.progress,1)}</strong></div></div><p class="rule-source">TTM = tatsächlich verbuchte Netto-Dividenden der letzten 12 Monate / 12. Das ist eine belastbare Ist-Rate, keine Forward-Dividendenprognose.</p></div>`);}
function enhanceIncome431(){const ks=$$('.kpis43 .kpi43');if(ks.length>=4){const g=incomeGoal431();ks[3].innerHTML=`<small>Aktuell / Ziel Monat</small><strong>${fmt431(g.monthly)} / ${fmt431(g.goal)}</strong><div class="hint431">Gap ${fmt431(g.gap)}</div>`;const acts=[()=>scrollHeading431('Monatsentwicklung'),()=>scrollHeading431('Ausschüttungen'),()=>openIncomeGoal431(),()=>openIncomeGoal431()];ks.slice(0,4).forEach((k,i)=>makeClick431(k,acts[i],k.querySelector('small')?.textContent));}if(!$('#incomeGoal431')){const k=$('.kpis43');if(k)k.insertAdjacentHTML('afterend',goalBlock431());$('#incomeGoal431')?.addEventListener('click',openIncomeGoal431);}fixBrokerLabels431();}

function relevantAssetIds431(){if(account431()==='WATCHLIST')return new Set(watch431().map(a=>a.assetId));return new Set(holdings431().map(h=>asset431(h.isin)?.assetId).filter(Boolean));}
function alertRows431(sev='ALL'){const ids=relevantAssetIds431();return (alerts||[]).filter(a=>!['DONE','SNOOZED'].includes(a.status)&&(!a.assetId||ids.has(a.assetId))&&(sev==='ALL'||a.severity===sev));}
function showAlerts431(sev='ALL'){const rows=alertRows431(sev);openModal(sev==='CRITICAL'?'Kritische Hinweise':sev==='WARN'?'Zu prüfen':'Aktive Hinweise',`<div class="modal-list431">${rows.length?rows.map(a=>{const asset=a.assetId?state.assets.find(x=>x.assetId===a.assetId):null;return`<button class="modal-row431" ${asset?`data-alertasset431="${esc(asset.assetId)}"`:''}><strong>${esc(asset?.name||a.ruleId||'HPOS Hinweis')}</strong><small>${esc(a.reason||a.action||'')} · ${esc(a.severity||'')}</small></button>`;}).join(''):'<div class="card empty">Keine Hinweise in diesem Filter.</div>'}</div>`);$$('[data-alertasset431]').forEach(b=>b.onclick=()=>{closeModal();openAsset(b.dataset.alertasset431,'analysis');});}
function showHalal431(statuses){const ids=relevantAssetIds431(),rows=state.assets.filter(a=>ids.has(a.assetId)&&statuses.includes(getEffectiveHalal(state,a).status));openModal(`Halal · ${statuses.join(' / ')}`,`<div class="modal-list431">${rows.length?rows.map(a=>{const h=getEffectiveHalal(state,a);return`<button class="modal-row431" data-halalasset431="${esc(a.assetId)}"><strong>${esc(a.name)}</strong><small>${esc(h.status)} · ${esc(h.reason||'Prüfung erforderlich')}</small></button>`;}).join(''):'<div class="card empty">Keine Position in diesem Status.</div>'}</div>`);$$('[data-halalasset431]').forEach(b=>b.onclick=()=>{closeModal();openAsset(b.dataset.halalasset431,'halal');});}
function enhanceAnalysis431(){const cs=$$('.analysis-card43');cs.forEach(c=>{const t=c.querySelector('small')?.textContent||'';if(t==='Kritisch')makeClick431(c,()=>showAlerts431('CRITICAL'),'Kritische Hinweise öffnen');else if(t==='Prüfen')makeClick431(c,()=>showAlerts431('WARN'),'Prüfhinweise öffnen');else if(t.includes('Halal offen'))makeClick431(c,()=>showHalal431(['UNKNOWN']),'Offene Halal-Prüfungen öffnen');else if(t.includes('H2 / H0'))makeClick431(c,()=>showHalal431(['H2','H0']),'H2 und H0 öffnen');});}

function classifyNewsCard431(card){const ael=card.querySelector('[data-na42]');const a=ael?state.assets.find(x=>x.assetId===ael.dataset.na42):null;if(!a)return'OTHER';if(a.portfolioRole==='WATCHLIST')return'WATCHLIST';if(a.portfolioRole==='HOLDING')return a.broker==='TRADE_REPUBLIC'?'TRADE_REPUBLIC':'SCALABLE';return'OTHER';}
function applyNewsScope431(){const scope=ui431().newsScope||'ALL';$$('.news-card').forEach(c=>{const cls=classifyNewsCard431(c);c.dataset.scope431=cls;const portfolio=cls==='SCALABLE'||cls==='TRADE_REPUBLIC';const ok=scope==='ALL'||(scope==='PORTFOLIO'&&portfolio)||scope===cls;if(!ok)c.style.display='none';});$$('[data-scope431]').forEach(b=>b.classList.toggle('active',b.dataset.scope431===scope));}
function setNewsScope431(scope){ui431().newsScope=scope;persist();if(currentPage!=='news'){route('news');setTimeout(()=>setNewsScope431(scope),150);return;}applyNewsScope431();injectContext431();}
function enhanceNews431(){if($('#newsScope431')){applyNewsScope431();return;}const tier=$('.chips42');if(!tier)return;const cards=$$('.news-card'),count=x=>cards.filter(c=>{const k=classifyNewsCard431(c);return x==='PORTFOLIO'?(k==='SCALABLE'||k==='TRADE_REPUBLIC'):k===x;}).length;const div=document.createElement('div');div.id='newsScope431';div.className='scope431';div.innerHTML=`<button data-scope431="ALL">Alle <span class="scope-count431">${cards.length}</span></button><button data-scope431="PORTFOLIO">Mein Depot <span class="scope-count431">${count('PORTFOLIO')}</span></button><button data-scope431="SCALABLE">Scalable <span class="scope-count431">${count('SCALABLE')}</span></button><button data-scope431="TRADE_REPUBLIC">Trade Republic <span class="scope-count431">${count('TRADE_REPUBLIC')}</span></button><button data-scope431="WATCHLIST">Watchlist <span class="scope-count431">${count('WATCHLIST')}</span></button>`;tier.before(div);$$('[data-scope431]',div).forEach(b=>b.onclick=()=>setNewsScope431(b.dataset.scope431));for(const el of [...$$('[data-nf42]'),$('#nq42'),$('#ns42')].filter(Boolean))el.addEventListener(el.tagName==='INPUT'?'input':'change',()=>setTimeout(applyNewsScope431,0));const stack=$('#nst42');if(stack)new MutationObserver(()=>applyNewsScope431()).observe(stack,{childList:true,subtree:true});applyNewsScope431();}

function assetHolding431(a){return pq431?.holdings?.find(h=>String(h.isin).toUpperCase()===String(a?.isin||'').toUpperCase())||null;}
function assetDiv431(a){return (pq431?.dividends||[]).filter(d=>String(d.isin).toUpperCase()===String(a?.isin||'').toUpperCase()).reduce((s,d)=>s+Number(d.net||0),0);}
function prependAssetFacts431(){const body=$('#assetTabBody'),a=state.assets.find(x=>x.assetId===currentAssetId);if(!body||!a||$('#assetFacts431'))return;const h=assetHolding431(a);if(currentAssetTab==='analysis'&&h){const html=`<div id="assetFacts431"><div class="asset-facts431"><div class="asset-fact431"><small>Depot</small><strong>${esc(brokerName431(h.broker))}</strong></div><div class="asset-fact431"><small>Unrealisiert</small><strong class="${Number(h.unrealizedReturnNet)>=0?'pos43':'neg43'}">${Number(h.unrealizedReturnNet)>=0?'+':''}${pct431(h.unrealizedReturnNet,1)}</strong></div><div class="asset-fact431"><small>Realisiert netto</small><strong>${h.realizedGainNet===undefined?'—':fmt431(h.realizedGainNet)}</strong></div><div class="asset-fact431"><small>Dividenden netto</small><strong>${fmt431(assetDiv431(a))}</strong></div></div><div class="card asset-source431"><strong>Datenbasis</strong><p>Position und Performance: Parqet-Snapshot. Regeln: HPOS. Kursreihe: externer Marktadapter, falls für die ISIN verfügbar.</p></div></div>`;body.insertAdjacentHTML('afterbegin',html);}else if(currentAssetTab==='halal'){const eff=getEffectiveHalal(state,a),checks=(state.halalChecks||[]).filter(c=>c.assetId===a.assetId).sort((x,y)=>String(y.checkedAt).localeCompare(String(x.checkedAt))),last=checks[0];const html=`<div id="assetFacts431"><div class="asset-facts431"><div class="asset-fact431"><small>Effektiver Status</small><strong>${esc(eff.status)}</strong></div><div class="asset-fact431"><small>Dokumentierte Checks</small><strong>${checks.length}</strong></div><div class="asset-fact431"><small>Letzte Quelle</small><strong>${esc(last?.source||'—')}</strong></div><div class="asset-fact431"><small>Letzte Prüfung</small><strong>${esc(last?dateFmt(last.checkedAt):'—')}</strong></div></div><div class="card asset-source431"><strong>Automatische Vorprüfung</strong><p>Ohne belastbare Musaffa-/Zoya-/Muslim-Xchange-Schnittstelle bleibt die automatische Vorprüfung UNKNOWN. Manuelle Prüfungen mit Beleg härten den Status; H2/H0 bleiben restriktiv.</p></div></div>`;body.insertAdjacentHTML('afterbegin',html);}else if(currentAssetTab==='news'){const count=$$('.news-card',body).length;body.insertAdjacentHTML('afterbegin',`<div id="assetFacts431" class="card asset-source431"><strong>News-Abdeckung</strong><p>${count?`${count} Meldung${count===1?'':'en'} im geladenen Snapshot.`:'Im geladenen Snapshot ist aktuell keine zugeordnete Meldung vorhanden.'} Depot- und Watchlist-News können im Hauptbereich News getrennt gefiltert werden.</p></div>`);}}
function enhanceAsset431(){const a=state.assets.find(x=>x.assetId===currentAssetId);if(!a)return;fixBrokerLabels431();prependAssetFacts431();const empty=[...$$('.chart-empty42')].find(x=>/nicht verfügbar/i.test(x.textContent));if(empty&&!$('.asset-source431',empty.parentElement)){const n=document.createElement('div');n.className='rule-source';n.textContent='Kein Fantasiekurs: eine Kurve erscheint erst, wenn der Marktadapter eine belastbare Zeitreihe für diese ISIN liefert.';empty.after(n);}}

function upgradeDashboard431(){if(!pq431)return;fixRing431();fixBrokerLabels431();enablePeriods431();clickHomeKpis431();addMoversHome431();}
function upgradePortfolio431(){fixRing431();fixBrokerLabels431();const head=[...$('#main').querySelectorAll('.section-head')].find(x=>x.textContent.includes('Gesamtdepot')||x.textContent.includes('Scalable')||x.textContent.includes('Trade Republic'));if(head&&!$('#portfolioMovers431')){const b=document.createElement('button');b.id='portfolioMovers431';b.className='btn small';b.textContent='Top Mover';b.onclick=showMoversModal431;head.appendChild(b);}}

const baseDashboard431=renderDashboard;renderDashboard=function(){baseDashboard431();upgradeDashboard431();injectContext431();};
const basePortfolio431=renderPortfolio;renderPortfolio=function(){basePortfolio431();upgradePortfolio431();injectContext431();};
const baseIncome431=renderIncome;renderIncome=function(){baseIncome431();enhanceIncome431();injectContext431();};
const baseNews431=renderNews;renderNews=async function(){await baseNews431();enhanceNews431();injectContext431();};
const baseAsset431=renderAssetDetail;renderAssetDetail=function(){baseAsset431();setTimeout(()=>{enhanceAsset431();injectContext431();},0);};
const baseRoute431=route;route=function(page,push=true){baseRoute431(page,push);setTimeout(()=>{if(currentPage==='analysis')enhanceAnalysis431();if(currentPage==='news')enhanceNews431();fixBrokerLabels431();injectContext431();},0);};

css431();loadPQ431().then(()=>{state.appMeta.appVersion=VERSION431;setTimeout(()=>{if(currentPage==='dashboard')upgradeDashboard431();else if(currentPage==='portfolio')upgradePortfolio431();else if(currentPage==='income')enhanceIncome431();else if(currentPage==='analysis')enhanceAnalysis431();else if(currentPage==='news')enhanceNews431();else if(currentPage==='asset')enhanceAsset431();injectContext431();},80);});
document.title='HPOS Alpha 4.3.1 · Usability';
})();
