/* HPOS Alpha 4.3 – Real Portfolio & Multi-Depot
   Parqet snapshot -> echtes Depot, eigene Brokerzuordnung, Sub-Euro-Marker -> Watchlist.
   Local-first: bestehende Halal-Historie/Strategie bleibt erhalten; Demo-/Testbestand wird gesichert und ersetzt. */
(() => {
'use strict';
const SNAP43='../data/portfolio/parqet_snapshot.json';
const VERSION43='1.3.0-alpha.4.3';
const NAV43=[['dashboard','⌂','Home'],['portfolio','◫','Depot'],['income','€','Income'],['analysis','◎','Analyse'],['news','◉','News']];
const ACCOUNT_LABEL43={ALL:'Gesamtdepot',SCALABLE:'Scalable Capital',TRADE_REPUBLIC:'Trade Republic',WATCHLIST:'Watchlist'};
let pq43=null;

function ui43(){state.userProfile.ui=state.userProfile.ui||{};state.userProfile.ui.alpha43=state.userProfile.ui.alpha43||{account:'ALL',halal:'ALL',sort:'value',month:null};return state.userProfile.ui.alpha43;}
function account43(){return ui43().account||'ALL';}
function setAccount43(id){if(!ACCOUNT_LABEL43[id])id='ALL';ui43().account=id;persist();syncHeader43();const page=currentPage==='asset'?'portfolio':currentPage;route(page,false);}
function byIsin43(isin){return state.assets.find(a=>a.isin&&String(a.isin).toUpperCase()===String(isin||'').toUpperCase())||null;}
function importedAssetIds43(){const s=new Set();for(const h of pq43?.holdings||[]){const a=byIsin43(h.isin);if(a)s.add(a.assetId);}return s;}
function holdings43(acct=account43()){if(!pq43)return[];if(acct==='WATCHLIST')return[];return (pq43.holdings||[]).filter(h=>acct==='ALL'||h.broker===acct);}
function cash43(acct=account43()){if(!pq43||acct==='WATCHLIST'||acct==='TRADE_REPUBLIC')return 0;return (pq43.cash||[]).filter(c=>acct==='ALL'||c.broker===acct).reduce((s,c)=>s+Number(c.value||0),0);}
function total43(acct=account43()){return holdings43(acct).reduce((s,h)=>s+Number(h.currentValue||0),0)+cash43(acct);}
function purchase43(acct=account43()){return holdings43(acct).reduce((s,h)=>s+Number(h.purchaseValue||0),0);}
function unreal43(acct=account43()){return holdings43(acct).reduce((s,h)=>s+Number(h.unrealizedGainNet||0),0);}
function dividends43(acct=account43()){return (pq43?.dividends||[]).filter(d=>acct==='ALL'||(acct==='WATCHLIST'?false:d.broker===acct));}
function fmt43(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));}
function pct43(v,d=1){return `${Number(v||0).toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d})} %`;}
function dataAge43(){if(!pq43?.generatedAt)return'unbekannt';return dateFmt(pq43.generatedAt);}
function hstatus43(isin){const a=byIsin43(isin);return a?getEffectiveHalal(state,a):{status:'UNKNOWN',reason:'Kein HPOS-Asset'};}
function brokerLabel43(b){return b==='TRADE_REPUBLIC'?'Trade Republic':'Scalable';}
function roleClass43(s){return s==='H1'?'good':s==='H2'?'warn':s==='H0'?'bad':'info';}

function css43(){if($('#alpha43css'))return;const s=document.createElement('style');s.id='alpha43css';s.textContent=`
.alpha-banner{font-size:12px!important;letter-spacing:.035em!important;padding:6px 12px!important}.topbar{grid-template-columns:auto auto minmax(128px,1fr) auto!important;gap:8px!important;padding-left:12px!important;padding-right:12px!important}.topbar>.top-title,.topbar>.top-actions{display:none!important}.profile43,.gear43,.search43{width:46px;height:46px;border-radius:14px;border:1px solid var(--line);background:var(--panel);color:var(--text);display:grid;place-items:center}.profile43 svg,.gear43 svg,.search43 svg{width:23px;height:23px;stroke:currentColor;fill:none;stroke-width:1.8}.account-switch43{height:46px;border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:14px;padding:0 12px;display:flex;align-items:center;justify-content:center;gap:7px;min-width:0;font-weight:760}.account-switch43 span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.account-switch43 small{color:var(--muted);font-size:13px}.fab43{position:fixed;z-index:60;right:18px;bottom:calc(82px + env(safe-area-inset-bottom));width:54px;height:54px;border-radius:50%;border:0;background:var(--green);color:#072016;font-size:31px;box-shadow:0 10px 30px rgba(0,0,0,.35)}
.bottom43{position:fixed;z-index:50;left:0;right:0;bottom:0;display:grid;grid-template-columns:repeat(5,1fr);padding:6px 6px calc(6px + env(safe-area-inset-bottom));background:rgba(7,12,19,.96);backdrop-filter:blur(20px);border-top:1px solid var(--line)}.bottom43 button{position:relative;border:0;background:transparent;color:var(--muted);min-height:55px;border-radius:14px;display:grid;place-items:center;gap:2px;font-size:11px}.bottom43 button i{font-style:normal;font-size:20px;line-height:1}.bottom43 button.active{background:rgba(56,217,150,.08);color:var(--green)}.main{padding-bottom:calc(104px + env(safe-area-inset-bottom))!important}
.hero43{padding:18px}.hero-value43{font-size:34px;font-weight:840;letter-spacing:-.03em}.hero-gain43{margin-top:5px;font-size:14px}.pos43{color:var(--green)}.neg43{color:var(--red)}.periods43{display:flex;gap:6px;overflow:auto;margin-top:13px}.periods43 button{border:0;background:var(--panel2);color:var(--muted);padding:8px 11px;border-radius:9px;white-space:nowrap}.periods43 .active{color:var(--text);background:rgba(112,167,255,.12)}
.kpis43{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:11px}.kpi43{border:1px solid var(--line);border-radius:14px;background:var(--panel);padding:12px}.kpi43 small{display:block;color:var(--muted);font-size:11px}.kpi43 strong{display:block;margin-top:5px;font-size:18px}.kpi43 .good{color:var(--green)}
.ring-card43{padding:15px;margin-top:11px}.ring43{width:190px;height:190px;margin:8px auto;position:relative}.ring43 svg{width:100%;height:100%;transform:rotate(-90deg)}.ring43 circle{fill:none;stroke-width:18}.ring43 .base{stroke:#1d2938}.ring43 .seg1{stroke:var(--blue)}.ring43 .seg2{stroke:var(--green)}.ring-center43{position:absolute;inset:34px;border-radius:50%;background:var(--panel);display:grid;place-items:center;text-align:center}.ring-center43 strong{font-size:21px}.ring-center43 small{color:var(--muted);font-size:10px}.account-legend43{display:grid;gap:6px}.account-legend43 button{border:0;border-top:1px solid var(--line);background:transparent;color:var(--text);padding:10px 0;display:grid;grid-template-columns:12px 1fr auto;gap:9px;align-items:center;text-align:left}.account-legend43 button:first-child{border-top:0}.dot43{width:10px;height:10px;border-radius:50%}
.depot-toolbar43{display:flex;gap:7px;overflow:auto;margin:10px 0}.chip43{white-space:nowrap;border:1px solid var(--line);background:var(--panel);color:var(--muted);border-radius:999px;padding:8px 11px}.chip43.active{background:var(--green);border-color:var(--green);color:#062116;font-weight:760}.select43,.input43{border:1px solid var(--line);background:#0c131d;color:var(--text);border-radius:11px;padding:10px}.depot-controls43{display:grid;grid-template-columns:1fr auto;gap:8px;margin-bottom:10px}.holding43{width:100%;border:0;border-top:1px solid var(--line);background:transparent;color:var(--text);padding:12px 2px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;text-align:left}.holding43:first-child{border-top:0}.holding43 small{display:block;color:var(--muted);font-size:11px;margin-top:3px}.holding43 .right{text-align:right}.holding43 .gain{font-size:11px;margin-top:3px}.badges43{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.broker43{font-size:9px;border-radius:999px;padding:3px 6px;background:rgba(112,167,255,.11);color:var(--blue)}
.watch43{display:grid;gap:8px}.watch-row43{border:1px solid var(--line);background:var(--panel);border-radius:13px;color:var(--text);padding:12px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px;text-align:left}.watch-row43 small{display:block;color:var(--muted);margin-top:4px}
.month-chart43{height:210px;display:flex;align-items:flex-end;gap:5px;padding-top:38px}.month43{flex:1;min-width:19px;height:100%;display:grid;grid-template-rows:1fr 22px;align-items:end}.month43 button{border:0;background:transparent;color:var(--muted);height:100%;padding:0;display:grid;grid-template-rows:1fr 22px;align-items:end}.bar43{width:100%;min-height:3px;background:var(--green);border-radius:5px 5px 2px 2px;opacity:.82}.month43.selected .bar43{background:var(--blue);opacity:1}.income-pill43{display:flex;justify-content:space-between;gap:10px;align-items:center;border:1px solid rgba(56,217,150,.25);background:rgba(56,217,150,.06);border-radius:12px;padding:10px 12px;margin-top:9px}.income-pill43 strong{font-size:18px}
.analysis-grid43{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.analysis-card43{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:12px}.analysis-card43 small{display:block;color:var(--muted)}.analysis-card43 strong{display:block;font-size:22px;margin-top:5px}.action43{width:100%;border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:13px;padding:12px;text-align:left;margin-top:8px}.action43 small{display:block;color:var(--muted);margin-top:4px}
.settings43{display:grid;gap:11px}.setting-group43{border:1px solid var(--line);background:var(--panel);border-radius:15px;overflow:hidden}.setting-title43{padding:11px 13px 7px;color:var(--muted);text-transform:uppercase;font-size:10px;letter-spacing:.06em}.setting-row43{width:100%;border:0;border-top:1px solid var(--line);background:transparent;color:var(--text);padding:13px;display:grid;grid-template-columns:32px minmax(0,1fr) auto;gap:10px;text-align:left;align-items:center}.setting-row43 small{display:block;color:var(--muted);margin-top:3px}.setting-row43:first-of-type{border-top:0}.sync43{font-size:11px;color:var(--muted);margin-top:8px}.source43{display:inline-flex;align-items:center;gap:5px;color:var(--muted);font-size:10px}
@media(min-width:760px){.kpis43{grid-template-columns:repeat(4,1fr)}.analysis-grid43{grid-template-columns:repeat(4,1fr)}}@media(min-width:1050px){.bottom43{display:none}.fab43{bottom:22px}.main{padding-bottom:50px!important}.topbar{max-width:1180px;margin:auto}}
`;document.head.appendChild(s);}

async function load43(){try{const r=await fetch(`${SNAP43}?v=4301`,{cache:'no-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const x=await r.json();if(!Array.isArray(x.holdings)||!Array.isArray(x.watchlist))throw new Error('Snapshot unvollständig');return x;}catch(e){console.error('HPOS43 Parqet snapshot',e);return null;}}
function assetClass43(name){if(/sukuk/i.test(name))return'SUKUK';if(/iShares|ETF|UCITS/i.test(name))return'ETF';return'EQUITY';}
function safeId43(isin){return`pq_${String(isin||uuid()).replace(/[^A-Za-z0-9]/g,'')}`;}
function isTest43(a){return /test aktie|testaktie|demo/i.test(String(a?.name||''))||String(a?.ticker||'').toUpperCase()==='TEST';}

function syncState43(data){
  if(!data)return false;
  const currentStamp=state.appMeta?.parqetImport?.generatedAt;
  if(currentStamp===data.generatedAt)return false;
  const raw=localStorage.getItem(STORAGE_KEY);
  if(raw&&!state.appMeta?.parqetImport){const bk=`hposPreParqetBackupV3_${new Date().toISOString().replace(/[:.]/g,'-')}`;try{localStorage.setItem(bk,raw);state.appMeta.preParqetBackupKey=bk;}catch{}}
  const oldAssets=[...(state.assets||[])],oldById=new Map(oldAssets.map(a=>[a.assetId,a])),oldByIsin=new Map(oldAssets.filter(a=>a.isin).map(a=>[String(a.isin).toUpperCase(),a]));
  const oldWatch=[...(state.watchlistEntries||[])],oldChecks=[...(state.halalChecks||[])],oldReviews=[...(state.reviews||[])],oldAlertState=[...(state.alertState||[])];
  const assets=[],idMap=new Map(),newByIsin=new Map();
  const add=(rec,role,extra={})=>{const key=String(rec.isin||'').toUpperCase();const old=oldByIsin.get(key);const a={...(old||{}),assetId:old?.assetId||safeId43(rec.isin),name:rec.name||old?.name||rec.isin,isin:rec.isin,assetClass:old?.assetClass&&old.assetClass!=='UNKNOWN'?old.assetClass:assetClass43(rec.name),currency:'EUR',portfolioRole:role,dataSource:'PARQET',...extra,createdAt:old?.createdAt||nowIso(),updatedAt:nowIso()};if(role==='HOLDING'){a.broker=rec.broker;a.sourceHoldingId=rec.holdingId;a.priceQuote={price:Number(rec.currentPrice),currency:'EUR',asOf:data.generatedAt,source:'Parqet Connector',kind:'IMPORTED_SNAPSHOT'};}else delete a.priceQuote;assets.push(a);newByIsin.set(key,a);if(old)idMap.set(old.assetId,a.assetId);return a;};
  for(const h of data.holdings)add(h,'HOLDING');
  for(const w of data.watchlist){if(newByIsin.has(String(w.isin).toUpperCase()))continue;add(w,'WATCHLIST',{broker:'WATCHLIST',watchSource:'PARQET_MARKER'});}
  const oldWatchAssetIds=new Set(oldWatch.filter(w=>w.status!=='ARCHIVED').map(w=>w.assetId));
  for(const oa of oldAssets){if(isTest43(oa)||idMap.has(oa.assetId)||oa.isin&&newByIsin.has(String(oa.isin).toUpperCase()))continue;if(oldWatchAssetIds.has(oa.assetId)||oldChecks.some(c=>c.assetId===oa.assetId)){const a={...oa,portfolioRole:'WATCHLIST',broker:'WATCHLIST',dataSource:oa.dataSource||'LOCAL',priceQuote:undefined,updatedAt:nowIso()};assets.push(a);idMap.set(oa.assetId,a.assetId);if(a.isin)newByIsin.set(String(a.isin).toUpperCase(),a);}}
  const resolveOld=id=>{const oa=oldById.get(id);if(!oa)return null;if(idMap.has(id))return idMap.get(id);if(oa.isin)return newByIsin.get(String(oa.isin).toUpperCase())?.assetId||null;return assets.find(a=>String(a.name).toLowerCase()===String(oa.name).toLowerCase())?.assetId||null;};
  const checks=oldChecks.filter(c=>{const oa=oldById.get(c.assetId);return !isTest43(oa);}).map(c=>{const id=resolveOld(c.assetId);return id?{...c,assetId:id}:null;}).filter(Boolean);
  const watchMap=new Map();
  for(const w of data.watchlist){const a=newByIsin.get(String(w.isin).toUpperCase());if(!a)continue;watchMap.set(a.assetId,{watchlistId:`pq_w_${w.isin}`,assetId:a.assetId,bucket:'C',thesis:'Parqet-Marker · Wert bewusst nicht als Depotbestand berücksichtigt.',entryTrigger:null,reviewDate:null,createdAt:data.generatedAt,status:'ACTIVE',source:'PARQET_MARKER'});}
  for(const ow of oldWatch){const id=resolveOld(ow.assetId);const oa=oldById.get(ow.assetId);if(!id||isTest43(oa))continue;if(!watchMap.has(id)||ow.source!=='PARQET_MARKER')watchMap.set(id,{...ow,assetId:id});}
  const tx=[];
  for(const h of data.holdings){const a=newByIsin.get(String(h.isin).toUpperCase());if(!a)continue;tx.push({transactionId:`pq_open_${h.isin}`,type:'OPENING_POSITION',date:h.earliestActivityDate||data.generatedAt.slice(0,10),createdAt:data.generatedAt,enteredBy:'parqet-snapshot',assetId:a.assetId,qty:Number(h.shares),price:Number(h.purchasePrice),useAsReference:false,externalSource:'PARQET',broker:h.broker});}
  for(const d of data.dividends||[]){const a=newByIsin.get(String(d.isin).toUpperCase());if(!a||a.portfolioRole!=='HOLDING')continue;tx.push({transactionId:`pq_div_${d.date}_${d.isin}`,type:'DIVIDEND',date:d.date,createdAt:data.generatedAt,enteredBy:'parqet-snapshot',assetId:a.assetId,amount:Number(d.net),grossAmount:Number(d.gross),tax:Number(d.tax||0),externalSource:'PARQET',broker:d.broker});}
  const reviews=oldReviews.map(r=>r.assetId?{...r,assetId:resolveOld(r.assetId)}:r).filter(r=>!r.assetId||assets.some(a=>a.assetId===r.assetId));
  const alertState=oldAlertState.map(a=>a.assetId?{...a,assetId:resolveOld(a.assetId)}:a).filter(a=>!a.assetId||assets.some(x=>x.assetId===a.assetId));
  state.assets=assets;state.transactions=tx;state.halalChecks=checks;state.watchlistEntries=[...watchMap.values()];state.reviews=reviews;state.alertState=alertState;
  state.userProfile.cashMode='OFF';
  state.dataStatus.portfolio={state:'CURRENT',source:'Parqet Connector Snapshot',asOf:data.generatedAt,lastAttemptAt:data.generatedAt,message:`Reales Depot importiert: ${data.holdings.length} Positionen; Sub-Euro-Marker als Watchlist ausgeschlossen.`};
  state.dataStatus.prices={state:'CURRENT',source:'Parqet Connector Snapshot',asOf:data.generatedAt,lastAttemptAt:data.generatedAt,message:'Importierte Depotpositionen enthalten bestätigte EUR-Kurse aus dem Parqet-Snapshot.'};
  state.appMeta.appVersion=VERSION43;state.appMeta.parqetImport={generatedAt:data.generatedAt,portfolioId:data.sourcePortfolio?.id,reconciliation:data.reconciliation,realHoldings:data.holdings.length,watchMarkers:data.watchlist.length,brokerRule:'Lokale Brokerzuordnung; nicht im öffentlichen Code gespeichert.'};
  state.diagnostics=(state.diagnostics||[]).filter(d=>!/TEST|DEMO/i.test(String(d.code||''))).concat([{at:nowIso(),code:'PARQET_REAL_PORTFOLIO_IMPORTED',severity:'INFO',message:`Parqet-Snapshot ${data.generatedAt}: ${data.holdings.length} reale Positionen, ${data.watchlist.length} Watchlist-Marker. Testbestand ersetzt.`}]);
  persist();return true;
}

function installHeader43(){
  const header=$('.topbar');if(!header)return;
  const profile=$('#menuBtn');profile.className='profile43';profile.setAttribute('aria-label','Profil');profile.innerHTML='<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"></circle><path d="M4.5 21c.8-5 3.2-7 7.5-7s6.7 2 7.5 7"></path></svg>';profile.onclick=openProfile43;
  let search=$('#globalSearch42');if(search){search.className='search43';search.innerHTML='<svg viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6.5"></circle><path d="m15.5 15.5 5 5"></path></svg>';header.insertBefore(search,$('.top-title'));}
  let sw=$('#accountSwitch43');if(!sw){sw=document.createElement('button');sw.id='accountSwitch43';sw.className='account-switch43';sw.onclick=openAccountSwitcher43;header.insertBefore(sw,$('.top-title'));}
  let gear=$('#gear43');if(!gear){gear=document.createElement('button');gear.id='gear43';gear.className='gear43';gear.setAttribute('aria-label','Einstellungen');gear.innerHTML='<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"></circle><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.5-2.5 1a7 7 0 0 0-1.8-1L14.3 3h-4.1L9.8 6a7 7 0 0 0-1.8 1L5.5 6 3.5 9.5l2 1.5a7 7 0 0 0 0 2L3.5 14.5l2 3.5L8 17a7 7 0 0 0 1.8 1l.4 3h4.1l.4-3a7 7 0 0 0 1.8-1l2.5 1 2-3.5-2-1.5a7 7 0 0 0 0-1Z"></path></svg>';gear.onclick=()=>route('settings');header.insertBefore(gear,$('.top-title'));}
  let fab=$('#fab43');if(!fab){fab=document.createElement('button');fab.id='fab43';fab.className='fab43';fab.setAttribute('aria-label','Neuer Eintrag');fab.textContent='+';fab.onclick=()=>openActionSheet(null,currentPage==='asset'?currentAssetId:null);document.body.appendChild(fab);}
  syncHeader43();
}
function syncHeader43(){const sw=$('#accountSwitch43');if(sw)sw.innerHTML=`<span>${esc(ACCOUNT_LABEL43[account43()]||'Gesamtdepot')}</span><small>⌄</small>`;}
function openAccountSwitcher43(){openModal('Ansicht wählen',`<div class="stack">${(pq43?.accounts||[]).map(a=>`<button class="action43" data-account43="${esc(a.id)}"><strong>${esc(a.name)}</strong><small>${a.id==='ALL'?'Scalable + Trade Republic':a.id==='WATCHLIST'?`${pq43.watchlist.length} Parqet-Marker + lokale Watchlist`:`${holdings43(a.id).length} reale Positionen · ${fmt43(total43(a.id))}`}</small></button>`).join('')}<button class="action43" id="addDepot43"><strong>＋ Depot hinzufügen</strong><small>Struktur ist vorbereitet; neue Datenquelle wird separat angebunden.</small></button></div>`);$$('[data-account43]').forEach(b=>b.onclick=()=>{closeModal();setAccount43(b.dataset.account43);});$('#addDepot43').onclick=()=>toast('Weitere Depots können über einen neuen Importadapter ergänzt werden.');}
function openProfile43(){const p=pq43;openModal('Profil & Datenquellen',`<div class="stack"><div class="card"><h3>HPOS Portfolio</h3><div class="details"><div class="kv"><span>Gesamtdepot</span><strong>${p?fmt43(p.kpis.importedPortfolioTotal):'—'}</strong></div><div class="kv"><span>Scalable</span><strong>${p?fmt43(p.kpis.scalableTotal):'—'}</strong></div><div class="kv"><span>Trade Republic</span><strong>${p?fmt43(p.kpis.tradeRepublicTotal):'—'}</strong></div><div class="kv"><span>Watchlist-Marker</span><strong>${p?.watchlist?.length??'—'}</strong></div></div></div><div class="card"><h3>Datenquelle</h3><p>Parqet Free Account wird nur als Read-only-Quelle genutzt. HPOS übernimmt Broker-Zuordnung, Filterung, Analyse und Halal-Logik selbst.</p><div class="rule-source">Snapshot ${esc(dataAge43())} · ${esc(p?.source||'unbekannt')}</div></div><button class="btn primary" id="profileSettings43">Einstellungen</button></div>`);$('#profileSettings43').onclick=()=>{closeModal();route('settings');};}

renderNav=function(){const p=currentPage==='radar'?'analysis':currentPage==='watchlist'?'analysis':currentPage==='halal'?'analysis':currentPage==='strategy'||currentPage==='data'||currentPage==='diagnostics'||currentPage==='settings'?'settings':currentPage;$('#nav').innerHTML=[...NAV43,['settings','⚙','Einstellungen']].map(([id,ic,l])=>`<button class="nav-btn ${p===id?'active':''}" data-r43="${id}"><span>${ic}</span><span>${l}</span></button>`).join('');$$('[data-r43]').forEach(b=>b.onclick=()=>route(b.dataset.r43));let nav=$('#bottom43');if(!nav){nav=document.createElement('nav');nav.id='bottom43';nav.className='bottom43';document.body.appendChild(nav);}nav.innerHTML=NAV43.map(([id,ic,l])=>`<button class="${p===id?'active':''}" data-b43="${id}"><i>${ic}</i><span>${l}</span></button>`).join('');$$('[data-b43]').forEach(b=>b.onclick=()=>route(b.dataset.b43));};
TITLES.analysis=['Analyse','HPOS Entscheidungen'];TITLES.settings=['Einstellungen','Regeln, Daten & Quellen'];TITLES.portfolio=['Depot','Bestände & Broker'];TITLES.dashboard=['Home','Portfolio Cockpit'];
const routeBase43=route;
route=function(page,push=true){if(page==='radar')page='analysis';if(page==='more')page='settings';if(page==='watchlist'&&account43()==='WATCHLIST')page='portfolio';if(!TITLES[page])page='dashboard';currentPage=page;if(push)history.replaceState(null,'',`#${page}`);const[t,s]=TITLES[page];$('#pageTitle').textContent=t;$('#pageSubtitle').textContent=s;closeDrawer();renderNav();const fn={dashboard:renderDashboard,portfolio:renderPortfolio,income:renderIncome,analysis:renderAnalysis43,news:renderNews,settings:renderSettings43,watchlist:renderWatchlist43,halal:renderHalal,strategy:renderStrategy,transactions:renderTransactions,data:renderData,diagnostics:renderDiagnostics,asset:renderAssetDetail}[page];(fn||renderDashboard)();$('#main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'auto'});syncHeader43();};

function accountRing43(){if(!pq43)return'';const sc=Number(pq43.kpis.scalableTotal||0),tr=Number(pq43.kpis.tradeRepublicTotal||0),tot=sc+tr||1,p1=sc/tot*100,p2=tr/tot*100,C=2*Math.PI*50;return `<div class="card ring-card43"><div class="top"><div><h3>Depotverteilung</h3><p>Segment auswählen oder Depot oben wechseln</p></div><span class="badge info">2 Depots</span></div><div class="ring43"><svg viewBox="0 0 120 120"><circle class="base" cx="60" cy="60" r="50"></circle><circle class="seg1" cx="60" cy="60" r="50" stroke-dasharray="${(C*p1/100).toFixed(2)} ${C.toFixed(2)}"></circle><circle class="seg2" cx="60" cy="60" r="50" stroke-dasharray="${(C*p2/100).toFixed(2)} ${C.toFixed(2)}" stroke-dashoffset="${(-C*p1/100).toFixed(2)}"></circle></svg><div class="ring-center43"><div><strong>${fmt43(tot)}</strong><small>Gesamtdepot</small></div></div></div><div class="account-legend43"><button data-ring-account="SCALABLE"><span class="dot43" style="background:var(--blue)"></span><span>Scalable Capital<small>${holdings43('SCALABLE').length} Positionen + Cash</small></span><strong>${pct43(p1)}</strong></button><button data-ring-account="TRADE_REPUBLIC"><span class="dot43" style="background:var(--green)"></span><span>Trade Republic<small>Cardinal Energy + Savaria</small></span><strong>${pct43(p2)}</strong></button></div></div>`;}
function topHoldings43(acct=account43(),n=5){return holdings43(acct).slice().sort((a,b)=>Number(b.currentValue)-Number(a.currentValue)).slice(0,n);}
function ytdDiv43(acct=account43()){const y=String(new Date().getFullYear());return dividends43(acct).filter(d=>String(d.date).startsWith(y)).reduce((s,d)=>s+Number(d.net||0),0);}

renderDashboard=function(){if(!pq43){$('#main').innerHTML='<div class="card empty">Parqet-Snapshot wird geladen …</div>';return;}if(account43()==='WATCHLIST'){renderWatchHome43();return;}const acct=account43(),tot=total43(acct),un=unreal43(acct),invest=purchase43(acct),ret=invest?un/invest*100:0,all=acct==='ALL',top=topHoldings43(acct);$('#main').innerHTML=`<div class="section-head"><div><h1>${esc(ACCOUNT_LABEL43[acct])}</h1><p>Reales Depot · Parqet Snapshot ${esc(dataAge43())}</p></div><button class="btn small" id="refreshRules43">HPOS prüfen</button></div><div class="card hero43"><small>Depotwert inkl. zugeordnetem Cash</small><div class="hero-value43">${fmt43(tot)}</div><div class="hero-gain43 ${un>=0?'pos43':'neg43'}">${un>=0?'+':''}${fmt43(un)} · ${un>=0?'+':''}${pct43(ret,2)} unrealisiert</div><div class="periods43"><button class="active">Aktuell</button><button disabled title="Historische Depotzeitreihe folgt mit Datenadapter">7T</button><button disabled>30T</button><button disabled>1J</button><button disabled>YTD</button><button disabled>Max</button></div></div><div class="kpis43">${all?`<div class="kpi43"><small>IZF / XIRR</small><strong class="good">${pct43(pq43.kpis.xirrPct,2)}</strong></div><div class="kpi43"><small>Realisierte Gewinne netto</small><strong>${fmt43(pq43.kpis.realizedGainNet)}</strong></div><div class="kpi43"><small>Dividenden netto gesamt</small><strong>${fmt43(pq43.kpis.dividendsNet)}</strong></div><div class="kpi43"><small>Watchlist-Marker</small><strong>${pq43.watchlist.length}</strong></div>`:`<div class="kpi43"><small>Einstand aktueller Bestand</small><strong>${fmt43(invest)}</strong></div><div class="kpi43"><small>Unrealisiert</small><strong class="${un>=0?'good':''}">${fmt43(un)}</strong></div><div class="kpi43"><small>Income YTD</small><strong>${fmt43(ytdDiv43(acct))}</strong></div><div class="kpi43"><small>Positionen</small><strong>${holdings43(acct).length}</strong></div>`}</div>${all?accountRing43():''}<div class="section-head"><div><h2>Größte Positionen</h2><p>Antippen öffnet die Investment-Akte</p></div></div><div class="card">${top.map(h=>holdingRow43(h,{compact:true})).join('')}</div><div class="section-head"><div><h2>Datenqualität</h2></div></div><div class="card"><div class="details"><div class="kv"><span>Reconciliation</span><strong>${esc(pq43.reconciliation.status)}</strong></div><div class="kv"><span>Parqet gemeldet</span><strong>${fmt43(pq43.kpis.parqetReportedTotal)}</strong></div><div class="kv"><span>Watchlist-Wert ausgeschlossen</span><strong>${fmt43(pq43.kpis.markerValueExcluded)}</strong></div><div class="kv"><span>Quelle</span><strong>Parqet Read-only</strong></div></div></div>`;$('#refreshRules43').onclick=()=>{recompute();toast('HPOS Regeln neu berechnet');renderDashboard();};$$('[data-ring-account]').forEach(b=>b.onclick=()=>setAccount43(b.dataset.ringAccount));bindHoldingRows43();};
function renderWatchHome43(){const ws=watchAssets43();const unknown=ws.filter(a=>getEffectiveHalal(state,a).status==='UNKNOWN').length;$('#main').innerHTML=`<div class="section-head"><div><h1>Watchlist</h1><p>Parqet-Marker dienen nur als Informationsanker, nicht als Depotwert</p></div></div><div class="kpis43"><div class="kpi43"><small>Kandidaten</small><strong>${ws.length}</strong></div><div class="kpi43"><small>Halal offen</small><strong>${unknown}</strong></div><div class="kpi43"><small>Depotwert</small><strong>0,00 €</strong></div><div class="kpi43"><small>Wertregel</small><strong>&lt; 1 € ignoriert</strong></div></div><button class="action43" id="openWatchList43"><strong>Watchlist öffnen</strong><small>Filtern, prüfen und einzelne Titel öffnen</small></button><button class="action43" id="watchNews43"><strong>News ansehen</strong><small>Discovery- und Primärquellen zu beobachteten Titeln</small></button>`;$('#openWatchList43').onclick=renderWatchlist43;$('#watchNews43').onclick=()=>route('news');}

function holdingRow43(h,{compact=false}={}){const a=byIsin43(h.isin),hs=hstatus43(h.isin),gain=Number(h.unrealizedGainNet||0);return `<button class="holding43" data-h43="${esc(a?.assetId||'')}"><div><strong>${esc(h.name)}</strong><small>${esc(h.isin)} · ${Number(h.shares).toLocaleString('de-DE',{maximumFractionDigits:6})} Stk.</small><div class="badges43"><span class="broker43">${esc(brokerLabel43(h.broker))}</span><span class="badge ${roleClass43(hs.status)}">${esc(hs.status)}</span></div></div><div class="right"><strong>${fmt43(h.currentValue)}</strong><div class="gain ${gain>=0?'pos43':'neg43'}">${gain>=0?'+':''}${fmt43(gain)} · ${h.unrealizedReturnNet>=0?'+':''}${pct43(h.unrealizedReturnNet,1)}</div>${compact?'':`<small>Ø ${fmt43(h.purchasePrice)}</small>`}</div></button>`;}
function bindHoldingRows43(){$$('[data-h43]').forEach(b=>{if(b.dataset.h43)b.onclick=()=>openAsset(b.dataset.h43);});}

renderPortfolio=function(){if(!pq43)return;const acct=account43();if(acct==='WATCHLIST'){renderWatchlist43();return;}const u=ui43();let hs=holdings43(acct).filter(h=>u.halal==='ALL'||hstatus43(h.isin).status===u.halal);const cmp={value:(a,b)=>b.currentValue-a.currentValue,performance:(a,b)=>Number(b.unrealizedReturnNet)-Number(a.unrealizedReturnNet),name:(a,b)=>a.name.localeCompare(b.name,'de')}[u.sort]||((a,b)=>b.currentValue-a.currentValue);hs=hs.slice().sort(cmp);$('#main').innerHTML=`<div class="section-head"><div><h1>${acct==='ALL'?'Gesamtdepot':esc(ACCOUNT_LABEL43[acct])}</h1><p>${holdings43(acct).length} reale Positionen · Watchlist ausgeschlossen</p></div><button class="btn small" id="tx43">Journal</button></div>${acct==='ALL'?accountRing43():''}<div class="depot-toolbar43">${['ALL','H1','H2','H0','UNKNOWN'].map(x=>`<button class="chip43 ${u.halal===x?'active':''}" data-half43="${x}">${x==='ALL'?'Alle':x==='UNKNOWN'?'Offen':x}</button>`).join('')}</div><div class="depot-controls43"><div></div><select class="select43" id="sort43"><option value="value" ${u.sort==='value'?'selected':''}>Wert</option><option value="performance" ${u.sort==='performance'?'selected':''}>Performance</option><option value="name" ${u.sort==='name'?'selected':''}>Name</option></select></div><div class="card">${hs.length?hs.map(h=>holdingRow43(h)).join(''):'<div class="empty">Keine Position im Filter.</div>'}</div><div class="rule-source" style="margin-top:9px">Depotwerte stammen aus dem Parqet-Snapshot. Cardinal Energy und Savaria werden HPOS-seitig Trade Republic zugeordnet.</div>`;$('#tx43').onclick=()=>route('transactions');$$('[data-half43]').forEach(b=>b.onclick=()=>{u.halal=b.dataset.half43;persist();renderPortfolio();});$('#sort43').onchange=e=>{u.sort=e.target.value;persist();renderPortfolio();};$$('[data-ring-account]').forEach(b=>b.onclick=()=>setAccount43(b.dataset.ringAccount));bindHoldingRows43();};

function watchAssets43(){const ids=new Set(state.watchlistEntries.filter(w=>w.status!=='ARCHIVED').map(w=>w.assetId));return state.assets.filter(a=>ids.has(a.assetId)&&a.portfolioRole!=='HOLDING').sort((a,b)=>a.name.localeCompare(b.name,'de'));}
function renderWatchlist43(){const ws=watchAssets43();$('#main').innerHTML=`<div class="section-head"><div><h1>Watchlist</h1><p>${ws.length} Titel · Werte fließen nicht in das Depot ein</p></div><button class="btn small" id="watchBack43">Analyse</button></div><div class="depot-controls43"><input class="input43" id="watchSearch43" placeholder="Name oder ISIN"><select class="select43" id="watchHalal43"><option value="ALL">Alle</option><option value="H1">H1</option><option value="H2">H2</option><option value="H0">H0</option><option value="UNKNOWN">Offen</option></select></div><div class="watch43" id="watchRows43"></div>`;const paint=()=>{const q=String($('#watchSearch43').value||'').toLowerCase(),hf=$('#watchHalal43').value;const rows=ws.filter(a=>(!q||`${a.name} ${a.isin||''}`.toLowerCase().includes(q))&&(hf==='ALL'||getEffectiveHalal(state,a).status===hf));$('#watchRows43').innerHTML=rows.length?rows.map(a=>{const h=getEffectiveHalal(state,a),w=state.watchlistEntries.find(x=>x.assetId===a.assetId);return `<button class="watch-row43" data-wa43="${esc(a.assetId)}"><div><strong>${esc(a.name)}</strong><small>${esc(a.isin||a.ticker||'')} · ${w?.source==='PARQET_MARKER'?'Parqet-Marker':'lokal'}</small></div><span class="badge ${roleClass43(h.status)}">${esc(h.status)}</span></button>`;}).join(''):'<div class="card empty">Kein Treffer.</div>';$$('[data-wa43]').forEach(b=>b.onclick=()=>openAsset(b.dataset.wa43));};$('#watchSearch43').oninput=paint;$('#watchHalal43').onchange=paint;$('#watchBack43').onclick=()=>route('analysis');paint();};
renderWatchlist=renderWatchlist43;

renderIncome=function(){if(!pq43)return;const u=ui43(),acct=account43()==='WATCHLIST'?'ALL':account43(),year=new Date().getFullYear(),ds=dividends43(acct).filter(d=>String(d.date).startsWith(String(year))),monthly=Array(12).fill(0),counts=Array(12).fill(0);for(const d of ds){const m=new Date(`${d.date}T00:00:00`).getMonth();monthly[m]+=Number(d.net||0);counts[m]++;}const max=Math.max(1,...monthly),sel=Number.isInteger(u.month)?u.month:null,months=['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'],total=monthly.reduce((a,b)=>a+b,0),selected=sel===null?null:ds.filter(d=>new Date(`${d.date}T00:00:00`).getMonth()===sel);$('#main').innerHTML=`<div class="section-head"><div><h1>Income</h1><p>${esc(ACCOUNT_LABEL43[acct])} · Netto-Ausschüttungen aus Parqet</p></div></div><div class="kpis43"><div class="kpi43"><small>${year} netto</small><strong>${fmt43(total)}</strong></div><div class="kpi43"><small>Ausschüttungen</small><strong>${ds.length}</strong></div><div class="kpi43"><small>Gesamt seit Importzeitraum</small><strong>${fmt43(dividends43(acct).reduce((s,d)=>s+Number(d.net||0),0))}</strong></div><div class="kpi43"><small>Ziel / Monat</small><strong>${fmt43(snapshot.effectiveProfile.rules.dividendGoalNetMonthlyEur.effectiveValue)}</strong></div></div><div class="card" style="margin-top:11px"><div class="top"><div><h3>Monatsentwicklung</h3><p>Balken antippen für exakte Werte</p></div>${sel!==null?'<button class="btn small" id="resetMonth43">Alle</button>':''}</div>${sel!==null?`<div class="income-pill43"><span>${months[sel]} · ${counts[sel]} Ausschüttung${counts[sel]===1?'':'en'}</span><strong>${fmt43(monthly[sel])}</strong></div>`:''}<div class="month-chart43">${monthly.map((v,i)=>`<div class="month43 ${sel===i?'selected':''}"><button data-m43="${i}" aria-label="${months[i]} ${fmt43(v)}"><div class="bar43" style="height:${Math.max(3,v/max*100)}%"></div><small>${months[i]}</small></button></div>`).join('')}</div></div><div class="section-head"><div><h2>${sel===null?'Ausschüttungen':'Ausschüttungen · '+months[sel]}</h2></div></div><div class="card">${(selected||ds).length?(selected||ds).slice().sort((a,b)=>b.date.localeCompare(a.date)).map(d=>{const a=byIsin43(d.isin);return `<button class="holding43" ${a?`data-divasset43="${esc(a.assetId)}"`:''}><div><strong>${esc(a?.name||d.isin)}</strong><small>${esc(dateFmt(d.date))} · ${esc(brokerLabel43(d.broker))}</small></div><div class="right"><strong>${fmt43(d.net)}</strong><small>brutto ${fmt43(d.gross)}</small></div></button>`;}).join(''):'<div class="empty">Keine Ausschüttung in der Auswahl.</div>'}</div>`;$$('[data-m43]').forEach(b=>b.onclick=()=>{u.month=Number(b.dataset.m43);persist();renderIncome();});$('#resetMonth43')?.addEventListener('click',()=>{u.month=null;persist();renderIncome();});$$('[data-divasset43]').forEach(b=>b.onclick=()=>openAsset(b.dataset.divasset43,'activities'));};

function relevantAlerts43(){const acct=account43(),ids=new Set(holdings43(acct==='WATCHLIST'?'ALL':acct).map(h=>byIsin43(h.isin)?.assetId).filter(Boolean));return alerts.filter(a=>!['DONE','SNOOZED'].includes(a.status)&&(!a.assetId||ids.has(a.assetId)));}
function renderAnalysis43(){recompute();const acct=account43(),assets=acct==='WATCHLIST'?watchAssets43():holdings43(acct).map(h=>byIsin43(h.isin)).filter(Boolean),hs={H1:0,H2:0,H0:0,UNKNOWN:0};for(const a of assets){const s=getEffectiveHalal(state,a).status;hs[s in hs?s:'UNKNOWN']++;}const aa=relevantAlerts43(),crit=aa.filter(a=>a.severity==='CRITICAL').length,warn=aa.filter(a=>a.severity==='WARN').length;$('#main').innerHTML=`<div class="section-head"><div><h1>Analyse</h1><p>${esc(ACCOUNT_LABEL43[acct])} · Regeln, Halal und Datenqualität</p></div><button class="btn primary small" id="recalc43">Neu prüfen</button></div><div class="analysis-grid43"><div class="analysis-card43"><small>Kritisch</small><strong class="neg43">${crit}</strong></div><div class="analysis-card43"><small>Prüfen</small><strong>${warn}</strong></div><div class="analysis-card43"><small>Halal offen</small><strong>${hs.UNKNOWN}</strong></div><div class="analysis-card43"><small>H2 / H0</small><strong>${hs.H2+hs.H0}</strong></div></div><button class="action43" id="halal43"><strong>Halal Register</strong><small>Automatische Vorprüfung bleibt UNKNOWN, bis eine belastbare Screening-Schnittstelle vorliegt; manuelle Belege härten den Status.</small></button><button class="action43" id="watch43"><strong>Watchlist · ${watchAssets43().length} Titel</strong><small>Parqet-Marker sind Informationsanker und niemals Depotbestand.</small></button><button class="action43" id="strategy43"><strong>Strategie & Limits</strong><small>Sukuk-Ziel, Positionsregeln, Quellenpriorität und weitere HPOS-Regeln.</small></button><div class="section-head"><div><h2>Aktive Hinweise</h2><p>${aa.length} für die gewählte Ansicht</p></div></div><div class="stack">${aa.length?aa.slice(0,12).map(a=>alertCard(a)).join(''):'<div class="card empty">Keine aktive Regelabweichung aus den prüfbaren Daten.</div>'}</div>`;$('#recalc43').onclick=()=>{recompute();toast('Analyse aktualisiert');renderAnalysis43();};$('#halal43').onclick=()=>route('halal');$('#watch43').onclick=()=>{ui43().account='WATCHLIST';persist();syncHeader43();renderWatchlist43();};$('#strategy43').onclick=()=>route('strategy');bindAlertButtons();}

function renderSettings43(){const imp=state.appMeta.parqetImport;$('#main').innerHTML=`<div class="section-head"><div><h1>Einstellungen</h1><p>Selten benötigte Verwaltung, getrennt von der täglichen Navigation</p></div></div><div class="settings43"><div class="setting-group43"><div class="setting-title43">Investment & Regeln</div><button class="setting-row43" data-set43="strategy"><span>⚙</span><span><strong>Strategie & Limits</strong><small>HPOS-Regeln und persönliche Overrides</small></span><span>›</span></button><button class="setting-row43" data-set43="halal"><span>☑</span><span><strong>Halal Register</strong><small>Prüfungen, Quellen, Konflikte</small></span><span>›</span></button></div><div class="setting-group43"><div class="setting-title43">Depot & Daten</div><button class="setting-row43" id="import43"><span>↻</span><span><strong>Parqet Importstatus</strong><small>${imp?.realHoldings||0} Positionen · ${imp?.watchMarkers||0} Marker · ${esc(dataAge43())}</small></span><span>›</span></button><button class="setting-row43" data-set43="data"><span>⇩</span><span><strong>Daten & Backup</strong><small>Lokales Backup und Wiederherstellung</small></span><span>›</span></button><button class="setting-row43" data-set43="diagnostics"><span>!</span><span><strong>Diagnose</strong><small>Datenqualität und technische Hinweise</small></span><span>›</span></button></div><div class="setting-group43"><div class="setting-title43">App</div><button class="setting-row43" id="sources43"><span>◉</span><span><strong>News & Quellen</strong><small>Primär-, Research- und Discovery-Quellen</small></span><span>›</span></button><button class="setting-row43" id="profile43"><span>○</span><span><strong>Profil & Depots</strong><small>Gesamtdepot, Scalable, Trade Republic, Watchlist</small></span><span>›</span></button></div></div>`;$$('[data-set43]').forEach(b=>b.onclick=()=>route(b.dataset.set43));$('#sources43').onclick=()=>route('news');$('#profile43').onclick=openProfile43;$('#import43').onclick=openImportStatus43;}
function openImportStatus43(){openModal('Parqet Importstatus',`<div class="stack"><div class="notice success"><strong>${esc(pq43?.reconciliation?.status||'UNKNOWN')}</strong><p>Reales Depot und Watchlist-Regel wurden getrennt reconciliert.</p></div><div class="card"><div class="details"><div class="kv"><span>Parqet gemeldet</span><strong>${fmt43(pq43.kpis.parqetReportedTotal)}</strong></div><div class="kv"><span>HPOS Depot</span><strong>${fmt43(pq43.kpis.importedPortfolioTotal)}</strong></div><div class="kv"><span>Marker ausgeschlossen</span><strong>${fmt43(pq43.kpis.markerValueExcluded)}</strong></div><div class="kv"><span>Scalable</span><strong>${fmt43(pq43.kpis.scalableTotal)}</strong></div><div class="kv"><span>Trade Republic</span><strong>${fmt43(pq43.kpis.tradeRepublicTotal)}</strong></div></div></div><div class="notice info">Parqet wird ohne kostenpflichtige Analysefunktionen verwendet. Ein neuer Bestandssync erfordert einen neuen Connector-Snapshot; GitHub Actions besitzt keine Parqet-Anmeldedaten.</div></div>`);}

const baseAsset43=renderAssetDetail;renderAssetDetail=function(){baseAsset43();const a=state.assets.find(x=>x.assetId===currentAssetId);if(!a)return;const h=(pq43?.holdings||[]).find(x=>String(x.isin).toUpperCase()===String(a.isin||'').toUpperCase());const head=$('#main .asset-head');if(head&&h){const tag=document.createElement('span');tag.className='badge info';tag.textContent=brokerLabel43(h.broker);head.appendChild(tag);}else if(head&&a.portfolioRole==='WATCHLIST'){const tag=document.createElement('span');tag.className='badge info';tag.textContent='Watchlist';head.appendChild(tag);}};

const baseTx43=renderTransactions;renderTransactions=function(){baseTx43();const head=$('#main .section-head');if(head){const n=document.createElement('div');n.className='notice info';n.style.marginTop='10px';n.innerHTML='<strong>Bestands-Snapshot</strong><p>Die lokalen Journalzeilen bilden den importierten aktuellen Bestand und relevante Dividenden ab. Eine gegebenenfalls umfangreichere externe Aktivitätshistorie ist nicht vollständig als lokales Journal gespiegelt.</p>';head.after(n);}};

async function boot43(){css43();pq43=await load43();if(pq43){const changed=syncState43(pq43);if(changed)recompute();}installHeader43();renderNav();let p=location.hash.slice(1)||'dashboard';if(p==='radar')p='analysis';if(p==='more')p='settings';route(p,false);document.title='HPOS Alpha 4.3 · Real Portfolio';}
boot43();
})();
