/* HPOS Alpha 4.4.1 – UX Consolidation + Thesis Intelligence */
(()=>{'use strict';
const VERSION='1.3.0-alpha.4.4.1';
const DAY=86400000;
const esc441=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num441=v=>Number(v||0);
const fmt441=(v,d=1)=>Number(v).toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d});
const eur441=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));
function css441(){if(document.getElementById('alpha441css'))return;const s=document.createElement('style');s.id='alpha441css';s.textContent=`
:root{--bg:#08111c;--panel:#0e1927;--panel2:#142235;--line:#26364a;--text:#f3f6fa;--muted:#91a4ba;--green:#24c98b;--orange:#e7a847;--red:#e26a6a;--blue:#5b9cf6}
.a441{display:grid;gap:12px}.a441 .card{margin:0}.a441-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.a441-head h3{margin:0}.a441-head p{margin:3px 0 0}.a441-hero{padding:14px 15px}.a441-value{font-size:30px;font-weight:850;line-height:1}.a441-sub{color:var(--muted);font-size:12px;margin-top:5px}.a441-decision{border-left:4px solid var(--orange)}.a441-decision.good{border-left-color:var(--green)}.a441-decision.bad{border-left-color:var(--red)}.a441-action{font-size:25px;font-weight:850;margin-top:3px}.a441-chips{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}.a441-chip{border:1px solid var(--line);border-radius:999px;padding:6px 9px;font-size:11px;color:var(--muted)}.a441-chip.good{color:var(--green);border-color:rgba(36,201,139,.35)}.a441-chip.warn{color:var(--orange);border-color:rgba(231,168,71,.35)}.a441-chip.bad{color:var(--red);border-color:rgba(226,106,106,.35)}.a441-chip.info{color:var(--blue);border-color:rgba(91,156,246,.35)}.a441-reasons{display:grid;gap:7px;margin-top:12px}.a441-reason{display:grid;grid-template-columns:28px 1fr;gap:8px;align-items:start}.a441-reason>span{width:28px;height:28px;border-radius:8px;background:var(--panel2);display:grid;place-items:center}.a441-reason small{display:block;color:var(--muted);margin-top:2px;line-height:1.35}.a441-chart svg{width:100%;height:170px;display:block;margin:8px 0}.a441-line{fill:none;stroke:var(--blue);stroke-width:3;vector-effect:non-scaling-stroke}.a441-entry{stroke:var(--orange);stroke-width:1.5;stroke-dasharray:6 5;vector-effect:non-scaling-stroke}.a441-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.a441-kpi{border:1px solid var(--line);border-radius:10px;padding:9px}.a441-kpi small{display:block;color:var(--muted);font-size:10px}.a441-kpi strong{display:block;margin-top:3px;font-size:13px}.a441-up{color:var(--green)}.a441-down{color:var(--red)}.a441-news{display:grid;gap:7px}.a441-newsitem{border:1px solid var(--line);border-radius:11px;padding:10px}.a441-newsitem h4{font-size:13px;line-height:1.35;margin:5px 0}.a441-newsitem p{font-size:11px;color:var(--muted);margin:0}.a441-thesis{display:grid;gap:8px}.a441-thesisrow{border:1px solid var(--line);border-radius:11px;padding:10px}.a441-thesisrow small{display:block;color:var(--muted);text-transform:uppercase;font-size:9px;letter-spacing:.045em}.a441-thesisrow p{font-size:12px;margin:5px 0 0;color:var(--muted)}.a441-analysis{display:grid;gap:10px}.a441-block{border:1px solid var(--line);border-radius:12px;padding:11px}.a441-block h4{margin:0 0 6px}.a441-block p{font-size:12px;margin:4px 0}.a441-actions{display:flex;gap:7px;flex-wrap:wrap}.a441-method summary{font-weight:750}.a441-tab-hide{display:none!important}
@media(min-width:760px){.a441-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.a441-two{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}}
`;document.head.appendChild(s)}
function localHolding441(asset){try{return window.HPOSLocalProjection433?.().holdings?.find(h=>String(h.isin||'').toUpperCase()===String(asset.isin||'').toUpperCase())||null}catch{return null}}
function weight441(h){try{const p=window.HPOSLocalProjection433?.(),t=Number(p?.kpis?.importedPortfolioTotal||0);return h&&t>0?Number(h.currentValue||0)/t*100:null}catch{return null}}
function thesis441(asset,b){const h=localHolding441(asset),w=weight441(h),hal=b.decision?.halal?.status||'UNKNOWN',s=b.stats,events=b.events||[],aa=b.decision?.alerts||[];const evidence=[],risks=[],catalysts=[],invalid=[];
if(hal==='H1')evidence.push('Halal-Gate ist mit einem effektiven H1 geöffnet.');else if(hal==='H0')invalid.push('H0 ist ein Hard Veto: kein Neukauf/Nachkauf; Exit-/Veto-Review.');else if(hal==='H2')invalid.push('H2 friert die Kauf-/Aufstockungslogik bis zum Review ein.');else invalid.push('UNKNOWN ist keine Kauf-/Aufstockungsfreigabe; Prüfung dokumentieren.');
if(w!=null){if(w>=1&&w<=8)evidence.push(`Depotgewicht ${fmt441(w)} % liegt in einem arbeitsfähigen Korridor.`);else if(w>8)risks.push(`Konzentration ${fmt441(w)} %: Portfolio-Fit vor zusätzlichem Kapital prüfen.`);else risks.push(`Position ${fmt441(w)} %: These gegen Opportunitätskosten und Mindestgröße prüfen.`)}
if(s){if(s.p3m!=null&&s.p3m>15)risks.push(`3M-Momentum +${fmt441(s.p3m)} %: Preisdisziplin vor Nachkauf.`);if(s.p3m!=null&&s.p3m<-12)catalysts.push(`3M-Rückgang ${fmt441(s.p3m)} %: Review-Fenster nur bei intakter These.`);if(s.drawdown!=null&&s.drawdown<-15)catalysts.push(`${fmt441(s.drawdown)} % unter 52W-Hoch: Bewertungskontext prüfen, kein automatisches Kaufsignal.`)}
const neg=events.filter(x=>x.impact?.dir==='neg').length,pos=events.filter(x=>x.impact?.dir==='pos').length;if(pos)evidence.push(`${pos} positives entscheidungsrelevantes Ereignis im 7-Tage-Fenster.`);if(neg)risks.push(`${neg} negatives entscheidungsrelevantes Ereignis im 7-Tage-Fenster.`);if(aa.length)risks.push(`${aa.length} aktive HPOS-Regelmeldung${aa.length===1?'':'en'} offen.`);
let confidence=35+(s?20:0)+(hal!=='UNKNOWN'?20:0)+(events.length?10:0)+(h?10:0)-Math.min(20,aa.length*4);confidence=Math.max(15,Math.min(95,confidence));const thesisState=invalid.length?'GATE OFFEN':risks.length?'BEOBACHTEN':'INTAKT';return{evidence:evidence.slice(0,3),risks:risks.slice(0,3),catalysts:catalysts.slice(0,2),invalid:invalid.slice(0,2),confidence,thesisState};}
function svg441(stats,h){if(!stats?.rows?.length)return'';const rows=stats.rows.slice(-260),vals=rows.map(x=>Number(x[1])),min=Math.min(...vals),max=Math.max(...vals),w=600,hh=170,p=8,span=Math.max(.0001,max-min),pts=vals.map((v,i)=>`${p+i/(vals.length-1)*(w-2*p)},${hh-p-(v-min)/span*(hh-2*p)}`).join(' ');let entry='';const ep=Number(h?.avgEntryPrice||h?.avgCost||0);if(ep>0&&ep>=min&&ep<=max){const y=hh-p-(ep-min)/span*(hh-2*p);entry=`<line class="a441-entry" x1="${p}" y1="${y}" x2="${w-p}" y2="${y}"/>`;}return`<svg viewBox="0 0 ${w} ${hh}" preserveAspectRatio="none" aria-label="Kursentwicklung"><polyline class="a441-line" points="${pts}"/>${entry}</svg>`}
function hero441(asset,b){const h=localHolding441(asset),w=weight441(h);return`<div class="card a441-hero"><div class="a441-head"><div><div class="a441-value">${h?eur441(h.currentValue):'—'}</div><div class="a441-sub">${h?`${Number(h.unrealizedReturnNet)>=0?'+':''}${fmt441(h.unrealizedReturnNet)} % seit Einstand`:'Lokale Position nicht verfügbar'}</div></div>${w!=null?`<span class="badge info">${fmt441(w)} % Depot</span>`:''}</div></div>`}
function decision441(b,t){const d=b.decision,tone=d.tone||'warn';return`<div class="card a441-decision ${tone}"><div class="a441-head"><div><small>HPOS ENTSCHEIDUNGSLAGE</small><div class="a441-action">${esc441(d.action)}</div><p>${esc441(t.invalid[0]||t.risks[0]||t.evidence[0]||'Keine starke Abweichung aus den verfügbaren Daten.')}</p></div><span class="badge ${tone==='good'?'good':tone==='bad'?'bad':'warn'}">Konfidenz ${t.confidence}%</span></div><div class="a441-chips"><span class="a441-chip ${d.halal?.status==='H1'?'good':'warn'}">☪ ${esc441(d.halal?.status||'UNKNOWN')}</span>${b.stats?.p3m!=null?`<span class="a441-chip ${b.stats.p3m>=0?'good':'bad'}">↗ 3M ${b.stats.p3m>=0?'+':''}${fmt441(b.stats.p3m)} %</span>`:''}${b.stats?.drawdown!=null?`<span class="a441-chip info">◒ 52W ${fmt441(b.stats.drawdown)} %</span>`:''}<span class="a441-chip info">These ${esc441(t.thesisState)}</span></div><div class="a441-reasons">${(d.reasons||[]).slice(0,3).map(r=>`<div class="a441-reason"><span>${r[0]}</span><div><strong>${esc441(r[1])}</strong><small>${esc441(r[2])}</small></div></div>`).join('')}</div></div>`}
function market441(asset,b){const h=localHolding441(asset),s=b.stats,file=b.file;if(!s||!file)return`<div class="card"><h3>Kurs & Position</h3><div class="empty">Keine belastbare Marktzeitreihe.</div></div>`;const cur=Number(file.regularMarketPriceEur);return`<div class="card a441-chart"><div class="a441-head"><div><h3>Kurs & Position</h3><p>Marktdaten plus persönlicher Einstand</p></div><span class="badge info">CURRENT</span></div>${svg441(s,h)}<div class="a441-grid"><div class="a441-kpi"><small>Kurs</small><strong>${Number.isFinite(cur)?eur441(cur):'—'}</strong></div><div class="a441-kpi"><small>Ø Einstand</small><strong>${h?eur441(h.avgEntryPrice||h.avgCost):'—'}</strong></div><div class="a441-kpi"><small>1 Monat</small><strong class="${s.p1m>=0?'a441-up':'a441-down'}">${s.p1m==null?'—':`${s.p1m>=0?'+':''}${fmt441(s.p1m)} %`}</strong></div><div class="a441-kpi"><small>1 Jahr</small><strong class="${s.p1y>=0?'a441-up':'a441-down'}">${s.p1y==null?'—':`${s.p1y>=0?'+':''}${fmt441(s.p1y)} %`}</strong></div></div><div class="rule-source">Gestrichelte Linie = lokaler Ø Einstand, soweit im sichtbaren Kursbereich. Markt: ${esc441(file.provider||'')}.</div></div>`}
function news441(events){return`<div class="card"><div class="a441-head"><div><h3>Was hat sich verändert?</h3><p>Maximal 3 neue, gebündelte Ereignisse</p></div><span class="badge info">${events.length}</span></div><div class="a441-news">${events.length?events.slice(0,3).map(x=>`<div class="a441-newsitem"><span class="badge ${x.impact?.dir==='neg'?'bad':x.impact?.dir==='pos'?'good':'info'}">${esc441(x.impact?.label||'NEUTRAL')}</span><h4>${esc441(x.lead.title)}</h4><p><strong>HPOS:</strong> ${esc441(x.impact?.text||'Keine eindeutige Wirkung.')}${x.count>1?` · ${x.count} ähnliche Meldungen gebündelt`:''}</p></div>`).join(''):'<div class="empty">Keine entscheidungsrelevante Veränderung im aktuellen 7-Tage-Fenster.</div>'}</div></div>`}
function thesisCard441(t){const rows=[['✓','Evidenz / These intakt',t.evidence],['▲','Risiken',t.risks],['↗','Katalysatoren',t.catalysts],['⛔','Invalidierung / Gate',t.invalid]];return`<div class="card"><div class="a441-head"><div><h3>Investmentthese</h3><p>These → Evidenz → Risiko → Invalidierung</p></div><span class="badge info">Methodik</span></div><div class="a441-thesis">${rows.map(([ic,k,a])=>`<div class="a441-thesisrow"><small>${ic} ${k}</small>${a.length?a.map(x=>`<p>${esc441(x)}</p>`).join(''):'<p>Kein belastbarer Punkt aus den aktuell verfügbaren Daten.</p>'}</div>`).join('')}</div><div class="rule-source">Harte Gates schlagen weiche Signale. Momentum oder News allein erzeugen keine Kaufentscheidung.</div></div>`}
function method441(b,t){return`<details class="card a441-method"><summary>Methodik & Datenqualität</summary><p>HPOS trennt Halal-Gates, Portfolio-Fit, Investmentthese, Fundamentaldaten, Markt/Timing und News-Evidenz. Fehlende Daten senken die Konfidenz, statt eine Freigabe zu erfinden.</p><div class="a441-chips"><span class="a441-chip">Markt ${b.stats?'✓':'?'}</span><span class="a441-chip">Halal ${esc441(b.decision.halal?.status||'UNKNOWN')}</span><span class="a441-chip">News ${b.events.length}</span><span class="a441-chip">Regeln ${b.decision.alerts?.length||0}</span><span class="a441-chip info">Konfidenz ${t.confidence}%</span></div></details>`}
function overview441(asset,b,t){return`<div class="a441">${hero441(asset,b)}${decision441(b,t)}${market441(asset,b)}${news441(b.events)}${thesisCard441(t)}${method441(b,t)}<div class="card"><div class="a441-actions"><button class="btn small" data-a441-halal>Halal prüfen</button><button class="btn small" data-a441-buy>Nachkaufen</button><button class="btn small" data-a441-sell>Teilverkauf</button><button class="btn small" data-a441-div>Dividende</button></div></div></div>`}
function analysis441(asset,b,t){const h=localHolding441(asset),w=weight441(h),s=b.stats;const scenarioBuy=w==null?'Gewichtung nicht berechenbar.':`Ein Nachkauf erhöht die aktuelle Gewichtung von ${fmt441(w)} %. Vor Ausführung Zielkorridor, Sektor-Cap und Halal-Gate erneut prüfen.`;return`<div class="a441 a441-analysis"><div class="card"><div class="a441-head"><div><h3>Analyse</h3><p>Vier Fragen statt weiterer Warnkarten</p></div><span class="badge info">Konfidenz ${t.confidence}%</span></div></div><div class="a441-two"><div class="a441-block"><h4>1 · Portfolio-Fit</h4><p>${w==null?'Depotgewicht unbekannt.':`Aktuelles Depotgewicht: ${fmt441(w)} %.`}</p><p>${(b.decision.alerts||[]).length?`${b.decision.alerts.length} aktive Regelmeldung${b.decision.alerts.length===1?'':'en'} beeinflussen den Portfolio-Fit.`:'Keine assetbezogene Regelverletzung erkannt.'}</p></div><div class="a441-block"><h4>2 · Performance & Timing</h4><p>${s?`1M ${s.p1m>=0?'+':''}${fmt441(s.p1m)} %, 3M ${s.p3m>=0?'+':''}${fmt441(s.p3m)} %, 1J ${s.p1y>=0?'+':''}${fmt441(s.p1y)} %.`:'Keine Marktzeitreihe.'}</p><p>${s?`Abstand zum 52W-Hoch: ${fmt441(s.drawdown)} %.`:''}</p></div></div><div class="a441-two"><div class="a441-block"><h4>3 · These & Risiken</h4>${[...t.invalid,...t.risks,...t.evidence].slice(0,4).map(x=>`<p>• ${esc441(x)}</p>`).join('')}</div><div class="a441-block"><h4>4 · Entscheidungsszenario</h4><p>${esc441(scenarioBuy)}</p><p>Verkaufsszenario: realisierte Wirkung erst nach Transaktionssimulation belastbar; kein automatischer Verkauf.</p></div></div>${thesisCard441(t)}${method441(b,t)}</div>`}
async function build441(asset){const b=await window.HPOSDecision44.bundle(asset),t=thesis441(asset,b);return{b,t}}
async function hydrate441(assetId,tab){const host=document.getElementById('asset441');if(!host||host.dataset.asset!==assetId)return;const asset=(state.assets||[]).find(a=>a.assetId===assetId);if(!asset)return;try{const {b,t}=await build441(asset);if(!document.getElementById('asset441')||document.getElementById('asset441').dataset.asset!==assetId)return;host.innerHTML=tab==='hpos'?analysis441(asset,b,t):overview441(asset,b,t);host.querySelector('[data-a441-halal]')?.addEventListener('click',()=>{currentAssetTab='halal';renderAssetDetail()});host.querySelector('[data-a441-buy]')?.addEventListener('click',()=>openEntryModal('BUY',assetId));host.querySelector('[data-a441-sell]')?.addEventListener('click',()=>openEntryModal('SELL',assetId));host.querySelector('[data-a441-div]')?.addEventListener('click',()=>openEntryModal('DIVIDEND',assetId));}catch(err){host.innerHTML=`<div class="notice warn">Thesis Intelligence konnte nicht vollständig laden: ${esc441(err.message)}</div>`}}
const baseTab441=typeof renderAssetTab==='function'?renderAssetTab:null;if(baseTab441){renderAssetTab=function(v,tab){if(!v?.asset)return baseTab441(v,tab);if(tab==='overview'||tab==='hpos'){setTimeout(()=>hydrate441(v.asset.assetId,tab),0);return`<div id="asset441" data-asset="${esc441(v.asset.assetId)}" class="a441"><div class="card"><p>HPOS verdichtet Entscheidung, Kurs, Ereignisse und These …</p></div></div>`}return baseTab441(v,tab)}}
function tabs441(){document.querySelectorAll('[data-asset-tab]').forEach(b=>{const t=b.dataset.assetTab;if(t==='overview')b.textContent='Übersicht';else if(t==='hpos')b.textContent='Analyse';else if(t==='activities')b.textContent='Historie';else if(t==='halal'||t==='news')b.classList.add('a441-tab-hide')});}
const obs441=new MutationObserver(()=>{clearTimeout(window.__tabs441);window.__tabs441=setTimeout(tabs441,10)});obs441.observe(document.body,{childList:true,subtree:true});css441();tabs441();window.HPOSThesis441={build:thesis441,version:VERSION};})();