/* HPOS Alpha 4.2 – Multi-Source News UX */
(() => {
'use strict';
const FEED='../data/news/news_feed.json',STATUS='../data/news/news_status.json',REG='../config/source_registry.json';
let feed=null,status=null,loading=null,limit=20,registry=null;
const rank={PRIMARY:0,PROFESSIONAL:1,RESEARCH:2,DISCOVERY:3};
const norm=v=>String(v??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
async function j(url){const r=await fetch(`${url}${url.includes('?')?'&':'?'}v=42`,{cache:'no-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function load(force=false){if(feed&&!force)return feed;if(loading&&!force)return loading;loading=Promise.all([j(FEED),j(STATUS)]).then(([f,s])=>{feed=f;status=s;return f}).catch(()=>{feed={items:[],assetIndex:{},loadError:true};status={state:'ERROR',message:'News-Snapshot nicht erreichbar.'};return feed}).finally(()=>loading=null);return loading}
function aid(n){const m=feed?.assetIndex?.[n.assetKey]||{},isin=String(m.isin||'').toUpperCase();if(isin){const a=state.assets.find(x=>String(x.isin||'').toUpperCase()===isin);if(a)return a.assetId}const t=norm(m.ticker);if(t){const hits=state.assets.filter(x=>norm(x.ticker)===t);if(hits.length===1)return hits[0].assetId}const al=[m.name,...(m.aliases||[])].map(norm);for(const a of state.assets){if([a.name,a.ticker,a.isin].map(norm).some(x=>al.includes(x)))return a.assetId}return null}
function all(assetId=null){const auto=(feed?.items||[]).map(n=>{const m=feed?.assetIndex?.[n.assetKey]||{};return{...n,assetId:aid(n),assetName:m.name,origin:'AUTO',sourceTier:n.sourceTier||(n.primarySource?'PRIMARY':'DISCOVERY')}}),local=(state.newsEntries||[]).map(n=>({...n,origin:'MANUAL',sourceTier:n.sourceTier||'RESEARCH'}));const a=[...auto,...local].filter(n=>!assetId||n.assetId===assetId);const seen=new Set(),out=[];for(const n of a.sort((x,y)=>String(y.publishedAt||y.updatedAt||'').localeCompare(String(x.publishedAt||x.updatedAt||'')))){const k=n.url||`${n.assetId||n.assetKey}|${norm(n.title)}`;if(seen.has(k))continue;seen.add(k);out.push(n)}return out}
function card(n){const a=n.assetId?state.assets.find(x=>x.assetId===n.assetId):null,t=n.sourceTier||'DISCOVERY',lab={PRIMARY:'Primär',PROFESSIONAL:'Profi',RESEARCH:'Research',DISCOVERY:'Discovery'}[t]||t;return`<div class="card news-card" data-nt42="${esc(t)}" data-nd42="${esc(n.publishedAt||n.updatedAt||'')}" data-nq42="${esc(`${n.title||''} ${n.source||''} ${n.assetName||a?.name||''}`.toLowerCase())}" style="${t==='PRIMARY'?'border-left:3px solid var(--green)':t==='PROFESSIONAL'?'border-left:3px solid var(--blue)':t==='RESEARCH'?'border-left:3px solid var(--orange)':''}"><div class="top"><div><strong>${esc(n.title||'Meldung')}</strong>${a?`<button class="asset-link" data-na42="${esc(a.assetId)}">${esc(a.name)}</button>`:n.assetName?`<div class="sub">${esc(n.assetName)}</div>`:''}</div><span class="badge info">${esc(n.source||'Quelle unbekannt')}</span></div><div class="asset-badges"><span class="badge ${t==='PRIMARY'?'good':t==='RESEARCH'?'warn':'info'}">${esc(lab)}</span><span class="badge">${n.origin==='AUTO'?'Automatisch':'Manuell'}</span>${n.provider?`<span class="badge">${esc(n.provider)}</span>`:''}</div><p>${esc(n.summary||n.note||(n.origin==='AUTO'?'Gefundene Meldung. Inhalt noch nicht automatisch als Investmentwirkung bewertet.':'Keine Zusammenfassung gespeichert.'))}</p><div class="rule-source">${esc(dateFmt(n.publishedAt||n.updatedAt))}</div>${n.url?`<div class="action-row"><a class="btn small" href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">Quelle öffnen</a></div>`:''}</div>`}
async function sources(){if(!registry){try{registry=await j(REG)}catch{registry={sources:[]}}}openModal('HPOS Quellenregister',`<div class="stack">${['PRIMARY','PROFESSIONAL','RESEARCH','HALAL','DISCOVERY'].map(g=>{const xs=(registry.sources||[]).filter(s=>s.tier===g);return xs.length?`<div class="card"><h3>${g}</h3>${xs.map(s=>`<div class="list-row"><strong>${esc(s.name)}</strong><div class="sub">${esc(s.use||'')}</div><div class="rule-source">${esc(s.automationMode||'')} · ${esc(s.cost||'')}</div></div>`).join('')}</div>`:''}).join('')}</div>`)}
function ds(){return status||state.dataStatus.news||{state:'UNKNOWN',message:'News-Status unbekannt.'}}
renderNews=async function(){const u=state.userProfile.ui=state.userProfile.ui||{};u.n42=u.n42||{tier:'ALL',sort:'priority',q:''};const f=u.n42;if(!feed){$('#main').innerHTML='<div class="card">News werden geladen …</div>';await load();if(currentPage!=='news')return}const d=ds(),rows=all(),items=rows.slice(0,limit);$('#main').innerHTML=`<div class="section-head"><div><h1>News</h1><p>Primärquellen → Profi → Research → Discovery</p></div><div class="action-row" style="margin:0"><button class="btn small" id="nsrc42">Quellen</button><button class="btn small" id="nref42">Neu laden</button><button class="btn small" id="newsAi">Mit ChatGPT prüfen</button><button class="btn primary small" id="newsAdd">＋ Meldung</button></div></div><div class="card"><div class="top"><div><h3>Datenstatus</h3><p>${esc(d.message||'')}</p></div>${dataStateBadge(d)}</div>${feed.directSources?`<div class="rule-source">Direktquellen: ${feed.directSources.map(x=>`${esc(x.source)} ${x.ok?'✓':'!'}`).join(' · ')}</div>`:''}</div><div class="chips42" style="margin-top:12px">${[['ALL','Alle'],['PRIMARY','Primär'],['PROFESSIONAL','Profi'],['RESEARCH','Research'],['DISCOVERY','Discovery']].map(([x,l])=>`<button class="chip42 ${f.tier===x?'active':''}" data-nf42="${x}">${l}</button>`).join('')}</div><div class="controls42"><input id="nq42" value="${esc(f.q||'')}" placeholder="Titel, Quelle oder Asset"><select id="ns42"><option value="priority">Priorität</option><option value="date">Neueste</option></select></div><div class="stack" id="nst42">${items.length?items.map(card).join(''):'<div class="card empty">Keine Meldungen im Snapshot.</div>'}</div>${rows.length>limit?'<div class="action-row"><button class="btn" id="nmore42">Weitere 20</button></div>':''}`;$('#ns42').value=f.sort;const apply=()=>{const cs=[...$$('.news-card')];cs.forEach(c=>{const ok=(f.tier==='ALL'||c.dataset.nt42===f.tier)&&(!f.q||c.dataset.nq42.includes(String(f.q).toLowerCase()));c.style.display=ok?'':'none'});if(cs.length){const p=cs[0].parentElement;cs.sort((a,b)=>f.sort==='date'?String(b.dataset.nd42).localeCompare(String(a.dataset.nd42)):(rank[a.dataset.nt42]??9)-(rank[b.dataset.nt42]??9)||String(b.dataset.nd42).localeCompare(String(a.dataset.nd42))).forEach(c=>p.appendChild(c))}};$$('[data-nf42]').forEach(b=>b.onclick=()=>{f.tier=b.dataset.nf42;persist();renderNews()});$('#nq42').oninput=e=>{f.q=e.target.value;persist();apply()};$('#ns42').onchange=e=>{f.sort=e.target.value;persist();apply()};$('#nmore42')?.addEventListener('click',()=>{limit+=20;renderNews()});$('#nsrc42').onclick=sources;$('#nref42').onclick=async()=>{feed=null;status=null;limit=20;await load(true);toast('News-Snapshot neu geladen');renderNews()};$('#newsAdd').onclick=()=>openNewsForm();$('#newsAi').onclick=openAiHandoff;$$('[data-na42]').forEach(b=>b.onclick=()=>openAsset(b.dataset.na42,'news'));apply();renderNav()};
const oldTab=renderAssetTab;renderAssetTab=function(v,tab){if(tab!=='news')return oldTab(v,tab);if(!feed&&!loading)load().then(()=>{if(currentPage==='asset'&&currentAssetTab==='news')renderAssetDetail()});const rows=feed?all(v.asset.assetId):[],items=rows.slice(0,15);return`<div class="section-head"><div><h2>News</h2><p>${items.length}${rows.length>15?` von ${rows.length}`:''} · priorisierte Quellen</p></div><button class="btn primary small" data-add-news>＋ Meldung</button></div><div class="stack">${items.length?items.map(card).join(''):`<div class="card empty">${feed?'Keine Meldung zu diesem Asset.':'News werden geladen …'}</div>`}</div>`};
load();
})();
